// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.mjs";

function make(tokens) {
  let rows = {};
  let lastRow = {
    contents: 0
  };
  tokens.forEach((tok, i) => {
    let match = tok.kind;
    if (typeof match !== "object") {
      switch (match) {
        case "Newline" :
        case "EOF" :
          return;
      }
    } else if (match.TAG === "Whitespace") {
      return;
    }
    let row = tok.position.row;
    if (row > lastRow.contents) {
      lastRow.contents = row;
    }
    let key = row.toString();
    let existing = Core__Option.getOr(rows[key], []);
    existing.push([
      tok.position.col,
      tok.endPosition.col,
      i
    ]);
    rows[key] = existing;
  });
  return {
    rows: rows,
    lastRow: lastRow.contents
  };
}

function rowTokensIndices(g, row) {
  return Core__Option.getOr(g.rows[row.toString()], []);
}

function tokenAt(g, tokens, row, col) {
  let entries = rowTokensIndices(g, row);
  let found = {
    contents: undefined
  };
  entries.forEach(param => {
    if (col >= param[0] && col < param[1]) {
      found.contents = tokens[param[2]];
      return;
    }
  });
  return found.contents;
}

function charAt(g, tokens, row, col) {
  let tok = tokenAt(g, tokens, row, col);
  if (tok === undefined) {
    return " ";
  }
  let rel = col - tok.position.col | 0;
  if (rel >= 0 && rel < tok.text.length) {
    return tok.text.charAt(rel);
  } else {
    return " ";
  }
}

function lastRow(g) {
  return g.lastRow;
}

export {
  make,
  rowTokensIndices,
  tokenAt,
  charAt,
  lastRow,
}
/* No side effect */
