// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Token from "../types/Token.mjs";
import * as Scanner from "./Scanner.mjs";

function isIdentChar(cp) {
  if (cp >= 48 && cp <= 57 || cp >= 65 && cp <= 90 || cp >= 97 && cp <= 122) {
    return true;
  } else {
    return cp >= 128;
  }
}

function readRun(s, ch) {
  let count = 0;
  while (!Scanner.isAtEnd(s) && Scanner.peek(s) === ch) {
    Scanner.advance(s);
    count = count + 1 | 0;
  };
  return count;
}

function readIdentifier(s) {
  let start = s.offset;
  while (!Scanner.isAtEnd(s) && isIdentChar(Scanner.peekCodePoint(s))) {
    Scanner.advance(s);
  };
  return s.source.slice(start, s.offset);
}

function readWhitespaceRun(s) {
  let startCol = s.col;
  let keep = true;
  while (keep && !Scanner.isAtEnd(s)) {
    let c = Scanner.peek(s);
    if (c === " " || c === "\t") {
      Scanner.advance(s);
    } else {
      keep = false;
    }
  };
  return s.col - startCol | 0;
}

function tokenize(tabSizeOpt, source) {
  let tabSize = tabSizeOpt !== undefined ? tabSizeOpt : 4;
  let s = Scanner.make(source, tabSize, undefined);
  let tokens = [];
  while (!Scanner.isAtEnd(s)) {
    let startPos = Scanner.position(s);
    let ch = Scanner.peek(s);
    let cp = Scanner.peekCodePoint(s);
    if (ch === "\n" || ch === "\r") {
      Scanner.advance(s);
      let endPos = Scanner.position(s);
      tokens.push(Token.make("Newline", "\n", startPos, endPos));
    } else if (ch === " " || ch === "\t") {
      let visW = readWhitespaceRun(s);
      let endPos$1 = Scanner.position(s);
      let text = source.slice(startPos.offset, endPos$1.offset);
      tokens.push(Token.make({
        TAG: "Whitespace",
        _0: visW
      }, text, startPos, endPos$1));
    } else if (ch === "-") {
      let n = readRun(s, "-");
      let endPos$2 = Scanner.position(s);
      let text$1 = source.slice(startPos.offset, endPos$2.offset);
      tokens.push(Token.make({
        TAG: "Dashes",
        _0: n
      }, text$1, startPos, endPos$2));
    } else if (ch === "=") {
      let n$1 = readRun(s, "=");
      let endPos$3 = Scanner.position(s);
      let text$2 = source.slice(startPos.offset, endPos$3.offset);
      tokens.push(Token.make({
        TAG: "Equals",
        _0: n$1
      }, text$2, startPos, endPos$3));
    } else if (ch === "_") {
      let n$2 = readRun(s, "_");
      let endPos$4 = Scanner.position(s);
      let text$3 = source.slice(startPos.offset, endPos$4.offset);
      tokens.push(Token.make({
        TAG: "Underscores",
        _0: n$2
      }, text$3, startPos, endPos$4));
    } else if (ch === "+") {
      Scanner.advance(s);
      let endPos$5 = Scanner.position(s);
      tokens.push(Token.make("Plus", "+", startPos, endPos$5));
    } else if (ch === "|") {
      Scanner.advance(s);
      let endPos$6 = Scanner.position(s);
      tokens.push(Token.make("Pipe", "|", startPos, endPos$6));
    } else if (ch === "[") {
      Scanner.advance(s);
      let endPos$7 = Scanner.position(s);
      tokens.push(Token.make("LBracket", "[", startPos, endPos$7));
    } else if (ch === "]") {
      Scanner.advance(s);
      let endPos$8 = Scanner.position(s);
      tokens.push(Token.make("RBracket", "]", startPos, endPos$8));
    } else if (ch === "(") {
      Scanner.advance(s);
      let endPos$9 = Scanner.position(s);
      tokens.push(Token.make("LParen", "(", startPos, endPos$9));
    } else if (ch === ")") {
      Scanner.advance(s);
      let endPos$10 = Scanner.position(s);
      tokens.push(Token.make("RParen", ")", startPos, endPos$10));
    } else if (ch === "<") {
      Scanner.advance(s);
      let endPos$11 = Scanner.position(s);
      tokens.push(Token.make("LAngle", "<", startPos, endPos$11));
    } else if (ch === ">") {
      Scanner.advance(s);
      let endPos$12 = Scanner.position(s);
      tokens.push(Token.make("RAngle", ">", startPos, endPos$12));
    } else if (ch === ":") {
      Scanner.advance(s);
      let endPos$13 = Scanner.position(s);
      tokens.push(Token.make("Colon", ":", startPos, endPos$13));
    } else if (ch === "#") {
      Scanner.advance(s);
      let endPos$14 = Scanner.position(s);
      tokens.push(Token.make("Hash", "#", startPos, endPos$14));
    } else if (ch === "$") {
      Scanner.advance(s);
      let endPos$15 = Scanner.position(s);
      tokens.push(Token.make("Dollar", "$", startPos, endPos$15));
    } else if (ch === "{") {
      Scanner.advance(s);
      let endPos$16 = Scanner.position(s);
      tokens.push(Token.make("LBrace", "{", startPos, endPos$16));
    } else if (ch === "}") {
      Scanner.advance(s);
      let endPos$17 = Scanner.position(s);
      tokens.push(Token.make("RBrace", "}", startPos, endPos$17));
    } else if (ch === "*") {
      Scanner.advance(s);
      let endPos$18 = Scanner.position(s);
      tokens.push(Token.make("Asterisk", "*", startPos, endPos$18));
    } else if (ch === "\"") {
      Scanner.advance(s);
      let endPos$19 = Scanner.position(s);
      tokens.push(Token.make("Quote", "\"", startPos, endPos$19));
    } else if (ch === "@") {
      Scanner.advance(s);
      let endPos$20 = Scanner.position(s);
      tokens.push(Token.make("At", "@", startPos, endPos$20));
    } else if (ch === ",") {
      Scanner.advance(s);
      let endPos$21 = Scanner.position(s);
      tokens.push(Token.make("Comma", ",", startPos, endPos$21));
    } else if (ch === "?") {
      Scanner.advance(s);
      let endPos$22 = Scanner.position(s);
      tokens.push(Token.make("QuestionMark", "?", startPos, endPos$22));
    } else if (isIdentChar(cp)) {
      let text$4 = readIdentifier(s);
      let endPos$23 = Scanner.position(s);
      tokens.push(Token.make("Identifier", text$4, startPos, endPos$23));
    } else {
      Scanner.advance(s);
      let endPos$24 = Scanner.position(s);
      let text$5 = source.slice(startPos.offset, endPos$24.offset);
      tokens.push(Token.make({
        TAG: "Other",
        _0: text$5
      }, text$5, startPos, endPos$24));
    }
  };
  let endPos$25 = Scanner.position(s);
  tokens.push(Token.make("EOF", "", endPos$25, endPos$25));
  return tokens;
}

export {
  isIdentChar,
  readRun,
  readIdentifier,
  readWhitespaceRun,
  tokenize,
}
/* No side effect */
