// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as UnicodeUtils from "../utils/UnicodeUtils.mjs";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";

function make(source, tabSizeOpt, param) {
  let tabSize = tabSizeOpt !== undefined ? tabSizeOpt : 4;
  return {
    source: source,
    offset: 0,
    row: 0,
    col: 0,
    tabSize: tabSize,
    prevWasZwj: false
  };
}

function isAtEnd(s) {
  return s.offset >= s.source.length;
}

function peek(s) {
  if (isAtEnd(s)) {
    return "";
  } else {
    return s.source.charAt(s.offset);
  }
}

function peekAt(s, n) {
  if ((s.offset + n | 0) >= s.source.length) {
    return "";
  } else {
    return s.source.charAt(s.offset + n | 0);
  }
}

function peekCodePoint(s) {
  if (isAtEnd(s)) {
    return -1;
  } else {
    return Core__Option.getOr(s.source.codePointAt(s.offset), -1);
  }
}

function advance(s) {
  while (true) {
    if (isAtEnd(s)) {
      return "";
    }
    let cp = peekCodePoint(s);
    let cuLen = cp > 65535 ? 2 : 1;
    let ch = s.source.slice(s.offset, s.offset + cuLen | 0);
    if (ch === "\r" && peekAt(s, 1) === "\n") {
      s.offset = s.offset + 1 | 0;
      s.prevWasZwj = false;
      continue;
    }
    if (ch === "\n" || ch === "\r") {
      s.offset = s.offset + 1 | 0;
      s.row = s.row + 1 | 0;
      s.col = 0;
      s.prevWasZwj = false;
      return "\n";
    }
    if (ch !== "\t") {
      if (cp === 8205) {
        s.offset = s.offset + cuLen | 0;
        s.prevWasZwj = true;
        return ch;
      } else if (s.prevWasZwj) {
        s.offset = s.offset + cuLen | 0;
        s.prevWasZwj = false;
        return ch;
      } else if (UnicodeUtils.isCombining(cp)) {
        s.offset = s.offset + cuLen | 0;
        return ch;
      } else if (UnicodeUtils.isWide(cp)) {
        s.offset = s.offset + cuLen | 0;
        s.col = s.col + 2 | 0;
        return ch;
      } else {
        s.offset = s.offset + cuLen | 0;
        s.col = s.col + 1 | 0;
        return ch;
      }
    }
    let next = (Primitive_int.div(s.col, s.tabSize) + 1 | 0) * s.tabSize | 0;
    s.col = next;
    s.offset = s.offset + 1 | 0;
    s.prevWasZwj = false;
    return "\t";
  };
}

function position(s) {
  return {
    row: s.row,
    col: s.col,
    offset: s.offset
  };
}

export {
  make,
  isAtEnd,
  peek,
  peekAt,
  peekCodePoint,
  advance,
  position,
}
/* No side effect */
