// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Token from "../types/Token.mjs";
import * as V2Types from "../types/V2Types.mjs";

function make(tokens) {
  return {
    tokens: tokens,
    cursor: 0
  };
}

function eofToken(ts) {
  let n = ts.tokens.length;
  if (n === 0) {
    return Token.make("EOF", "", V2Types.zeroPos, V2Types.zeroPos);
  } else {
    return ts.tokens[n - 1 | 0];
  }
}

function peek(ts) {
  if (ts.cursor < ts.tokens.length) {
    return ts.tokens[ts.cursor];
  } else {
    return eofToken(ts);
  }
}

function peekAt(ts, n) {
  let i = ts.cursor + n | 0;
  if (i < ts.tokens.length) {
    return ts.tokens[i];
  } else {
    return eofToken(ts);
  }
}

function next(ts) {
  let tok = peek(ts);
  if (!Token.isEof(tok)) {
    ts.cursor = ts.cursor + 1 | 0;
  }
  return tok;
}

function isAtEnd(ts) {
  return Token.isEof(peek(ts));
}

function position(ts) {
  return peek(ts).position;
}

function save(ts) {
  return ts.cursor;
}

function restore(ts, snapshot) {
  ts.cursor = snapshot;
}

function rewindToRow(ts, row) {
  let n = ts.tokens.length;
  let i = 0;
  let found = false;
  while (!found && i < n) {
    let tok = ts.tokens[i];
    if (tok.position.row >= row) {
      ts.cursor = i;
      found = true;
    } else {
      i = i + 1 | 0;
    }
  };
  if (!found) {
    ts.cursor = n;
    return;
  }
}

function skipInlineWhitespace(ts) {
  let start = ts.cursor;
  let keep = true;
  while (keep) {
    let match = peek(ts).kind;
    if (typeof match !== "object" || match.TAG !== "Whitespace") {
      keep = false;
    } else {
      next(ts);
    }
  };
  return ts.cursor - start | 0;
}

function skipToEndOfRow(ts) {
  let keep = true;
  while (keep) {
    let tok = peek(ts);
    let match = tok.kind;
    if (typeof match !== "object") {
      switch (match) {
        case "Newline" :
          next(ts);
          keep = false;
          break;
        case "EOF" :
          keep = false;
          break;
        default:
          next(ts);
      }
    } else {
      next(ts);
    }
  };
}

function findOnCurrentRow(ts, matcher) {
  let start = ts.cursor;
  let row = peek(ts).position.row;
  let found;
  let i = start;
  let n = ts.tokens.length;
  let keep = true;
  while (keep && i < n) {
    let tok = ts.tokens[i];
    if (tok.position.row !== row) {
      keep = false;
    } else {
      let match = tok.kind;
      let exit = 0;
      if (typeof match !== "object") {
        switch (match) {
          case "Newline" :
          case "EOF" :
            keep = false;
            break;
          default:
            exit = 1;
        }
      } else {
        exit = 1;
      }
      if (exit === 1) {
        if (matcher(tok)) {
          found = i;
          keep = false;
        } else {
          i = i + 1 | 0;
        }
      }
    }
  };
  return found;
}

export {
  make,
  eofToken,
  peek,
  peekAt,
  next,
  isAtEnd,
  position,
  save,
  restore,
  rewindToRow,
  skipInlineWhitespace,
  skipToEndOfRow,
  findOnCurrentRow,
}
/* No side effect */
