// Generated by ReScript, PLEASE EDIT WITH CARE

import * as V2Types from "../types/V2Types.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function inferLayout(children, containerBoundsOpt, param) {
  let containerBounds = containerBoundsOpt !== undefined ? Primitive_option.valFromOption(containerBoundsOpt) : undefined;
  let n = children.length;
  if (n === 0) {
    return {
      direction: "Column",
      groups: [],
      distribution: undefined
    };
  }
  let groups = [];
  let i = 0;
  while (i < n) {
    let start = i;
    let startRow = V2Types.getLocation(children[start]).start.row;
    let j = start + 1 | 0;
    let keep = true;
    while (keep && j < n) {
      let row = V2Types.getLocation(children[j]).start.row;
      if (row === startRow) {
        j = j + 1 | 0;
      } else {
        keep = false;
      }
    };
    let end_ = j;
    let dir = (end_ - start | 0) >= 2 ? "Row" : "Column";
    groups.push({
      direction: dir,
      start: start,
      end_: end_,
      startRow: startRow
    });
    i = end_;
  };
  let allRow = {
    contents: true
  };
  let allCol = {
    contents: true
  };
  groups.forEach(g => {
    let match = g.direction;
    switch (match) {
      case "Row" :
        allCol.contents = false;
        return;
      case "Column" :
        allRow.contents = false;
        return;
      case "Mixed" :
        allRow.contents = false;
        allCol.contents = false;
        return;
    }
  });
  let overall = groups.length === 0 ? "Column" : (
      groups.length === 1 ? groups[0].direction : (
          allRow.contents ? "Row" : (
              allCol.contents ? "Column" : "Mixed"
            )
        )
    );
  let match = groups.length;
  let distribution;
  if (match !== 1 || containerBounds === undefined) {
    distribution = undefined;
  } else {
    let g = groups[0];
    if (g.direction === "Row" && (g.end_ - g.start | 0) >= 2) {
      let innerLeft = containerBounds.x + 1 | 0;
      let innerRight = (containerBounds.x + containerBounds.width | 0) - 2 | 0;
      let firstChild = children[g.start];
      let lastChild = children[g.end_ - 1 | 0];
      let firstStartCol = V2Types.getLocation(firstChild).start.col;
      let lastEndCol = V2Types.getLocation(lastChild).end_.col;
      let leftPad = firstStartCol - innerLeft | 0;
      let rightPad = innerRight - (lastEndCol - 1 | 0) | 0;
      let lp = leftPad < 0 ? 0 : leftPad;
      let rp = rightPad < 0 ? 0 : rightPad;
      let w = (innerRight - innerLeft | 0) + 1 | 0;
      distribution = w <= 0 ? undefined : (
          lp <= 1 && rp <= 1 ? "SpaceBetween" : (
              Math.abs(lp - rp | 0) <= 1.0 && lp > 1 ? "Center_" : (
                  lp <= 1 && rp > 1 ? "Start" : (
                      lp > 1 && rp <= 1 ? "End" : "SpaceAround"
                    )
                )
            )
        );
    } else {
      distribution = undefined;
    }
  }
  return {
    direction: overall,
    groups: groups,
    distribution: distribution
  };
}

export {
  inferLayout,
}
/* No side effect */
