// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Slugify from "../utils/Slugify.mjs";
import * as Heuristics from "../utils/Heuristics.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";

function assignGroups(radios, parentSlugOpt, heuristicsOpt, param) {
  let parentSlug = parentSlugOpt !== undefined ? parentSlugOpt : "parent";
  let heuristics = heuristicsOpt !== undefined ? heuristicsOpt : Heuristics.default;
  let n = radios.length;
  if (n === 0) {
    return radios;
  }
  let parent = Core__Array.fromInitializer(n, i => i);
  let find = i => {
    let p = parent[i];
    if (p === i) {
      return i;
    }
    let r = find(p);
    parent[i] = r;
    return r;
  };
  let union = (a, b) => {
    let ra = find(a);
    let rb = find(b);
    if (ra !== rb) {
      parent[ra] = rb;
      return;
    }
  };
  radios.forEach((r, i) => {
    for (let j = i + 1 | 0; j < n; ++j) {
      let s = radios[j];
      let rRow = r.location.start.row;
      let sRow = s.location.start.row;
      if (rRow === sRow) {
        let gap = Math.abs(s.location.start.col - r.location.end_.col | 0);
        if (gap <= heuristics.radioHorizontalGap) {
          union(i, j);
        }
      } else {
        let rowDist = Math.abs(sRow - rRow | 0);
        let colDist = Math.abs(s.location.start.col - r.location.start.col | 0);
        if (rowDist <= (heuristics.radioMaxBlankRows + 1 | 0) && colDist <= heuristics.radioVerticalColumnTolerance) {
          union(i, j);
        }
      }
    }
  });
  let groupIds = {};
  let nextId = {
    contents: 1
  };
  radios.forEach((_r, i) => {
    let root = find(i);
    let key = root.toString();
    let match = groupIds[key];
    if (match !== undefined) {
      return;
    } else {
      groupIds[key] = nextId.contents;
      nextId.contents = nextId.contents + 1 | 0;
      return;
    }
  });
  let totalGroups = nextId.contents - 1 | 0;
  return Core__Array.fromInitializer(n, i => {
    let root = find(i);
    let key = root.toString();
    let gid = Core__Option.getOr(groupIds[key], 1);
    let radio = radios[i];
    let groupName = totalGroups <= 1 ? parentSlug + "-group" : parentSlug + `-group-` + gid.toString();
    return {
      location: radio.location,
      selected: radio.selected,
      label: radio.label,
      group: groupName
    };
  });
}

function assignGroupsRecursive(children, parentSlug, heuristics) {
  let withNested = children.map(node => {
    switch (node.TAG) {
      case "SceneNode" :
        let s = node._0;
        let newKids = assignGroupsRecursive(s.children, s.slug, heuristics);
        return {
          TAG: "SceneNode",
          _0: {
            location: s.location,
            slug: s.slug,
            title: s.title,
            device: s.device,
            transition: s.transition,
            children: newKids,
            layout: s.layout
          }
        };
      case "ComponentNode" :
        let co = node._0;
        let newKids$1 = assignGroupsRecursive(co.children, co.slug, heuristics);
        return {
          TAG: "ComponentNode",
          _0: {
            location: co.location,
            slug: co.slug,
            props: co.props,
            children: newKids$1,
            layout: co.layout
          }
        };
      case "ContainerNode" :
        let c = node._0;
        let id = c.id;
        let innerSlug;
        if (id !== undefined) {
          innerSlug = id;
        } else {
          let n = c.name;
          innerSlug = n !== undefined ? Slugify.slugify(n) : parentSlug + `-container`;
        }
        let newKids$2 = assignGroupsRecursive(c.children, innerSlug, heuristics);
        return {
          TAG: "ContainerNode",
          _0: {
            location: c.location,
            id: c.id,
            name: c.name,
            children: newKids$2,
            layout: c.layout,
            bounds: c.bounds,
            containsErrorRecovery: c.containsErrorRecovery
          }
        };
      default:
        return node;
    }
  });
  let directRadios = [];
  let directRadioIndices = [];
  withNested.forEach((n, i) => {
    if (n.TAG !== "RadioNode") {
      return;
    }
    directRadios.push(n._0);
    directRadioIndices.push(i);
  });
  if (directRadios.length === 0) {
    return withNested;
  }
  let assigned = assignGroups(directRadios, parentSlug, heuristics, undefined);
  let result = withNested.slice();
  directRadioIndices.forEach((idx, k) => {
    let updated = assigned[k];
    result[idx] = {
      TAG: "RadioNode",
      _0: updated
    };
  });
  return result;
}

export {
  assignGroups,
  assignGroupsRecursive,
}
/* No side effect */
