// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as Slugify from "../../utils/Slugify.mjs";
import * as Heuristics from "../../utils/Heuristics.mjs";
import * as EscapeUtils from "../../utils/EscapeUtils.mjs";
import * as UnicodeUtils from "../../utils/UnicodeUtils.mjs";

Vitest.describe("Heuristics module", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("default thresholds are stable", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    t.expect(Heuristics.default.containerColumnTolerance).toBe(1);
    t.expect(Heuristics.default.containerWidthTolerance).toBe(2);
    t.expect(Heuristics.default.radioHorizontalGap).toBe(6);
    t.expect(Heuristics.default.radioVerticalColumnTolerance).toBe(1);
    t.expect(Heuristics.default.radioMaxBlankRows).toBe(0);
    t.expect(Heuristics.default.dividerMinRun).toBe(3);
    t.expect(Heuristics.default.nearMissTokenDistance).toBe(1);
  });
  Vitest.test("rule IDs are stable strings", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    t.expect(Heuristics.Rule.containerWallAlignment).toBe("container.wallAlignment");
    t.expect(Heuristics.Rule.textCenter).toBe("text.center");
    t.expect(Heuristics.Rule.radioGroupingHorizontal).toBe("radioGrouping.horizontal");
    t.expect(Heuristics.Rule.nearMissPatterns).toBe("nearMissPatterns");
  });
});

Vitest.describe("Slugify", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("simple lowercase words", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => t.expect(Slugify.slugify("Hello World")).toBe("hello-world"));
  Vitest.test("strips surrounding punctuation", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => t.expect(Slugify.slugify("Sign In!")).toBe("sign-in"));
  Vitest.test("empty input returns 'empty'", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    t.expect(Slugify.slugify("")).toBe("empty");
    t.expect(Slugify.slugify("  ")).toBe("empty");
  });
});

Vitest.describe("UnicodeUtils", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("graphemeWidth handles narrow/wide/combining", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    t.expect(UnicodeUtils.graphemeWidth("a")).toBe(1);
    t.expect(UnicodeUtils.graphemeWidth("한")).toBe(2);
    t.expect(UnicodeUtils.graphemeWidth("")).toBe(0);
  });
  Vitest.test("visualWidth accounts for tab stops", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    t.expect(UnicodeUtils.visualWidth("\tx", undefined, undefined, undefined)).toBe(5);
    t.expect(UnicodeUtils.visualWidth("ab\tc", undefined, undefined, undefined)).toBe(5);
  });
});

Vitest.describe("EscapeUtils", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("unescapes \\\" \\\\ \\$", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    t.expect(EscapeUtils.unescapeString("a\\\"b")).toBe("a\"b");
    t.expect(EscapeUtils.unescapeString("a\\\\b")).toBe("a\\b");
    t.expect(EscapeUtils.unescapeString("a\\$b")).toBe("a$b");
  });
  Vitest.test("unknown escapes pass through", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => t.expect(EscapeUtils.unescapeString("a\\xb")).toBe("a\\xb"));
});

/*  Not a pure module */
