// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Lexer from "../../lexer/Lexer.mjs";
import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as GridIndex from "../../lexer/GridIndex.mjs";

function getKind(tokens, i) {
  return tokens[i].kind;
}

function getText(tokens, i) {
  return tokens[i].text;
}

Vitest.describe("V2 Lexer", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("tokenizes a simple container line", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let tokens = Lexer.tokenize(undefined, "+--Login--+");
    t.expect(tokens.length).toBe(6);
    t.expect(tokens[0].kind).toBe("Plus");
    t.expect(tokens[1].kind).toEqual({
      TAG: "Dashes",
      _0: 2
    });
    t.expect(tokens[2].kind).toBe("Identifier");
    t.expect(tokens[2].text).toBe("Login");
    t.expect(tokens[3].kind).toEqual({
      TAG: "Dashes",
      _0: 2
    });
    t.expect(tokens[4].kind).toBe("Plus");
    t.expect(tokens[5].kind).toBe("EOF");
  });
  Vitest.test("tracks row/col across newlines", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let tokens = Lexer.tokenize(undefined, "a\nb");
    let aTok = tokens[0];
    let nl = tokens[1];
    let bTok = tokens[2];
    t.expect(aTok.position.row).toBe(0);
    t.expect(aTok.position.col).toBe(0);
    t.expect(nl.kind).toBe("Newline");
    t.expect(bTok.position.row).toBe(1);
    t.expect(bTok.position.col).toBe(0);
  });
  Vitest.test("tokenizes input bracket as separate tokens", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let tokens = Lexer.tokenize(undefined, "[__email__]");
    t.expect(tokens[0].kind).toBe("LBracket");
    t.expect(tokens[1].kind).toEqual({
      TAG: "Underscores",
      _0: 2
    });
    t.expect(tokens[2].kind).toBe("Identifier");
    t.expect(tokens[2].text).toBe("email");
    t.expect(tokens[3].kind).toEqual({
      TAG: "Underscores",
      _0: 2
    });
    t.expect(tokens[4].kind).toBe("RBracket");
  });
  Vitest.test("counts wide characters as 2 visual columns", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let tokens = Lexer.tokenize(undefined, "한x");
    let id = tokens[0];
    t.expect(id.kind).toBe("Identifier");
    t.expect(id.endPosition.col).toBe(3);
  });
  Vitest.test("handles CRLF as a single Newline", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let tokens = Lexer.tokenize(undefined, "a\r\nb");
    t.expect(tokens.length).toBe(4);
    t.expect(tokens[1].kind).toBe("Newline");
    let bTok = tokens[2];
    t.expect(bTok.position.row).toBe(1);
  });
});

Vitest.describe("V2 GridIndex", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.test("charAt returns the expected character", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
  let tokens = Lexer.tokenize(undefined, "+--+\n|  |\n+--+");
  let g = GridIndex.make(tokens);
  t.expect(GridIndex.charAt(g, tokens, 0, 0)).toBe("+");
  t.expect(GridIndex.charAt(g, tokens, 0, 1)).toBe("-");
  t.expect(GridIndex.charAt(g, tokens, 1, 0)).toBe("|");
  t.expect(GridIndex.charAt(g, tokens, 2, 3)).toBe("+");
  t.expect(GridIndex.charAt(g, tokens, 1, 2)).toBe(" ");
}));

export {
  getKind,
  getText,
}
/*  Not a pure module */
