// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Parser from "../../V2Parser.mjs";

let loginV2 = `@scene: login
@title: Login
@device: mobile

+---------------------------+
|                           |
|        'WYREFRAME'        |
|                           |
|  +---------------------+  |
|  | #email              |  |
|  +---------------------+  |
|                           |
|  +---------------------+  |
|  | #password           |  |
|  +---------------------+  |
|                           |
|     [ Login ]             |
|                           |
|  "Forgot password?"       |
|                           |
|  "Create account"         |
+---------------------------+`;

let signupV2 = `@scene: signup
@title: Sign Up
@device: mobile

+---------------------------+
|     [ Back ]              |
|                           |
|     Create Account        |
|                           |
|  +---------------------+  |
|  | #name               |  |
|  +---------------------+  |
|                           |
|  +---------------------+  |
|  | #email2             |  |
|  +---------------------+  |
|                           |
|  +---------------------+  |
|  | #password2          |  |
|  +---------------------+  |
|                           |
|  +---------------------+  |
|  | #confirmPassword    |  |
|  +---------------------+  |
|                           |
|     [ Sign Up ]           |
+---------------------------+`;

let forgotV2 = `@scene: forgot
@title: Forgot Password
@device: mobile

+---------------------------+
|     [ Back ]              |
|                           |
|   Reset Password          |
|                           |
|   Enter your email to     |
|   receive reset link      |
|                           |
|  +---------------------+  |
|  | #resetEmail         |  |
|  +---------------------+  |
|                           |
|     [ Send Link ]         |
+---------------------------+`;

let dashboardSimplified = `@scene: dashboard
@title: Dashboard
@device: mobile

+---------------------------+
|  Dashboard      [ Logout ]|
|                           |
|  Welcome back!            |
|                           |
+---------------------------+`;

Vitest.describe("V2: examples/index.html scenes round-trip cleanly", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("login", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let r = V2Parser.parse(loginV2, undefined, undefined);
    t.expect(r.success).toBe(true);
    let match = r.ast;
    if (match !== undefined && match.TAG === "SceneBlock") {
      return t.expect(match._0.slug).toBe("login");
    } else {
      return t.expect(true).toBe(false);
    }
  });
  Vitest.test("signup", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let r = V2Parser.parse(signupV2, undefined, undefined);
    t.expect(r.success).toBe(true);
    let match = r.ast;
    if (match !== undefined && match.TAG === "SceneBlock") {
      return t.expect(match._0.slug).toBe("signup");
    } else {
      return t.expect(true).toBe(false);
    }
  });
  Vitest.test("forgot", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let r = V2Parser.parse(forgotV2, undefined, undefined);
    t.expect(r.success).toBe(true);
    let match = r.ast;
    if (match !== undefined && match.TAG === "SceneBlock") {
      return t.expect(match._0.slug).toBe("forgot");
    } else {
      return t.expect(true).toBe(false);
    }
  });
  Vitest.test("dashboard", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let r = V2Parser.parse(dashboardSimplified, undefined, undefined);
    t.expect(r.success).toBe(true);
  });
  Vitest.test("all examples produce a non-empty layout", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let r1 = V2Parser.parse(loginV2, undefined, undefined);
    let match = r1.ast;
    if (match !== undefined && match.TAG === "SceneBlock") {
      return t.expect(match._0.children.length > 0).toBe(true);
    }
  });
  Vitest.test("layout groups address children by index range — no duplication", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let r = V2Parser.parse(loginV2, undefined, undefined);
    let match = r.ast;
    if (match === undefined) {
      return;
    }
    if (match.TAG !== "SceneBlock") {
      return;
    }
    let s = match._0;
    let nChildren = s.children.length;
    s.layout.groups.forEach(g => {
      t.expect(g.end_ <= nChildren).toBe(true);
      t.expect(g.start >= 0 && g.start < g.end_).toBe(true);
    });
  });
});

export {
  loginV2,
  signupV2,
  forgotV2,
  dashboardSimplified,
}
/*  Not a pure module */
