// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";

let loginScene = `@scene: login
@title: Login
@device: mobile

+---------------------------+
|                           |
|        'WYREFRAME'        |
|                           |
|  +---------------------+  |
|  | #email              |  |
|  +---------------------+  |
|                           |
|  +---------------------+  |
|  | #password           |  |
|  +---------------------+  |
|                           |
|     [ Login ]             |
|                           |
|  "Forgot password?"       |
|                           |
|  "Create account"         |
+---------------------------+`;

let signupScene = `@scene: signup
@title: Sign Up
@device: mobile

+---------------------------+
|     [ Back ]              |
|                           |
|     Create Account        |
|                           |
|  +---------------------+  |
|  | #name               |  |
|  +---------------------+  |
|                           |
|     [ Sign Up ]           |
+---------------------------+`;

let dashboardScene = `@scene: dashboard
@title: Dashboard
@device: mobile

+---------------------------+
|  Dashboard      [ Logout ]|
|                           |
|  Welcome back!            |
|                           |
+---------------------------+`;

function countContainers(block) {
  let count = {
    contents: 0
  };
  let walk = node => {
    if (node.TAG === "ContainerNode") {
      count.contents = count.contents + 1 | 0;
    }
    let children = V2Types.getChildren(node);
    if (children !== undefined) {
      children.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return count.contents;
}

function countButtons(block) {
  let count = {
    contents: 0
  };
  let walk = node => {
    if (node.TAG === "ButtonNode") {
      count.contents = count.contents + 1 | 0;
    }
    let children = V2Types.getChildren(node);
    if (children !== undefined) {
      children.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return count.contents;
}

function countStrings(block) {
  let count = {
    contents: 0
  };
  let walk = node => {
    if (node.TAG === "StringNode") {
      count.contents = count.contents + 1 | 0;
    }
    let children = V2Types.getChildren(node);
    if (children !== undefined) {
      children.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return count.contents;
}

Vitest.describe("V2 Parser - examples/index.html scenes", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("parses the login scene without errors", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(loginScene, undefined, undefined);
    t.expect(result.success).toBe(true);
    t.expect(result.errors.length).toBe(0);
  });
  Vitest.test("login scene has the correct slug, title, device", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(loginScene, undefined, undefined);
    let match = result.ast;
    if (match === undefined) {
      return t.expect(true).toBe(false);
    }
    if (match.TAG !== "SceneBlock") {
      return t.expect(true).toBe(false);
    }
    let s = match._0;
    t.expect(s.slug).toBe("login");
    t.expect(s.title).toEqual("Login");
    t.expect(s.device).toEqual("Mobile");
  });
  Vitest.test("login scene contains the outer container", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(loginScene, undefined, undefined);
    let block = result.ast;
    if (block !== undefined) {
      return t.expect(countContainers(block)).toBe(3);
    } else {
      return t.expect(true).toBe(false);
    }
  });
  Vitest.test("login scene includes the Login button", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(loginScene, undefined, undefined);
    let block = result.ast;
    if (block !== undefined) {
      return t.expect(countButtons(block) >= 1).toBe(true);
    } else {
      return t.expect(true).toBe(false);
    }
  });
  Vitest.test("login scene includes two string literals (forgot/create)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(loginScene, undefined, undefined);
    let block = result.ast;
    if (block !== undefined) {
      return t.expect(countStrings(block)).toBe(2);
    } else {
      return t.expect(true).toBe(false);
    }
  });
  Vitest.test("parses the signup scene", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(signupScene, undefined, undefined);
    t.expect(result.success).toBe(true);
    let match = result.ast;
    if (match === undefined) {
      return t.expect(true).toBe(false);
    }
    if (match.TAG !== "SceneBlock") {
      return t.expect(true).toBe(false);
    }
    let s = match._0;
    t.expect(s.slug).toBe("signup");
    t.expect(countButtons({
      TAG: "SceneBlock",
      _0: s
    }) >= 2).toBe(true);
  });
  Vitest.test("parses the dashboard scene", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(dashboardScene, undefined, undefined);
    t.expect(result.success).toBe(true);
    let match = result.ast;
    if (match !== undefined && match.TAG === "SceneBlock") {
      return t.expect(match._0.slug).toBe("dashboard");
    } else {
      return t.expect(true).toBe(false);
    }
  });
});

Vitest.describe("V2 Parser - error cases", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("missing block declaration", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse("Just some text", undefined, undefined);
    t.expect(result.success).toBe(false);
    t.expect(result.errors.length >= 1).toBe(true);
  });
  Vitest.test("unclosed container produces an error", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: bad

+--Top--+
|       |
|       |`, undefined, undefined);
    t.expect(result.errors.length >= 1).toBe(true);
  });
  Vitest.test("priority disambiguation: [v: foo] parses as Select", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: t

+------------+
| [v: pick]  |
+------------+`, undefined, undefined);
    let foundSelect = {
      contents: false
    };
    let block = result.ast;
    if (block !== undefined) {
      let walk = n => {
        if (n.TAG === "SelectNode") {
          foundSelect.contents = true;
        }
        let c = V2Types.getChildren(n);
        if (c !== undefined) {
          c.forEach(walk);
          return;
        }
      };
      let tmp;
      tmp = block.TAG === "SceneBlock" ? ({
          TAG: "SceneNode",
          _0: block._0
        }) : ({
          TAG: "ComponentNode",
          _0: block._0
        });
      walk(tmp);
    }
    t.expect(foundSelect.contents).toBe(true);
  });
  Vitest.test("priority disambiguation: [__email__] parses as Input", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: t

+-------------+
| [__email__] |
+-------------+`, undefined, undefined);
    let foundInput = {
      contents: false
    };
    let block = result.ast;
    if (block !== undefined) {
      let walk = n => {
        if (n.TAG === "InputNode") {
          foundInput.contents = true;
        }
        let c = V2Types.getChildren(n);
        if (c !== undefined) {
          c.forEach(walk);
          return;
        }
      };
      let tmp;
      tmp = block.TAG === "SceneBlock" ? ({
          TAG: "SceneNode",
          _0: block._0
        }) : ({
          TAG: "ComponentNode",
          _0: block._0
        });
      walk(tmp);
    }
    t.expect(foundInput.contents).toBe(true);
  });
  Vitest.test("priority disambiguation: [x] parses as Checkbox", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: t

[x] Accept terms`, undefined, undefined);
    let foundCheckbox = {
      contents: false
    };
    let block = result.ast;
    if (block !== undefined) {
      let walk = n => {
        if (n.TAG === "CheckboxNode") {
          if (n._0.checked) {
            foundCheckbox.contents = true;
          }
        }
        let c = V2Types.getChildren(n);
        if (c !== undefined) {
          c.forEach(walk);
          return;
        }
      };
      let tmp;
      tmp = block.TAG === "SceneBlock" ? ({
          TAG: "SceneNode",
          _0: block._0
        }) : ({
          TAG: "ComponentNode",
          _0: block._0
        });
      walk(tmp);
    }
    t.expect(foundCheckbox.contents).toBe(true);
  });
});

export {
  loginScene,
  signupScene,
  dashboardScene,
  countContainers,
  countButtons,
  countStrings,
}
/*  Not a pure module */
