// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Parser from "../../V2Parser.mjs";

Vitest.describe("Regression P2: strict parse mode (Codex round 15)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("strict=true halts at first block with an error (subsequent blocks NOT parsed)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let opts_tabSize = V2Parser.defaultOptions.tabSize;
    let opts_maxDepth = V2Parser.defaultOptions.maxDepth;
    let opts_heuristics = V2Parser.defaultOptions.heuristics;
    let opts_emojiRegistry = V2Parser.defaultOptions.emojiRegistry;
    let opts = {
      strict: true,
      tabSize: opts_tabSize,
      maxDepth: opts_maxDepth,
      heuristics: opts_heuristics,
      emojiRegistry: opts_emojiRegistry
    };
    let result = V2Parser.parse(`@scene: first

[__unclosed

@scene: second

OK here`, opts, undefined);
    t.expect(result.blocks.length).toBe(1);
    let match = result.blocks[0];
    if (match !== undefined && match.TAG === "SceneBlock") {
      t.expect(match._0.slug).toBe("first");
    } else {
      t.expect("missing-first").toBe("found");
    }
    t.expect(result.success).toBe(false);
  });
  Vitest.test("strict=true promotes recoverable errors to non-recoverable", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let opts_tabSize = V2Parser.defaultOptions.tabSize;
    let opts_maxDepth = V2Parser.defaultOptions.maxDepth;
    let opts_heuristics = V2Parser.defaultOptions.heuristics;
    let opts_emojiRegistry = V2Parser.defaultOptions.emojiRegistry;
    let opts = {
      strict: true,
      tabSize: opts_tabSize,
      maxDepth: opts_maxDepth,
      heuristics: opts_heuristics,
      emojiRegistry: opts_emojiRegistry
    };
    let result = V2Parser.parse(`@scene: s

[__unclosed`, opts, undefined);
    let unclosed = result.errors.find(e => {
      let match = e.code;
      return match === "UnclosedInput";
    });
    if (unclosed !== undefined) {
      return t.expect(unclosed.recoverable).toBe(false);
    } else {
      return t.expect("no-unclosed-error").toBe("found");
    }
  });
  Vitest.test("strict=false (default) still parses subsequent blocks after an error", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: first

[__unclosed

@scene: second

OK here`, undefined, undefined);
    t.expect(result.blocks.length).toBe(2);
  });
  Vitest.test("strict=false keeps the recoverable=true flag", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

[__unclosed`, undefined, undefined);
    let unclosed = result.errors.find(e => {
      let match = e.code;
      return match === "UnclosedInput";
    });
    if (unclosed !== undefined) {
      return t.expect(unclosed.recoverable).toBe(true);
    } else {
      return t.expect("no-unclosed-error").toBe("found");
    }
  });
  Vitest.test("strict=true on clean input still produces success=true", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let opts_tabSize = V2Parser.defaultOptions.tabSize;
    let opts_maxDepth = V2Parser.defaultOptions.maxDepth;
    let opts_heuristics = V2Parser.defaultOptions.heuristics;
    let opts_emojiRegistry = V2Parser.defaultOptions.emojiRegistry;
    let opts = {
      strict: true,
      tabSize: opts_tabSize,
      maxDepth: opts_maxDepth,
      heuristics: opts_heuristics,
      emojiRegistry: opts_emojiRegistry
    };
    let result = V2Parser.parse(`@scene: s

Hello`, opts, undefined);
    t.expect(result.success).toBe(true);
    t.expect(result.errors.length).toBe(0);
  });
});

/*  Not a pure module */
