// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";

function firstStringNode(block) {
  let found = {
    contents: undefined
  };
  let walk = n => {
    let match = found.contents;
    if (match === undefined && n.TAG === "StringNode") {
      found.contents = n._0;
    }
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return found.contents;
}

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression: StringParser preserves content (Codex P2)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("plain string content is non-empty", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: t

"hello world"`, undefined, undefined);
    let block = result.ast;
    if (block === undefined) {
      return t.expect("no-ast").toBe("ast");
    }
    let s = firstStringNode(block);
    if (s !== undefined) {
      return t.expect(s.content).toBe("hello world");
    } else {
      return t.expect("missing-string-node").toBe("present");
    }
  });
  Vitest.test("string with emoji resolves into content", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: t

"hi :check: there"`, undefined, undefined);
    let block = result.ast;
    if (block === undefined) {
      return t.expect("no-ast").toBe("ast");
    }
    let s = firstStringNode(block);
    if (s === undefined) {
      return t.expect("missing-string-node").toBe("present");
    }
    t.expect(s.content.includes("✔")).toBe(true);
    t.expect(s.content.includes("hi")).toBe(true);
    t.expect(s.content.includes("there")).toBe(true);
    let hasEmojiRef = s.interpolations.some(p => {
      switch (p.TAG) {
        case "Literal" :
        case "PropRef" :
          return false;
        case "EmojiRef" :
          return true;
      }
    });
    t.expect(hasEmojiRef).toBe(true);
  });
  Vitest.test("multiline string content keeps the newline", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: t

"line1
line2"`, undefined, undefined);
    let block = result.ast;
    if (block === undefined) {
      return t.expect("no-ast").toBe("ast");
    }
    let s = firstStringNode(block);
    if (s !== undefined) {
      t.expect(s.multiline).toBe(true);
      t.expect(s.content.includes("line1")).toBe(true);
      t.expect(s.content.includes("line2")).toBe(true);
      return t.expect(s.content.includes("\n")).toBe(true);
    } else {
      return t.expect("missing").toBe("present");
    }
  });
  Vitest.test("component-side ${prop} inside string keeps marker in content + PropRef in interpolations", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@component: greeting
@props: name

"Hello \${name}!"`, undefined, undefined);
    let block = result.ast;
    if (block === undefined) {
      return t.expect("no-ast").toBe("ast");
    }
    let s = firstStringNode(block);
    if (s === undefined) {
      return t.expect("missing").toBe("present");
    }
    t.expect(s.content.includes("Hello")).toBe(true);
    t.expect(s.content.includes("\${name}")).toBe(true);
    let hasPropRef = s.interpolations.some(p => {
      switch (p.TAG) {
        case "PropRef" :
          return true;
        case "Literal" :
        case "EmojiRef" :
          return false;
      }
    });
    t.expect(hasPropRef).toBe(true);
  });
});

Vitest.describe("Regression: scene-level \${prop} becomes literal text (Codex P2)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("standalone scene-level \${prop} returns TextNode, not PropPlaceholderNode", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: t

\${name}`, undefined, undefined);
    let foundPlaceholder = {
      contents: false
    };
    let foundTextLiteral = {
      contents: false
    };
    let block = result.ast;
    if (block !== undefined) {
      collectNodes(block).forEach(n => {
        switch (n.TAG) {
          case "TextNode" :
            if (n._0.content.includes("\${name}")) {
              foundTextLiteral.contents = true;
              return;
            } else {
              return;
            }
          case "PropPlaceholderNode" :
            foundPlaceholder.contents = true;
            return;
          default:
            return;
        }
      });
    }
    t.expect(foundPlaceholder.contents).toBe(false);
    t.expect(foundTextLiteral.contents).toBe(true);
  });
  Vitest.test("scene-level \${prop} emits PropOutsideComponent warning", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: t

\${name}`, undefined, undefined);
    let hasWarning = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return match === "PropOutsideComponent";
      } else {
        return false;
      }
    });
    t.expect(hasWarning).toBe(true);
  });
  Vitest.test("component-side \${prop} still returns PropPlaceholderNode", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@component: c
@props: name

\${name}`, undefined, undefined);
    let foundPlaceholder = {
      contents: false
    };
    let block = result.ast;
    if (block !== undefined) {
      collectNodes(block).forEach(n => {
        if (n.TAG === "PropPlaceholderNode") {
          foundPlaceholder.contents = true;
          return;
        }
      });
    }
    t.expect(foundPlaceholder.contents).toBe(true);
  });
  Vitest.test("scene-level \${prop} inside string keeps literal marker, no PropRef", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: t

"Hello \${name}"`, undefined, undefined);
    let block = result.ast;
    if (block !== undefined) {
      let s = firstStringNode(block);
      if (s !== undefined) {
        t.expect(s.content.includes("\${name}")).toBe(true);
        let hasPropRef = s.interpolations.some(p => {
          switch (p.TAG) {
            case "PropRef" :
              return true;
            case "Literal" :
            case "EmojiRef" :
              return false;
          }
        });
        t.expect(hasPropRef).toBe(false);
      } else {
        t.expect("missing").toBe("present");
      }
    } else {
      t.expect("no-ast").toBe("ast");
    }
    let hasWarning = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return match === "PropOutsideComponent";
      } else {
        return false;
      }
    });
    t.expect(hasWarning).toBe(true);
  });
});

export {
  firstStringNode,
  collectNodes,
}
/*  Not a pure module */
