// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as Slugify from "../../utils/Slugify.mjs";
import * as EmojiRegistry from "../../registry/EmojiRegistry.mjs";

Vitest.describe("Regression P2: EmojiRegistry.reset wipes custom registrations (Codex round 17)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("register then reset → custom no longer resolves; built-ins still resolve", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    EmojiRegistry.register("custom", "🎉");
    t.expect(EmojiRegistry.lookup("custom")).toEqual("🎉");
    EmojiRegistry.reset();
    t.expect(EmojiRegistry.lookup("custom")).toEqual(undefined);
    t.expect(EmojiRegistry.lookup("check")).toEqual("✔");
  });
  Vitest.test("multiple register/reset cycles stay clean", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    EmojiRegistry.register("a", "A");
    EmojiRegistry.register("b", "B");
    EmojiRegistry.reset();
    t.expect(EmojiRegistry.lookup("a")).toEqual(undefined);
    t.expect(EmojiRegistry.lookup("b")).toEqual(undefined);
    EmojiRegistry.register("a", "A");
    EmojiRegistry.reset();
    t.expect(EmojiRegistry.lookup("a")).toEqual(undefined);
  });
});

Vitest.describe("Regression P2: Slugify replaces broader punctuation (Codex round 17)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("`/` is treated as a separator", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => t.expect(Slugify.slugify("A/B")).toBe("a-b"));
  Vitest.test("`#` is treated as a separator", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => t.expect(Slugify.slugify("Save #1")).toBe("save-1"));
  Vitest.test("`@` and `.` are treated as separators", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => t.expect(Slugify.slugify("foo@bar.com")).toBe("foo-bar-com"));
  Vitest.test("multiple punctuation chars collapse to one `-`", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => t.expect(Slugify.slugify("a // b")).toBe("a-b"));
  Vitest.test("CJK is preserved (not treated as separator)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => t.expect(Slugify.slugify("사용자 이름")).toBe("사용자-이름"));
  Vitest.test("alphanumeric-only text unchanged (after lowercase)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => t.expect(Slugify.slugify("Hello123")).toBe("hello123"));
});

/*  Not a pure module */
