// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P2: CRLF-accurate child offsets (Codex round 32)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("button inside CRLF-source container has start.offset pointing at real `[`", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let src = "@scene: s\r\n\r\n+----------+\r\n| [ Go ]   |\r\n+----------+";
    let result = V2Parser.parse(src, undefined, undefined);
    let block = result.ast;
    let buttons = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "ButtonNode") {
        return n._0;
      }
    });
    let b = buttons[0];
    if (b === undefined) {
      return t.expect("no-button").toBe("found");
    }
    let off = b.location.start.offset;
    let ch = src.charAt(off);
    t.expect(ch).toBe("[");
  });
  Vitest.test("LF-source child offset still correct (regression baseline)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let src = "@scene: s\n\n+----------+\n| [ Go ]   |\n+----------+";
    let result = V2Parser.parse(src, undefined, undefined);
    let block = result.ast;
    let buttons = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "ButtonNode") {
        return n._0;
      }
    });
    let b = buttons[0];
    if (b === undefined) {
      return t.expect("no-button").toBe("found");
    }
    let off = b.location.start.offset;
    let ch = src.charAt(off);
    t.expect(ch).toBe("[");
  });
});

Vitest.describe("Regression P2: containsErrorRecovery flag for multi-id (Codex round 32)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("two Format-2 IDs marks container.containsErrorRecovery=true", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+--------+
| #foo   |
| #bar   |
+--------+`, undefined, undefined);
    let block = result.ast;
    let containers = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "ContainerNode") {
        return n._0;
      }
    });
    let c = containers[0];
    if (c !== undefined) {
      return t.expect(c.containsErrorRecovery).toBe(true);
    } else {
      return t.expect("no-container").toBe("found");
    }
  });
  Vitest.test("invalid Format-2 ID (`| #foo bar |`) also flags containsErrorRecovery", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+-----------+
| #foo bar  |
+-----------+`, undefined, undefined);
    let block = result.ast;
    let containers = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "ContainerNode") {
        return n._0;
      }
    });
    let c = containers[0];
    if (c !== undefined) {
      return t.expect(c.containsErrorRecovery).toBe(true);
    } else {
      return t.expect("no-container").toBe("found");
    }
  });
  Vitest.test("normal container has containsErrorRecovery=false", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+----+
| Hi |
+----+`, undefined, undefined);
    let block = result.ast;
    let containers = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "ContainerNode") {
        return n._0;
      }
    });
    let c = containers[0];
    if (c !== undefined) {
      return t.expect(c.containsErrorRecovery).toBe(false);
    } else {
      return t.expect("no-container").toBe("found");
    }
  });
});

export {
  collectNodes,
}
/*  Not a pure module */
