// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P2: consecutive recovered blocks keep their bound (Codex round 28)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.test("two nested @scene declarations in same container don't trigger UnclosedContainer", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
  let result = V2Parser.parse(`@scene: outer

+--------------+
| @scene: a    |
| body of a    |
| @scene: b    |
| body of b    |
+--------------+`, undefined, undefined);
  let hasUnclosed = result.errors.some(e => {
    let match = e.code;
    return match === "UnclosedContainer";
  });
  t.expect(hasUnclosed).toBe(false);
  t.expect(result.blocks.length >= 3).toBe(true);
}));

Vitest.describe("Regression P2: tolerated wall pipe stripped from recovered text (Codex round 28)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.test("recovered block with right-wall drifted -1 col: text is clean", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
  let result = V2Parser.parse(`@scene: outer

+------------+
| @scene: x   |
| Hi         |
+------------+`, undefined, undefined);
  let match = result.blocks[1];
  if (match === undefined) {
    return t.expect("no-inner").toBe("found");
  }
  if (match.TAG !== "SceneBlock") {
    return t.expect("no-inner").toBe("found");
  }
  let nodes = collectNodes({
    TAG: "SceneBlock",
    _0: match._0
  });
  let dirty = nodes.some(n => {
    if (n.TAG === "TextNode") {
      return n._0.content.includes("|");
    } else {
      return false;
    }
  });
  t.expect(dirty).toBe(false);
}));

export {
  collectNodes,
}
/*  Not a pure module */
