// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P2: recovered nested block strips container walls (Codex round 23)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("recovered nested block with body row `| Hi |` does NOT emit `|` TextNodes", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: outer

+----------+
| @scene: x |
| Hi       |
+----------+`, undefined, undefined);
    let match = result.blocks[1];
    if (match === undefined) {
      return t.expect("no-inner").toBe("found");
    }
    if (match.TAG !== "SceneBlock") {
      return t.expect("no-inner").toBe("found");
    }
    let nodes = collectNodes({
      TAG: "SceneBlock",
      _0: match._0
    });
    let badText = nodes.some(n => {
      if (n.TAG === "TextNode") {
        return n._0.content.trim() === "|";
      } else {
        return false;
      }
    });
    t.expect(badText).toBe(false);
  });
  Vitest.test("recovered nested block correctly captures inner body text", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: outer

+--------------+
| @scene: y    |
| Some content |
+--------------+`, undefined, undefined);
    let match = result.blocks[1];
    if (match === undefined) {
      return t.expect("no-inner").toBe("found");
    }
    if (match.TAG !== "SceneBlock") {
      return t.expect("no-inner").toBe("found");
    }
    let nodes = collectNodes({
      TAG: "SceneBlock",
      _0: match._0
    });
    let hasInner = nodes.some(n => {
      if (n.TAG === "TextNode") {
        return n._0.content.includes("Some content");
      } else {
        return false;
      }
    });
    t.expect(hasInner).toBe(true);
  });
});

export {
  collectNodes,
}
/*  Not a pure module */
