// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P2: underscores-only input (Codex round 10)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("`[____________]` parses as Input with empty placeholder", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

[____________]`, undefined, undefined);
    let foundInput = {
      contents: undefined
    };
    let block = result.ast;
    if (block !== undefined) {
      collectNodes(block).forEach(n => {
        if (n.TAG === "InputNode") {
          foundInput.contents = n._0;
          return;
        }
      });
    }
    let i = foundInput.contents;
    if (i !== undefined) {
      t.expect(i.placeholder).toBe("");
    } else {
      t.expect("no-input").toBe("found");
    }
    let hasUnclosed = result.errors.some(e => {
      let match = e.code;
      return match === "UnclosedInput";
    });
    t.expect(hasUnclosed).toBe(false);
  });
  Vitest.test("`[____]` (just 4 underscores) parses as Input with empty placeholder", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

[____]`, undefined, undefined);
    let foundInput = {
      contents: undefined
    };
    let block = result.ast;
    if (block !== undefined) {
      collectNodes(block).forEach(n => {
        if (n.TAG === "InputNode") {
          foundInput.contents = n._0;
          return;
        }
      });
    }
    let i = foundInput.contents;
    if (i !== undefined) {
      return t.expect(i.placeholder).toBe("");
    } else {
      return t.expect("no-input").toBe("found");
    }
  });
});

Vitest.describe("Regression P2: child offsets after tab/wide chars (Codex round 10)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.test("tab-prefixed inner element offset points at the actual `[`", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
  let src = "@scene: s\n\n\t+------+\n\t| [OK] |\n\t+------+";
  let result = V2Parser.parse(src, undefined, undefined);
  let block = result.ast;
  let buttons = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
    if (n.TAG === "ButtonNode") {
      return n._0;
    }
  });
  let b = buttons[0];
  if (b === undefined) {
    return t.expect("no-button").toBe("found");
  }
  let off = b.location.start.offset;
  let ch = src.charAt(off);
  t.expect(ch).toBe("[");
}));

export {
  collectNodes,
}
/*  Not a pure module */
