// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Lexer from "../../lexer/Lexer.mjs";
import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Parser from "../../V2Parser.mjs";

Vitest.describe("Regression P2: standalone CR line endings (Codex round 29)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("CR-only line endings parse a Container correctly (no UnclosedContainer)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse("@scene: s\r\r+----+\r|    |\r+----+", undefined, undefined);
    let hasUnclosed = result.errors.some(e => {
      let match = e.code;
      return match === "UnclosedContainer";
    });
    t.expect(hasUnclosed).toBe(false);
    t.expect(result.success).toBe(true);
  });
  Vitest.test("CR rows increment row coordinate", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let tokens = Lexer.tokenize(undefined, "a\rb");
    let bTok = tokens[2];
    t.expect(bTok.position.row).toBe(1);
  });
});

Vitest.describe("Regression P2: every nested block declaration reported (Codex round 29)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("two nested @scene declarations in one container → TWO NestedBlockDeclaration errors", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: outer

+---------------+
| @scene: alpha |
| body          |
| @scene: beta  |
| body          |
+---------------+`, undefined, undefined);
    let nestedCount = result.errors.filter(e => {
      let match = e.code;
      return match === "NestedBlockDeclaration";
    }).length;
    t.expect(nestedCount).toBe(2);
  });
  Vitest.test("three nested @scene declarations produce three errors", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: outer

+----------------+
| @scene: a      |
| @scene: b      |
| @scene: c      |
+----------------+`, undefined, undefined);
    let nestedCount = result.errors.filter(e => {
      let match = e.code;
      return match === "NestedBlockDeclaration";
    }).length;
    t.expect(nestedCount).toBe(3);
  });
});

/*  Not a pure module */
