// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Parser from "../../V2Parser.mjs";

Vitest.describe("Regression P2: tab-separated format-2 ID line is invalid (Codex round 48)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("`#foo\\tbar` inside container emits InvalidIdFormat (not silently assigned id=foo\\tbar)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse("@scene: s\n\n+----------+\n|#foo\tbar |\n+----------+", undefined, undefined);
    let hasInvalid = result.errors.some(e => {
      let match = e.code;
      return match === "InvalidIdFormat";
    });
    t.expect(hasInvalid).toBe(true);
  });
  Vitest.test("`#foo bar` (space-separated) still emits InvalidIdFormat", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+----------+
|#foo bar  |
+----------+`, undefined, undefined);
    let hasInvalid = result.errors.some(e => {
      let match = e.code;
      return match === "InvalidIdFormat";
    });
    t.expect(hasInvalid).toBe(true);
  });
  Vitest.test("`#foo` alone (no extra content) is still a valid format-2 ID", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+----------+
|  #foo    |
+----------+`, undefined, undefined);
    let hasInvalid = result.errors.some(e => {
      let match = e.code;
      return match === "InvalidIdFormat";
    });
    t.expect(hasInvalid).toBe(false);
  });
  Vitest.test("tab-only id `#a\\tb\\tc` still rejected", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse("@scene: s\n\n+----------+\n|#a\tb\tc   |\n+----------+", undefined, undefined);
    let hasInvalid = result.errors.some(e => {
      let match = e.code;
      return match === "InvalidIdFormat";
    });
    t.expect(hasInvalid).toBe(true);
  });
});

/*  Not a pure module */
