// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Parser from "../../V2Parser.mjs";

Vitest.describe("Regression P2: body row missing one wall is reported (Codex round 27)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("`+-----+ / | abc / +-----+` (right wall missing on row 2) emits MisalignedContainerWall", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+-----+
| abc
+-----+`, undefined, undefined);
    let hasWallWarn = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return match === "MisalignedContainerWall";
      } else {
        return false;
      }
    });
    t.expect(hasWallWarn).toBe(true);
  });
  Vitest.test("`+--+ / abc | / +--+` (left wall missing) also emits MisalignedContainerWall", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+----+
abc  |
+----+`, undefined, undefined);
    let hasWallWarn = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return match === "MisalignedContainerWall";
      } else {
        return false;
      }
    });
    t.expect(hasWallWarn).toBe(true);
  });
  Vitest.test("perfectly walled body row emits NO wall warning", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+----+
| ab |
+----+`, undefined, undefined);
    let hasWallWarn = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return match === "MisalignedContainerWall";
      } else {
        return false;
      }
    });
    t.expect(hasWallWarn).toBe(false);
  });
  Vitest.test("blank row with only one wall does NOT emit warning", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+----+
|    |

+----+`, undefined, undefined);
    let hasWallWarn = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return match === "MisalignedContainerWall";
      } else {
        return false;
      }
    });
    t.expect(hasWallWarn).toBe(false);
  });
});

/*  Not a pure module */
