// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as EmojiRegistry from "../../registry/EmojiRegistry.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

function firstStringNode(block) {
  let found = {
    contents: undefined
  };
  collectNodes(block).forEach(n => {
    let match = found.contents;
    if (match !== undefined || n.TAG !== "StringNode") {
      return;
    } else {
      found.contents = n._0;
      return;
    }
  });
  return found.contents;
}

Vitest.describe("Regression P1: nested container preserves contents (Codex round 3)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("box inside box keeps the inner text child", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+----------+
|+--------+|
||   Hi   ||
|+--------+|
+----------+`, undefined, undefined);
    let block = result.ast;
    let containers = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "ContainerNode") {
        return n._0;
      }
    });
    t.expect(containers.length >= 2).toBe(true);
    let foundInner = {
      contents: false
    };
    containers.forEach(c => {
      c.children.forEach(child => {
        if (child.TAG === "TextNode" && child._0.content.includes("Hi")) {
          foundInner.contents = true;
          return;
        }
      });
    });
    t.expect(foundInner.contents).toBe(true);
  });
  Vitest.test("3-level nested container preserves the deepest text", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+------------+
|+----------+|
||+--------+||
|||  deep  |||
||+--------+||
|+----------+|
+------------+`, undefined, undefined);
    let block = result.ast;
    let containers = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "ContainerNode") {
        return n._0;
      }
    });
    t.expect(containers.length >= 3).toBe(true);
    let foundDeep = {
      contents: false
    };
    let block$1 = result.ast;
    (
      block$1 !== undefined ? collectNodes(block$1) : []
    ).forEach(n => {
      if (n.TAG === "TextNode" && n._0.content.includes("deep")) {
        foundDeep.contents = true;
        return;
      }
    });
    t.expect(foundDeep.contents).toBe(true);
  });
});

Vitest.describe("Regression P2: horizontal radios become distinct nodes (Codex round 3)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("(*) A   ( ) B on one row produces TWO radios", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

(*) Visa   ( ) MasterCard`, undefined, undefined);
    let block = result.ast;
    let radios = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "RadioNode") {
        return n._0;
      }
    });
    t.expect(radios.length).toBe(2);
    let visa = radios[0];
    let mc = radios[1];
    if (visa !== undefined && mc !== undefined) {
      t.expect(visa.selected).toBe(true);
      t.expect(visa.label.trim()).toBe("Visa");
      t.expect(mc.selected).toBe(false);
      return t.expect(mc.label.trim()).toBe("MasterCard");
    } else {
      return t.expect("missing-radios").toBe("found");
    }
  });
  Vitest.test("three same-row radios produce three nodes", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

( ) S  ( ) M  (*) L`, undefined, undefined);
    let block = result.ast;
    let radios = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "RadioNode") {
        return n._0;
      }
    });
    t.expect(radios.length).toBe(3);
  });
});

Vitest.describe("Regression P2: emoji not double-rendered (Codex round 3)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("interpolations do not contain a Literal that also includes the resolved emoji glyph", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

"hi :check:"`, undefined, undefined);
    let block = result.ast;
    if (block === undefined) {
      return t.expect("no-ast").toBe("ast");
    }
    let s = firstStringNode(block);
    if (s === undefined) {
      return t.expect("missing-string").toBe("present");
    }
    let emoji = Core__Option.getOr(EmojiRegistry.lookup("check"), "?");
    let literalsContainEmoji = s.interpolations.some(p => {
      switch (p.TAG) {
        case "Literal" :
          return p._0.includes(emoji);
        case "PropRef" :
        case "EmojiRef" :
          return false;
      }
    });
    t.expect(literalsContainEmoji).toBe(false);
    let emojiRefs = s.interpolations.filter(p => {
      switch (p.TAG) {
        case "Literal" :
        case "PropRef" :
          return false;
        case "EmojiRef" :
          return true;
      }
    });
    t.expect(emojiRefs.length).toBe(1);
    t.expect(s.content.includes(emoji)).toBe(true);
  });
  Vitest.test("reconstructing from interpolations equals content", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

"hi :check: bye"`, undefined, undefined);
    let block = result.ast;
    if (block === undefined) {
      return t.expect("no-ast").toBe("ast");
    }
    let s = firstStringNode(block);
    if (s === undefined) {
      return t.expect("missing").toBe("present");
    }
    let rendered = Core__Array.reduce(s.interpolations, "", (acc, p) => {
      switch (p.TAG) {
        case "Literal" :
          return acc + p._0;
        case "PropRef" :
          return acc;
        case "EmojiRef" :
          return acc + p._0.emoji;
      }
    });
    t.expect(rendered).toBe(s.content);
  });
  Vitest.test("unknown emoji appears once in content and once in interpolations", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

"x :nope: y"`, undefined, undefined);
    let block = result.ast;
    if (block === undefined) {
      return t.expect("no-ast").toBe("ast");
    }
    let s = firstStringNode(block);
    if (s === undefined) {
      return t.expect("missing").toBe("present");
    }
    let firstIdx = s.content.indexOf(":nope:");
    let lastIdx = s.content.lastIndexOf(":nope:");
    t.expect(firstIdx >= 0).toBe(true);
    t.expect(firstIdx).toBe(lastIdx);
    let hasWarning = result.warnings.some(w => {
      let name = w.code;
      if (typeof name !== "object" || name.TAG !== "UnknownEmoji") {
        return false;
      } else {
        return name._0 === "nope";
      }
    });
    t.expect(hasWarning).toBe(true);
  });
});

export {
  collectNodes,
  firstStringNode,
}
/*  Not a pure module */
