// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P2: unclosed container recovery skips body rows (Codex round 42)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("unclosed `+--+ / | a | / | b |` produces ONE ErrorNode and NO leaked Text", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+----+
| a  |
| b  |`, undefined, undefined);
    let hasUnclosed = result.errors.some(e => {
      let match = e.code;
      return match === "UnclosedContainer";
    });
    t.expect(hasUnclosed).toBe(true);
    let block = result.ast;
    let nodes = block !== undefined ? collectNodes(block) : [];
    let leaked = nodes.some(n => {
      if (n.TAG !== "TextNode") {
        return false;
      }
      let tt = n._0;
      let c = tt.content.trim();
      if (c === "a" || c === "b" || tt.content.includes("| a")) {
        return true;
      } else {
        return tt.content.includes("| b");
      }
    });
    t.expect(leaked).toBe(false);
    let errNodes = nodes.filter(n => n.TAG === "ErrorNode");
    t.expect(errNodes.length >= 1).toBe(true);
  });
  Vitest.test("recovered ErrorNode.recoveredContent includes the body rows", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+----+
| body row 1 |
| body row 2 |`, undefined, undefined);
    let block = result.ast;
    let errNode = (
      block !== undefined ? collectNodes(block) : []
    ).find(n => n.TAG === "ErrorNode");
    if (errNode === undefined) {
      return t.expect("no-error-node").toBe("found");
    }
    if (errNode.TAG !== "ErrorNode") {
      return t.expect("no-error-node").toBe("found");
    }
    let content = errNode._0.recoveredContent;
    if (content !== undefined) {
      t.expect(content.includes("body row 1")).toBe(true);
      return t.expect(content.includes("body row 2")).toBe(true);
    } else {
      return t.expect("no-recovered-content").toBe("present");
    }
  });
  Vitest.test("recovery stops at next `+`-leading row (sync point)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+----+
| body |
+-------+
| body2 |`, undefined, undefined);
    let unclosedCount = result.errors.filter(e => {
      let match = e.code;
      return match === "UnclosedContainer";
    }).length;
    t.expect(unclosedCount >= 1).toBe(true);
  });
  Vitest.test("recovery stops at @scene declaration", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: outer

+----+
| body |
@scene: next`, undefined, undefined);
    t.expect(result.blocks.length >= 2).toBe(true);
    let match = result.blocks[1];
    if (match !== undefined && match.TAG === "SceneBlock") {
      return t.expect(match._0.slug).toBe("next");
    } else {
      return t.expect("no-second-scene").toBe("found");
    }
  });
});

export {
  collectNodes,
}
/*  Not a pure module */
