// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P2: unclosed string returns ErrorNode (Codex round 25)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("unclosed `\"abc` produces ErrorNode (not StringNode)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

"abc`, undefined, undefined);
    let block = result.ast;
    let nodes = block !== undefined ? collectNodes(block) : [];
    let strings = nodes.filter(n => n.TAG === "StringNode");
    let errs = nodes.filter(n => n.TAG === "ErrorNode");
    t.expect(strings.length).toBe(0);
    t.expect(errs.length >= 1).toBe(true);
  });
  Vitest.test("closed `\"abc\"` still produces a StringNode", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

"abc"`, undefined, undefined);
    let block = result.ast;
    let nodes = block !== undefined ? collectNodes(block) : [];
    let strings = nodes.filter(n => n.TAG === "StringNode");
    t.expect(strings.length).toBe(1);
  });
});

Vitest.describe("Regression P2: unclosed container returns ErrorNode (Codex round 25)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.test("`+--+` with no matching bottom produces an ErrorNode", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
  let result = V2Parser.parse(`@scene: s

+--+
|  |`, undefined, undefined);
  let block = result.ast;
  let nodes = block !== undefined ? collectNodes(block) : [];
  let containers = nodes.filter(n => n.TAG === "ContainerNode");
  let errs = nodes.filter(n => n.TAG === "ErrorNode");
  t.expect(containers.length).toBe(0);
  t.expect(errs.length >= 1).toBe(true);
  let hasUnclosed = result.errors.some(e => {
    let match = e.code;
    return match === "UnclosedContainer";
  });
  t.expect(hasUnclosed).toBe(true);
}));

Vitest.describe("Regression P2: per-parse emoji registry (Codex round 25)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("custom registry from parseOptions overrides defaults", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let custom = {};
    custom["rocket"] = "🚀";
    let opts_strict = V2Parser.defaultOptions.strict;
    let opts_tabSize = V2Parser.defaultOptions.tabSize;
    let opts_maxDepth = V2Parser.defaultOptions.maxDepth;
    let opts_heuristics = V2Parser.defaultOptions.heuristics;
    let opts_emojiRegistry = custom;
    let opts = {
      strict: opts_strict,
      tabSize: opts_tabSize,
      maxDepth: opts_maxDepth,
      heuristics: opts_heuristics,
      emojiRegistry: opts_emojiRegistry
    };
    let result = V2Parser.parse(`@scene: s\n\n:rocket:`, opts, undefined);
    let block = result.ast;
    let nodes = block !== undefined ? collectNodes(block) : [];
    let emojiNode = nodes.find(n => n.TAG === "EmojiNode");
    if (emojiNode !== undefined && emojiNode.TAG === "EmojiNode") {
      return t.expect(emojiNode._0.emoji).toBe("🚀");
    } else {
      return t.expect("no-emoji").toBe("found");
    }
  });
  Vitest.test("custom registry does NOT mutate the global default registry", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let custom = {};
    custom["ephemeral"] = "TEMP";
    let opts_strict = V2Parser.defaultOptions.strict;
    let opts_tabSize = V2Parser.defaultOptions.tabSize;
    let opts_maxDepth = V2Parser.defaultOptions.maxDepth;
    let opts_heuristics = V2Parser.defaultOptions.heuristics;
    let opts_emojiRegistry = custom;
    let opts = {
      strict: opts_strict,
      tabSize: opts_tabSize,
      maxDepth: opts_maxDepth,
      heuristics: opts_heuristics,
      emojiRegistry: opts_emojiRegistry
    };
    V2Parser.parse(`@scene: s\n\n:ephemeral:`, opts, undefined);
    let result = V2Parser.parse(`@scene: s\n\n:ephemeral:`, undefined, undefined);
    let hasUnknown = result.warnings.some(w => {
      let name = w.code;
      if (typeof name !== "object" || name.TAG !== "UnknownEmoji") {
        return false;
      } else {
        return name._0 === "ephemeral";
      }
    });
    t.expect(hasUnknown).toBe(true);
  });
  Vitest.test("custom registry falls back to defaults for missing shortcodes", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let custom = {};
    custom["rocket"] = "🚀";
    let opts_strict = V2Parser.defaultOptions.strict;
    let opts_tabSize = V2Parser.defaultOptions.tabSize;
    let opts_maxDepth = V2Parser.defaultOptions.maxDepth;
    let opts_heuristics = V2Parser.defaultOptions.heuristics;
    let opts_emojiRegistry = custom;
    let opts = {
      strict: opts_strict,
      tabSize: opts_tabSize,
      maxDepth: opts_maxDepth,
      heuristics: opts_heuristics,
      emojiRegistry: opts_emojiRegistry
    };
    let result = V2Parser.parse(`@scene: s\n\n:check:`, opts, undefined);
    let block = result.ast;
    let nodes = block !== undefined ? collectNodes(block) : [];
    let emojiNode = nodes.find(n => n.TAG === "EmojiNode");
    if (emojiNode !== undefined && emojiNode.TAG === "EmojiNode") {
      return t.expect(emojiNode._0.emoji).toBe("✔");
    } else {
      return t.expect("no-emoji").toBe("found");
    }
  });
});

export {
  collectNodes,
}
/*  Not a pure module */
