// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as Heuristics from "../../utils/Heuristics.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P2: one-sided corner shift (Codex round 16)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.test("bottom border with left corner exact, right shifted +1 still parses", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
  let result = V2Parser.parse(`@scene: s

+----+
|    |
+-----+`, undefined, undefined);
  let block = result.ast;
  let containers = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
    if (n.TAG === "ContainerNode") {
      return n._0;
    }
  });
  t.expect(containers.length).toBe(1);
  let hasCornerWarn = result.warnings.some(w => {
    let match = w.code;
    if (typeof match !== "object") {
      return match === "MisalignedContainerCorner";
    } else {
      return false;
    }
  });
  t.expect(hasCornerWarn).toBe(true);
}));

Vitest.describe("Regression P2: containerWidthTolerance + InconsistentContainerWidth (Codex round 16)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("bottom border one col WIDER than top emits InconsistentContainerWidth", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+----+
|    |
+-----+`, undefined, undefined);
    let hasWidthWarn = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return match === "InconsistentContainerWidth";
      } else {
        return false;
      }
    });
    t.expect(hasWidthWarn).toBe(true);
    let hasRuleId = result.warnings.some(w => {
      let match = w.code;
      let match$1 = w.ruleId;
      if (typeof match !== "object" && match === "InconsistentContainerWidth" && match$1 !== undefined) {
        return match$1 === Heuristics.Rule.containerWidthConsistency;
      } else {
        return false;
      }
    });
    t.expect(hasRuleId).toBe(true);
  });
  Vitest.test("bottom border one col NARROWER than top emits InconsistentContainerWidth", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+-----+
|     |
+----+`, undefined, undefined);
    let hasWidthWarn = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return match === "InconsistentContainerWidth";
      } else {
        return false;
      }
    });
    t.expect(hasWidthWarn).toBe(true);
  });
  Vitest.test("equal widths emit NO InconsistentContainerWidth warning", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+----+
|    |
+----+`, undefined, undefined);
    let hasWidthWarn = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return match === "InconsistentContainerWidth";
      } else {
        return false;
      }
    });
    t.expect(hasWidthWarn).toBe(false);
  });
});

export {
  collectNodes,
}
/*  Not a pure module */
