// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P2: header-attr parsing stops at next block (Codex round 8)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("@scene immediately after another @scene does NOT become an attribute", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: first
@scene: second`, undefined, undefined);
    let match = result.ast;
    if (match === undefined) {
      return t.expect("no-scene").toBe("scene");
    }
    if (match.TAG !== "SceneBlock") {
      return t.expect("no-scene").toBe("scene");
    }
    let s = match._0;
    t.expect(s.slug).toBe("first");
    t.expect(s.children.length).toBe(0);
    t.expect(s.title).toEqual(undefined);
  });
  Vitest.test("@component immediately after @scene also terminates header-attrs", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: a
@component: b`, undefined, undefined);
    let match = result.ast;
    if (match === undefined) {
      return t.expect("no-scene").toBe("scene");
    }
    if (match.TAG !== "SceneBlock") {
      return t.expect("no-scene").toBe("scene");
    }
    let s = match._0;
    t.expect(s.slug).toBe("a");
    t.expect(s.children.length).toBe(0);
  });
});

Vitest.describe("Regression P2: top border with trailing junk is rejected (Codex round 8)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("+---+ trailing does NOT become a Container", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+---+ trailing
|   |
+---+`, undefined, undefined);
    let block = result.ast;
    let containers = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "ContainerNode") {
        return n._0;
      }
    });
    t.expect(containers.length).toBe(0);
  });
  Vitest.test("clean `+---+` (no trailing) still parses", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+---+
|   |
+---+`, undefined, undefined);
    let block = result.ast;
    let containers = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "ContainerNode") {
        return n._0;
      }
    });
    t.expect(containers.length).toBe(1);
  });
  Vitest.test("top border with trailing whitespace only is still accepted", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse("@scene: s\n\n+---+   \n|   |\n+---+", undefined, undefined);
    let block = result.ast;
    let containers = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "ContainerNode") {
        return n._0;
      }
    });
    t.expect(containers.length).toBe(1);
  });
});

Vitest.describe("Regression P2: duplicate prop names (Codex round 8)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("@props: name, name=Bob emits DuplicatePropName + last wins", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@component: greeting
@props: name, name=Bob

\${name}`, undefined, undefined);
    let hasDup = result.warnings.some(w => {
      let n = w.code;
      if (typeof n !== "object" || n.TAG !== "DuplicatePropName") {
        return false;
      } else {
        return n._0 === "name";
      }
    });
    t.expect(hasDup).toBe(true);
    let match = result.ast;
    if (match === undefined) {
      return t.expect("no-component").toBe("component");
    }
    if (match.TAG === "SceneBlock") {
      return t.expect("no-component").toBe("component");
    }
    let c = match._0;
    t.expect(c.props.length).toBe(1);
    let p = c.props[0];
    if (p !== undefined) {
      t.expect(p.name).toBe("name");
      return t.expect(p.defaultValue).toEqual("Bob");
    }
  });
  Vitest.test("no warning for unique props", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@component: c
@props: a, b, c

\${a}\${b}\${c}`, undefined, undefined);
    let hasDup = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return false;
      } else {
        return match.TAG === "DuplicatePropName";
      }
    });
    t.expect(hasDup).toBe(false);
  });
});

export {
  collectNodes,
}
/*  Not a pure module */
