// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as Heuristics from "../../utils/Heuristics.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

function isDivider(n) {
  return n.TAG === "DividerNode";
}

Vitest.describe("Regression P2: dividerMinRun respected for plain dividers (Codex round 11)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("bare `-` is NOT a Divider", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

-`, undefined, undefined);
    let block = result.ast;
    let dividers = (
      block !== undefined ? collectNodes(block) : []
    ).filter(isDivider);
    t.expect(dividers.length).toBe(0);
  });
  Vitest.test("`--` (2 chars) is NOT a Divider", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

--`, undefined, undefined);
    let block = result.ast;
    let dividers = (
      block !== undefined ? collectNodes(block) : []
    ).filter(isDivider);
    t.expect(dividers.length).toBe(0);
  });
  Vitest.test("`---` (3 chars, meeting dividerMinRun) IS a Divider", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

---`, undefined, undefined);
    let block = result.ast;
    let dividers = (
      block !== undefined ? collectNodes(block) : []
    ).filter(isDivider);
    t.expect(dividers.length).toBe(1);
  });
  Vitest.test("`==` is NOT a bold Divider", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

==`, undefined, undefined);
    let block = result.ast;
    let dividers = (
      block !== undefined ? collectNodes(block) : []
    ).filter(isDivider);
    t.expect(dividers.length).toBe(0);
  });
  Vitest.test("`-#id-` (short form WITH content) is still a Divider", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

-#section-`, undefined, undefined);
    let block = result.ast;
    let dividers = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "DividerNode") {
        return n._0;
      }
    });
    t.expect(dividers.length).toBe(1);
    let d = dividers[0];
    if (d !== undefined) {
      return t.expect(d.id).toEqual("section");
    }
  });
  Vitest.test("custom dividerMinRun=1 admits bare `-` as divider", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let opts_strict = V2Parser.defaultOptions.strict;
    let opts_tabSize = V2Parser.defaultOptions.tabSize;
    let opts_maxDepth = V2Parser.defaultOptions.maxDepth;
    let opts_heuristics = {
      containerColumnTolerance: Heuristics.emptyPartial.containerColumnTolerance,
      containerWidthTolerance: Heuristics.emptyPartial.containerWidthTolerance,
      radioHorizontalGap: Heuristics.emptyPartial.radioHorizontalGap,
      radioVerticalColumnTolerance: Heuristics.emptyPartial.radioVerticalColumnTolerance,
      radioMaxBlankRows: Heuristics.emptyPartial.radioMaxBlankRows,
      centerSymmetryThreshold: Heuristics.emptyPartial.centerSymmetryThreshold,
      rightAlignThreshold: Heuristics.emptyPartial.rightAlignThreshold,
      dividerMinRun: 1,
      nearMissTokenDistance: Heuristics.emptyPartial.nearMissTokenDistance
    };
    let opts_emojiRegistry = V2Parser.defaultOptions.emojiRegistry;
    let opts = {
      strict: opts_strict,
      tabSize: opts_tabSize,
      maxDepth: opts_maxDepth,
      heuristics: opts_heuristics,
      emojiRegistry: opts_emojiRegistry
    };
    let result = V2Parser.parse(`@scene: s

-`, opts, undefined);
    let block = result.ast;
    let dividers = (
      block !== undefined ? collectNodes(block) : []
    ).filter(isDivider);
    t.expect(dividers.length).toBe(1);
  });
});

export {
  collectNodes,
  isDivider,
}
/*  Not a pure module */
