// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P2: @props default with `=` preserved (Codex round 34)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.test("`@props: url=https://a=b` keeps full URL as default", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
  let result = V2Parser.parse(`@component: c
@props: url=https://a=b

\${url}`, undefined, undefined);
  let match = result.ast;
  if (match === undefined) {
    return t.expect("no-component").toBe("found");
  }
  if (match.TAG === "SceneBlock") {
    return t.expect("no-component").toBe("found");
  }
  let p = match._0.props[0];
  if (p !== undefined) {
    t.expect(p.name).toBe("url");
    return t.expect(p.defaultValue).toEqual("https://a=b");
  } else {
    return t.expect("no-prop").toBe("found");
  }
}));

Vitest.describe("Regression P2: standalone ${prop:default} with `:` preserved (Codex round 34)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.test("${url:https://example.com} parses name=`url`, default=`https://example.com`", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
  let result = V2Parser.parse(`@component: c
@props: url

\${url:https://example.com}`, undefined, undefined);
  let block = result.ast;
  let prop = (
    block !== undefined ? collectNodes(block) : []
  ).find(n => n.TAG === "PropPlaceholderNode");
  if (prop === undefined) {
    return t.expect("no-prop").toBe("found");
  }
  if (prop.TAG !== "PropPlaceholderNode") {
    return t.expect("no-prop").toBe("found");
  }
  let p = prop._0;
  t.expect(p.name).toBe("url");
  t.expect(p.defaultValue).toEqual("https://example.com");
}));

Vitest.describe("Regression P2: string-interpolation ${prop:default} with `:` (Codex round 34)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.test("\"Open ${url:https://example.com}\" → PropRef with full URL default", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
  let result = V2Parser.parse(`@component: c
@props: url

"Open \${url:https://example.com}"`, undefined, undefined);
  let block = result.ast;
  let strNode = (
    block !== undefined ? collectNodes(block) : []
  ).find(n => n.TAG === "StringNode");
  if (strNode === undefined) {
    return t.expect("no-string").toBe("found");
  }
  if (strNode.TAG !== "StringNode") {
    return t.expect("no-string").toBe("found");
  }
  let propRef = strNode._0.interpolations.find(i => {
    switch (i.TAG) {
      case "PropRef" :
        return true;
      case "Literal" :
      case "EmojiRef" :
        return false;
    }
  });
  if (propRef !== undefined) {
    switch (propRef.TAG) {
      case "PropRef" :
        let p = propRef._0;
        t.expect(p.name).toBe("url");
        return t.expect(p.defaultValue).toEqual("https://example.com");
      case "Literal" :
      case "EmojiRef" :
        break;
    }
  }
  t.expect("no-propref").toBe("found");
}));

export {
  collectNodes,
}
/*  Not a pure module */
