// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as Heuristics from "../../utils/Heuristics.mjs";
import * as UnicodeUtils from "../../utils/UnicodeUtils.mjs";

Vitest.describe("Regression P2: partial heuristics override merges with defaults (Codex round 13)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("Heuristics.applyPartial fills in missing fields from base", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let p_containerColumnTolerance = Heuristics.emptyPartial.containerColumnTolerance;
    let p_containerWidthTolerance = Heuristics.emptyPartial.containerWidthTolerance;
    let p_radioHorizontalGap = 99;
    let p_radioVerticalColumnTolerance = Heuristics.emptyPartial.radioVerticalColumnTolerance;
    let p_radioMaxBlankRows = Heuristics.emptyPartial.radioMaxBlankRows;
    let p_centerSymmetryThreshold = Heuristics.emptyPartial.centerSymmetryThreshold;
    let p_rightAlignThreshold = Heuristics.emptyPartial.rightAlignThreshold;
    let p_dividerMinRun = Heuristics.emptyPartial.dividerMinRun;
    let p_nearMissTokenDistance = Heuristics.emptyPartial.nearMissTokenDistance;
    let p = {
      containerColumnTolerance: p_containerColumnTolerance,
      containerWidthTolerance: p_containerWidthTolerance,
      radioHorizontalGap: p_radioHorizontalGap,
      radioVerticalColumnTolerance: p_radioVerticalColumnTolerance,
      radioMaxBlankRows: p_radioMaxBlankRows,
      centerSymmetryThreshold: p_centerSymmetryThreshold,
      rightAlignThreshold: p_rightAlignThreshold,
      dividerMinRun: p_dividerMinRun,
      nearMissTokenDistance: p_nearMissTokenDistance
    };
    let merged = Heuristics.applyPartial(p, Heuristics.default);
    t.expect(merged.radioHorizontalGap).toBe(99);
    t.expect(merged.containerColumnTolerance).toBe(Heuristics.default.containerColumnTolerance);
    t.expect(merged.dividerMinRun).toBe(Heuristics.default.dividerMinRun);
    t.expect(merged.centerSymmetryThreshold).toBe(Heuristics.default.centerSymmetryThreshold);
  });
  Vitest.test("emptyPartial through applyPartial gives full default", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let merged = Heuristics.applyPartial(Heuristics.emptyPartial, Heuristics.default);
    t.expect(merged.containerColumnTolerance).toBe(1);
    t.expect(merged.dividerMinRun).toBe(3);
    t.expect(merged.radioHorizontalGap).toBe(6);
  });
  Vitest.test("V2Parser honors a single-field heuristic override", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let opts_strict = V2Parser.defaultOptions.strict;
    let opts_tabSize = V2Parser.defaultOptions.tabSize;
    let opts_maxDepth = V2Parser.defaultOptions.maxDepth;
    let opts_heuristics = {
      containerColumnTolerance: Heuristics.emptyPartial.containerColumnTolerance,
      containerWidthTolerance: Heuristics.emptyPartial.containerWidthTolerance,
      radioHorizontalGap: Heuristics.emptyPartial.radioHorizontalGap,
      radioVerticalColumnTolerance: Heuristics.emptyPartial.radioVerticalColumnTolerance,
      radioMaxBlankRows: Heuristics.emptyPartial.radioMaxBlankRows,
      centerSymmetryThreshold: Heuristics.emptyPartial.centerSymmetryThreshold,
      rightAlignThreshold: Heuristics.emptyPartial.rightAlignThreshold,
      dividerMinRun: 1,
      nearMissTokenDistance: Heuristics.emptyPartial.nearMissTokenDistance
    };
    let opts_emojiRegistry = V2Parser.defaultOptions.emojiRegistry;
    let opts = {
      strict: opts_strict,
      tabSize: opts_tabSize,
      maxDepth: opts_maxDepth,
      heuristics: opts_heuristics,
      emojiRegistry: opts_emojiRegistry
    };
    let result = V2Parser.parse("@scene: s\n\n-", opts, undefined);
    let match = result.ast;
    let hasDivider = match !== undefined && match.TAG === "SceneBlock" ? match._0.children.some(n => n.TAG === "DividerNode") : false;
    t.expect(hasDivider).toBe(true);
  });
});

Vitest.describe("Regression P2: ZWJ emoji is one wide grapheme (Codex round 13)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("`👨‍👩‍👧` has visual width 2", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let w = UnicodeUtils.visualWidth("👨‍👩‍👧", undefined, undefined, undefined);
    t.expect(w).toBe(2);
  });
  Vitest.test("two ZWJ emoji + ascii has expected width", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let w = UnicodeUtils.visualWidth("👨‍👩‍👧X", undefined, undefined, undefined);
    t.expect(w).toBe(3);
  });
  Vitest.test("non-ZWJ wide emoji is also 2", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let w = UnicodeUtils.visualWidth("\u{1F600}", undefined, undefined, undefined);
    t.expect(w).toBe(2);
  });
  Vitest.test("plain ASCII width unchanged by ZWJ fix", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let w = UnicodeUtils.visualWidth("hello", undefined, undefined, undefined);
    t.expect(w).toBe(5);
  });
  Vitest.test("foldGraphemes treats ZWJ cluster as one grapheme of width 2", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let count = UnicodeUtils.foldGraphemes("👨‍👩‍👧", (acc, param, param$1, param$2) => acc + 1 | 0, 0);
    t.expect(count).toBe(1);
  });
});

/*  Not a pure module */
