// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Parser from "../../V2Parser.mjs";

Vitest.describe("Regression P2: defensive options merge from JS (Codex round 22)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("partial options object `{strict: true}` does NOT throw", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let partial = { strict: true };
    let result = V2Parser.parse("@scene: s\n\nHello", partial, undefined);
    t.expect(result.success).toBe(true);
  });
  Vitest.test("totally undefined options (no `~options` passed) still parses", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse("@scene: s\n\nHi", undefined, undefined);
    t.expect(result.success).toBe(true);
  });
  Vitest.test("partial options preserves the explicit `strict` value", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let partial = { strict: true };
    let result = V2Parser.parse("@scene: s\n\n[__abc", partial, undefined);
    let unclosed = result.errors.find(e => {
      let match = e.code;
      return match === "UnclosedInput";
    });
    if (unclosed !== undefined) {
      return t.expect(unclosed.recoverable).toBe(false);
    } else {
      return t.expect("no-error").toBe("found");
    }
  });
});

Vitest.describe("Regression P2: recovered nested block doesn't consume outer's closing border (Codex round 22)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("no spurious UnclosedContainer when recovering nested block", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: outer

+---------------+
| @scene: inner |
+---------------+`, undefined, undefined);
    let hasUnclosedContainer = result.errors.some(e => {
      let match = e.code;
      return match === "UnclosedContainer";
    });
    t.expect(hasUnclosedContainer).toBe(false);
    t.expect(result.blocks.length).toBe(2);
  });
  Vitest.test("recovered nested block has empty body when nothing follows it inside the container", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: outer

+---------------+
| @scene: inner |
+---------------+`, undefined, undefined);
    let match = result.blocks[1];
    if (match === undefined) {
      return t.expect("missing-inner").toBe("found");
    }
    if (match.TAG !== "SceneBlock") {
      return t.expect("missing-inner").toBe("found");
    }
    let s = match._0;
    t.expect(s.slug).toBe("inner");
    t.expect(s.children.length).toBe(0);
  });
});

/*  Not a pure module */
