// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

function firstContainerTextContent(block) {
  let nodes = collectNodes(block);
  let inContainer = {
    contents: false
  };
  let found = {
    contents: undefined
  };
  nodes.forEach(n => {
    let match = found.contents;
    let match$1 = inContainer.contents;
    if (match !== undefined) {
      return;
    }
    switch (n.TAG) {
      case "ContainerNode" :
        inContainer.contents = true;
        return;
      case "TextNode" :
        if (match$1) {
          found.contents = n._0.content;
          return;
        } else {
          return;
        }
      default:
        return;
    }
  });
  return found.contents;
}

Vitest.describe("Regression P2: literal trailing pipe preserved in container text (Codex round 46)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("`| a||` keeps `a|` (literal pipe before well-aligned wall)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+---+
|a| |
+---+`, undefined, undefined);
    let block = result.ast;
    if (block === undefined) {
      return t.expect("no-ast").toBe("ast");
    }
    let content = firstContainerTextContent(block);
    if (content !== undefined) {
      return t.expect(content.includes("a|")).toBe(true);
    } else {
      return t.expect("no-text").toBe("found");
    }
  });
  Vitest.test("`| a |` (no literal pipe) still parses as plain `a`", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+---+
| a |
+---+`, undefined, undefined);
    let block = result.ast;
    if (block === undefined) {
      return t.expect("no-ast").toBe("ast");
    }
    let content = firstContainerTextContent(block);
    if (content === undefined) {
      return t.expect("no-text").toBe("found");
    }
    let trimmed = content.trim();
    t.expect(trimmed).toBe("a");
  });
  Vitest.test("literal pipe in middle of content preserved", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+-------+
|a|b|c  |
+-------+`, undefined, undefined);
    let block = result.ast;
    if (block === undefined) {
      return t.expect("no-ast").toBe("ast");
    }
    let content = firstContainerTextContent(block);
    if (content !== undefined) {
      return t.expect(content.includes("a|b|c")).toBe(true);
    } else {
      return t.expect("no-text").toBe("found");
    }
  });
});

export {
  collectNodes,
  firstContainerTextContent,
}
/*  Not a pure module */
