// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P1: TextParser stops before inline elements (Codex round 12)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("`Dashboard      [ Logout ]` becomes Text + Button (not one giant Text)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

Dashboard      [ Logout ]`, undefined, undefined);
    let block = result.ast;
    let nodes = block !== undefined ? collectNodes(block) : [];
    let texts = Core__Array.filterMap(nodes, n => {
      if (n.TAG === "TextNode") {
        return n._0;
      }
    });
    let buttons = Core__Array.filterMap(nodes, n => {
      if (n.TAG === "ButtonNode") {
        return n._0;
      }
    });
    t.expect(buttons.length).toBe(1);
    let foundDashText = texts.some(tt => {
      if (tt.content.includes("Dashboard")) {
        return !tt.content.includes("[");
      } else {
        return false;
      }
    });
    t.expect(foundDashText).toBe(true);
    let b = buttons[0];
    if (b !== undefined) {
      return t.expect(b.text).toBe("Logout");
    }
  });
  Vitest.test("inline string after text: `Title \"sub\"` becomes Text + String", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

Title "sub"`, undefined, undefined);
    let block = result.ast;
    let nodes = block !== undefined ? collectNodes(block) : [];
    let strings = nodes.filter(n => n.TAG === "StringNode");
    t.expect(strings.length >= 1).toBe(true);
  });
  Vitest.test("inline link after text: `See <docs>` becomes Text + Link", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

See <docs>`, undefined, undefined);
    let block = result.ast;
    let nodes = block !== undefined ? collectNodes(block) : [];
    let links = nodes.filter(n => n.TAG === "LinkNode");
    t.expect(links.length >= 1).toBe(true);
  });
  Vitest.test("inline radio after text: `Size: ( ) S (*) M` becomes Text + two Radios", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

Size: ( ) S (*) M`, undefined, undefined);
    let block = result.ast;
    let nodes = block !== undefined ? collectNodes(block) : [];
    let radios = nodes.filter(n => n.TAG === "RadioNode");
    t.expect(radios.length).toBe(2);
  });
});

Vitest.describe("Regression P2: V2Parser parses multiple top-level blocks (Codex round 12)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("two @scene blocks both appear in parseResult.blocks", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: first

Hello

@scene: second

World`, undefined, undefined);
    t.expect(result.blocks.length).toBe(2);
    let match = result.blocks[0];
    let match$1 = result.blocks[1];
    if (match !== undefined && match.TAG === "SceneBlock" && match$1 !== undefined && match$1.TAG === "SceneBlock") {
      t.expect(match._0.slug).toBe("first");
      return t.expect(match$1._0.slug).toBe("second");
    }
    t.expect("missing-blocks").toBe("found");
  });
  Vitest.test("legacy `ast` accessor still returns the FIRST block", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: first

@scene: second`, undefined, undefined);
    let match = result.ast;
    if (match !== undefined && match.TAG === "SceneBlock") {
      return t.expect(match._0.slug).toBe("first");
    } else {
      return t.expect("missing-ast").toBe("found");
    }
  });
  Vitest.test("mixed @scene + @component blocks both parse", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: page

Hi

@component: card
@props: title

\${title}`, undefined, undefined);
    t.expect(result.blocks.length).toBe(2);
    let match = result.blocks[0];
    let match$1 = result.blocks[1];
    if (match !== undefined && match.TAG === "SceneBlock" && match$1 !== undefined && match$1.TAG !== "SceneBlock") {
      let c = match$1._0;
      t.expect(match._0.slug).toBe("page");
      t.expect(c.slug).toBe("card");
      return t.expect(c.props.length).toBe(1);
    }
    t.expect("wrong-block-kinds").toBe("right");
  });
  Vitest.test("source with no blocks still produces MissingBlockDeclaration", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse("just text", undefined, undefined);
    t.expect(result.success).toBe(false);
    t.expect(result.blocks.length).toBe(0);
  });
});

export {
  collectNodes,
}
/*  Not a pure module */
