// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as EmojiRegistry from "../../registry/EmojiRegistry.mjs";

Vitest.describe("Regression P2: null emojiRegistry from JS does NOT crash (Codex round 26)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("`{emojiRegistry: null}` falls back to default registry", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let partial = { emojiRegistry: null };
    let result = V2Parser.parse("@scene: s\n\n:check:", partial, undefined);
    t.expect(result.success).toBe(true);
    let match = result.ast;
    if (match === undefined) {
      return t.expect("no-scene").toBe("scene");
    }
    if (match.TAG !== "SceneBlock") {
      return t.expect("no-scene").toBe("scene");
    }
    let foundCheck = match._0.children.some(n => {
      if (n.TAG === "EmojiNode") {
        return n._0.emoji === "✔";
      } else {
        return false;
      }
    });
    t.expect(foundCheck).toBe(true);
  });
  Vitest.test("`{emojiRegistry: undefined}` is equivalent to omitting the field", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let partial = { emojiRegistry: undefined };
    let result = V2Parser.parse("@scene: s\n\n:check:", partial, undefined);
    t.expect(result.success).toBe(true);
  });
  Vitest.test("EmojiRegistry.lookupWithOverride(null, name) doesn't throw", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let nullOverride = null;
    let r = EmojiRegistry.lookupWithOverride(nullOverride, "check");
    t.expect(r).toEqual("✔");
  });
});

/*  Not a pure module */
