// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as Heuristics from "../../utils/Heuristics.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P2: near-miss LooksLike warnings (Codex round 18)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("`[Save` text emits LooksLikeButton with nearMissPatterns ruleId", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

[Save`, undefined, undefined);
    let hit = result.warnings.some(w => {
      let match = w.code;
      let match$1 = w.ruleId;
      if (typeof match !== "object" && match === "LooksLikeButton" && match$1 !== undefined) {
        return match$1 === Heuristics.Rule.nearMissPatterns;
      } else {
        return false;
      }
    });
    t.expect(hit).toBe(true);
  });
  Vitest.test("`[x` text emits LooksLikeCheckbox", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

[x`, undefined, undefined);
    let hit = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return match === "LooksLikeCheckbox";
      } else {
        return false;
      }
    });
    t.expect(hit).toBe(true);
  });
  Vitest.test("`[__email` (no closing) is handled by V2InputParser as ErrorNode + UnclosedInput", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

[__email`, undefined, undefined);
    let hasUnclosed = result.errors.some(e => {
      let match = e.code;
      return match === "UnclosedInput";
    });
    t.expect(hasUnclosed).toBe(true);
  });
  Vitest.test("`(x` text emits LooksLikeRadio", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

(x`, undefined, undefined);
    let hit = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return match === "LooksLikeRadio";
      } else {
        return false;
      }
    });
    t.expect(hit).toBe(true);
  });
  Vitest.test("clean text emits NO near-miss warning", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

Just plain text`, undefined, undefined);
    let hit = result.warnings.some(w => {
      let match = w.code;
      if (typeof match === "object") {
        return false;
      }
      switch (match) {
        case "LooksLikeButton" :
        case "LooksLikeInput" :
        case "LooksLikeCheckbox" :
        case "LooksLikeRadio" :
          return true;
        default:
          return false;
      }
    });
    t.expect(hit).toBe(false);
  });
});

Vitest.describe("Regression P3: error end positions advance (Codex round 18)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("unclosed `[__abc` produces an ErrorNode whose end advances past start", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

[__abc`, undefined, undefined);
    let block = result.ast;
    let errNodes = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "ErrorNode") {
        return n._0;
      }
    });
    let e = errNodes[0];
    if (e === undefined) {
      return t.expect("no-error-node").toBe("found");
    }
    let startCol = e.location.start.col;
    let endCol = e.location.end_.col;
    t.expect(endCol > startCol).toBe(true);
  });
  Vitest.test("unclosed `\"abc` UnclosedString error has end past start", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

"abc`, undefined, undefined);
    let unclosed = result.errors.find(e => {
      let match = e.code;
      return match === "UnclosedString";
    });
    if (unclosed === undefined) {
      return t.expect("no-unclosed-string").toBe("found");
    }
    let startCol = unclosed.location.start.col;
    let endCol = unclosed.location.end_.col;
    t.expect(endCol > startCol).toBe(true);
  });
});

export {
  collectNodes,
}
/*  Not a pure module */
