// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

function firstContainer(block) {
  let found = {
    contents: undefined
  };
  collectNodes(block).forEach(n => {
    let match = found.contents;
    if (match !== undefined || n.TAG !== "ContainerNode") {
      return;
    } else {
      found.contents = n._0;
      return;
    }
  });
  return found.contents;
}

Vitest.describe("Regression P2: hyphenated format-1 container ID (Codex round 40)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("`+--#account-email--+` parses with id=account-email", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+--#account-email--+
|                  |
+------------------+`, undefined, undefined);
    let block = result.ast;
    if (block === undefined) {
      return t.expect("no-ast").toBe("ast");
    }
    let c = firstContainer(block);
    if (c !== undefined) {
      return t.expect(c.id).toEqual("account-email");
    } else {
      return t.expect("no-container").toBe("found");
    }
  });
  Vitest.test("`+--#multi-word-id--+` keeps both hyphens", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+--#multi-word-id--+
|                  |
+------------------+`, undefined, undefined);
    let block = result.ast;
    if (block === undefined) {
      return t.expect("no-ast").toBe("ast");
    }
    let c = firstContainer(block);
    if (c !== undefined) {
      return t.expect(c.id).toEqual("multi-word-id");
    } else {
      return t.expect("no-container").toBe("found");
    }
  });
  Vitest.test("`+--#simple--+` still parses (no regression)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+--#simple--+
|           |
+-----------+`, undefined, undefined);
    let block = result.ast;
    if (block === undefined) {
      return t.expect("no-ast").toBe("ast");
    }
    let c = firstContainer(block);
    if (c !== undefined) {
      return t.expect(c.id).toEqual("simple");
    } else {
      return t.expect("no-container").toBe("found");
    }
  });
  Vitest.test("`+-#card-+` (single-dash form) still parses as `card`", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+-#card-+
|       |
+-------+`, undefined, undefined);
    let block = result.ast;
    if (block === undefined) {
      return t.expect("no-ast").toBe("ast");
    }
    let c = firstContainer(block);
    if (c !== undefined) {
      return t.expect(c.id).toEqual("card");
    } else {
      return t.expect("no-container").toBe("found");
    }
  });
});

export {
  collectNodes,
  firstContainer,
}
/*  Not a pure module */
