// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Parser from "../../V2Parser.mjs";

Vitest.describe("Regression P2: duplicate Button/Link IDs reported (Codex round 38)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("two `[ Save ]` buttons emit DuplicateContainerId warning with slug=save", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

[ Save ]
[ Save ]`, undefined, undefined);
    let hasDup = result.warnings.some(w => {
      let id = w.code;
      if (typeof id !== "object" || id.TAG !== "DuplicateContainerId") {
        return false;
      } else {
        return id._0 === "save";
      }
    });
    t.expect(hasDup).toBe(true);
  });
  Vitest.test("two identical `< More >` links emit duplicate warning", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

< More >
< More >`, undefined, undefined);
    let hasDup = result.warnings.some(w => {
      let id = w.code;
      if (typeof id !== "object" || id.TAG !== "DuplicateContainerId") {
        return false;
      } else {
        return id._0 === "more";
      }
    });
    t.expect(hasDup).toBe(true);
  });
  Vitest.test("identical Select placeholders also emit duplicate warning", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

[v: City ]
[v: City ]`, undefined, undefined);
    let hasDup = result.warnings.some(w => {
      let id = w.code;
      if (typeof id !== "object" || id.TAG !== "DuplicateContainerId") {
        return false;
      } else {
        return id._0 === "city";
      }
    });
    t.expect(hasDup).toBe(true);
  });
  Vitest.test("distinct button labels emit NO duplicate warning", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

[ Save ]
[ Cancel ]`, undefined, undefined);
    let hasDup = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return false;
      } else {
        return match.TAG === "DuplicateContainerId";
      }
    });
    t.expect(hasDup).toBe(false);
  });
  Vitest.test("Container id and Button id sharing a slug also emit duplicate", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+--#save--+
|         |
+---------+
[ Save ]`, undefined, undefined);
    let hasDup = result.warnings.some(w => {
      let id = w.code;
      if (typeof id !== "object" || id.TAG !== "DuplicateContainerId") {
        return false;
      } else {
        return id._0 === "save";
      }
    });
    t.expect(hasDup).toBe(true);
  });
});

/*  Not a pure module */
