// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Parser from "../../V2Parser.mjs";

Vitest.describe("Regression P2: nested block declaration is recovered as a new top-level block (Codex round 20)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("@scene inside container produces NestedBlockDeclaration AND the nested block parses as top-level", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: outer

+---------------+
| @scene: inner |
+---------------+`, undefined, undefined);
    let hasNested = result.errors.some(e => {
      let match = e.code;
      return match === "NestedBlockDeclaration";
    });
    t.expect(hasNested).toBe(true);
    t.expect(result.blocks.length).toBe(2);
    let match = result.blocks[0];
    let match$1 = result.blocks[1];
    if (match !== undefined && match.TAG === "SceneBlock" && match$1 !== undefined && match$1.TAG === "SceneBlock") {
      t.expect(match._0.slug).toBe("outer");
      return t.expect(match$1._0.slug).toBe("inner");
    }
    t.expect("missing-blocks").toBe("found");
  });
  Vitest.test("@component inside scene container is recovered as top-level component", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: outer

+---------------------+
| @component: gadget  |
+---------------------+`, undefined, undefined);
    t.expect(result.blocks.length).toBe(2);
    let match = result.blocks[0];
    let match$1 = result.blocks[1];
    if (match !== undefined && match.TAG === "SceneBlock" && match$1 !== undefined && match$1.TAG !== "SceneBlock") {
      t.expect(match._0.slug).toBe("outer");
      return t.expect(match$1._0.slug).toBe("gadget");
    }
    t.expect("wrong-blocks").toBe("right");
  });
  Vitest.test("non-nested input still works (no false rewind)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: outer

+----+
| Hi |
+----+`, undefined, undefined);
    t.expect(result.blocks.length).toBe(1);
    let hasNested = result.errors.some(e => {
      let match = e.code;
      return match === "NestedBlockDeclaration";
    });
    t.expect(hasNested).toBe(false);
  });
});

/*  Not a pure module */
