// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P2: inner container diagnostics not duplicated (Codex round 5)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("${foo} inside a scene container emits exactly ONE PropOutsideComponent warning", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+-------+
|\${foo}|
+-------+`, undefined, undefined);
    let propOutsideWarns = result.warnings.filter(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return match === "PropOutsideComponent";
      } else {
        return false;
      }
    });
    t.expect(propOutsideWarns.length).toBe(1);
  });
  Vitest.test("two distinct inner diagnostics each appear exactly once", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+----------+
|\${a}     |
|\${b}     |
+----------+`, undefined, undefined);
    let propOutsideWarns = result.warnings.filter(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return match === "PropOutsideComponent";
      } else {
        return false;
      }
    });
    t.expect(propOutsideWarns.length).toBe(2);
  });
});

Vitest.describe("Regression P2: checkbox same-row separation (Codex round 5)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("[x] One [ ] Two on one row produces two CheckboxNodes", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

[x] One [ ] Two`, undefined, undefined);
    let block = result.ast;
    let checkboxes = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "CheckboxNode") {
        return n._0;
      }
    });
    t.expect(checkboxes.length).toBe(2);
    let match = checkboxes[0];
    let match$1 = checkboxes[1];
    if (match !== undefined && match$1 !== undefined) {
      t.expect(match.checked).toBe(true);
      t.expect(match.label.trim()).toBe("One");
      t.expect(match$1.checked).toBe(false);
      return t.expect(match$1.label.trim()).toBe("Two");
    } else {
      return t.expect("missing-checkboxes").toBe("found");
    }
  });
  Vitest.test("three same-row checkboxes produce three nodes", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

[ ] A [ ] B [x] C`, undefined, undefined);
    let block = result.ast;
    let checkboxes = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "CheckboxNode") {
        return n._0;
      }
    });
    t.expect(checkboxes.length).toBe(3);
  });
});

export {
  collectNodes,
}
/*  Not a pure module */
