// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P2: nested @scene/@component inside container (Codex round 4)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("@scene inside a container reports NestedBlockDeclaration", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: outer

+---------------+
| @scene: bad   |
+---------------+`, undefined, undefined);
    let hasNested = result.errors.some(e => {
      let match = e.code;
      return match === "NestedBlockDeclaration";
    });
    t.expect(hasNested).toBe(true);
    t.expect(result.success).toBe(false);
  });
  Vitest.test("@component inside a container is also reported", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: outer

+---------------+
| @component: c |
+---------------+`, undefined, undefined);
    let hasNested = result.errors.some(e => {
      let match = e.code;
      return match === "NestedBlockDeclaration";
    });
    t.expect(hasNested).toBe(true);
  });
});

Vitest.describe("Regression P2: unknown prop refs inside strings (Codex round 4)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("${missing} inside a string warns just like the standalone form", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@component: greeting
@props: name

"\${missing}"`, undefined, undefined);
    let hasUnknown = result.warnings.some(w => {
      let n = w.code;
      if (typeof n !== "object" || n.TAG !== "UnknownPropReference") {
        return false;
      } else {
        return n._0 === "missing";
      }
    });
    t.expect(hasUnknown).toBe(true);
  });
  Vitest.test("${name} inside a string does NOT warn when declared", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@component: greeting
@props: name

"Hello \${name}!"`, undefined, undefined);
    let hasUnknown = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return false;
      } else {
        return match.TAG === "UnknownPropReference";
      }
    });
    t.expect(hasUnknown).toBe(false);
  });
  Vitest.test("scene block does NOT emit UnknownPropReference for placeholder text", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

"\${name}"`, undefined, undefined);
    let hasUnknown = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return false;
      } else {
        return match.TAG === "UnknownPropReference";
      }
    });
    t.expect(hasUnknown).toBe(false);
  });
});

Vitest.describe("Regression P3: ContainerNode end offset (Codex round 4)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("container end_.offset > start.offset", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+----+
|    |
+----+`, undefined, undefined);
    let block = result.ast;
    let containers = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "ContainerNode") {
        return n._0;
      }
    });
    t.expect(containers.length >= 1).toBe(true);
    let c = containers[0];
    if (c === undefined) {
      return t.expect("no-container").toBe("found");
    }
    let startOff = c.location.start.offset;
    let endOff = c.location.end_.offset;
    t.expect(endOff > startOff).toBe(true);
    let span = endOff - startOff | 0;
    t.expect(span >= 10).toBe(true);
  });
  Vitest.test("end position row/col match the bottom border", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+----+
|    |
+----+`, undefined, undefined);
    let block = result.ast;
    let containers = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "ContainerNode") {
        return n._0;
      }
    });
    let c = containers[0];
    if (c !== undefined) {
      return t.expect(c.location.end_.row).toBe(c.location.start.row + 2 | 0);
    } else {
      return t.expect("no-container").toBe("found");
    }
  });
});

export {
  collectNodes,
}
/*  Not a pure module */
