// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as Belt_SetString from "@rescript/runtime/lib/es6/Belt_SetString.js";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P2: tab-indented container slices by visual cols (Codex round 9)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.test("tab-indented container keeps its inner text child", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
  let result = V2Parser.parse("@scene: s\n\n\t+------+\n\t| Hi   |\n\t+------+", undefined, undefined);
  let block = result.ast;
  let containers = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
    if (n.TAG === "ContainerNode") {
      return n._0;
    }
  });
  t.expect(containers.length >= 1).toBe(true);
  let foundHi = {
    contents: false
  };
  let block$1 = result.ast;
  (
    block$1 !== undefined ? collectNodes(block$1) : []
  ).forEach(n => {
    if (n.TAG === "TextNode" && n._0.content.includes("Hi")) {
      foundHi.contents = true;
      return;
    }
  });
  t.expect(foundHi.contents).toBe(true);
}));

Vitest.describe("Regression P3: radio group naming (Codex round 9)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("two separated groups → -group-1 and -group-2", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

(*) A
(*) B
         (*) C
         (*) D`, undefined, undefined);
    let block = result.ast;
    let radios = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "RadioNode") {
        return n._0;
      }
    });
    let groups = radios.map(r => Core__Option.getOr(r.group, ""));
    t.expect(radios.length).toBe(4);
    let distinct = Belt_SetString.fromArray(groups);
    let distinctCount = Belt_SetString.size(distinct);
    t.expect(distinctCount).toBe(2);
    Belt_SetString.forEach(distinct, g => {
      let hasPattern = g.includes("-group-1") || g.includes("-group-2") || g.includes("-group-3");
      t.expect(hasPattern).toBe(true);
    });
  });
  Vitest.test("single group → bare -group suffix", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

(*) A
( ) B`, undefined, undefined);
    let block = result.ast;
    let radios = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "RadioNode") {
        return n._0;
      }
    });
    let r = radios[0];
    if (r === undefined) {
      return t.expect("no-radio").toBe("found");
    }
    let g = Core__Option.getOr(r.group, "");
    t.expect(g.endsWith("-group")).toBe(true);
    t.expect(g.includes("-group-")).toBe(false);
  });
});

export {
  collectNodes,
}
/*  Not a pure module */
