// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P1: unclosed input emits error (Codex round 2)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("[__email without closing __] reports UnclosedInput", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

[__email`, undefined, undefined);
    let hasUnclosedInput = result.errors.some(e => {
      let match = e.code;
      return match === "UnclosedInput";
    });
    t.expect(hasUnclosedInput).toBe(true);
  });
  Vitest.test("unclosed input recovery produces an ErrorNode in the AST", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

[__email`, undefined, undefined);
    let foundErrNode = {
      contents: false
    };
    let block = result.ast;
    if (block !== undefined) {
      collectNodes(block).forEach(n => {
        if (n.TAG === "ErrorNode") {
          foundErrNode.contents = true;
          return;
        }
      });
    }
    t.expect(foundErrNode.contents).toBe(true);
  });
});

Vitest.describe("Regression P1: radio grouping wired before validation (Codex round 2)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("vertical radios get assigned group IDs", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

(*) A
( ) B`, undefined, undefined);
    let b = result.ast;
    let radios = Core__Array.filterMap(collectNodes(b !== undefined ? b : ({
        TAG: "SceneBlock",
        _0: {
          location: V2Types.zeroLoc,
          slug: "",
          title: undefined,
          device: undefined,
          transition: undefined,
          children: [],
          layout: V2Types.emptyLayout
        }
      })), n => {
      if (n.TAG === "RadioNode") {
        return n._0;
      }
    });
    t.expect(radios.length).toBe(2);
    radios.forEach(r => t.expect(Core__Option.isSome(r.group)).toBe(true));
  });
  Vitest.test("two selected radios in same group emits MultipleRadiosSelected", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

(*) A
(*) B`, undefined, undefined);
    let hasMultipleSelected = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return false;
      } else {
        return match.TAG === "MultipleRadiosSelected";
      }
    });
    t.expect(hasMultipleSelected).toBe(true);
  });
});

Vitest.describe("Regression P2: invalid format-2 ID line emits InvalidIdFormat (Codex round 2)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.test("| #foo bar | inside container reports InvalidIdFormat", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
  let result = V2Parser.parse(`@scene: s

+-----------+
| #foo bar  |
+-----------+`, undefined, undefined);
  let hasInvalid = result.errors.some(e => {
    let match = e.code;
    return match === "InvalidIdFormat";
  });
  t.expect(hasInvalid).toBe(true);
}));

Vitest.describe("Regression P2: short divider forms (Codex round 2)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("-#id- parses as a Divider with id", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

-#id-`, undefined, undefined);
    let found = {
      contents: undefined
    };
    let block = result.ast;
    if (block !== undefined) {
      collectNodes(block).forEach(n => {
        if (n.TAG === "DividerNode") {
          found.contents = n._0;
          return;
        }
      });
    }
    let d = found.contents;
    if (d !== undefined) {
      return t.expect(d.id).toEqual("id");
    } else {
      return t.expect("no-divider").toBe("found");
    }
  });
  Vitest.test("=#id= parses as a bold Divider with id", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

=#id=`, undefined, undefined);
    let found = {
      contents: undefined
    };
    let block = result.ast;
    if (block !== undefined) {
      collectNodes(block).forEach(n => {
        if (n.TAG === "DividerNode") {
          found.contents = n._0;
          return;
        }
      });
    }
    let d = found.contents;
    if (d !== undefined) {
      t.expect(d.id).toEqual("id");
      return t.expect(d.style).toEqual("Bold");
    } else {
      return t.expect("no-divider").toBe("found");
    }
  });
  Vitest.test("=text= parses as a bold Divider with label", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

=text=`, undefined, undefined);
    let found = {
      contents: undefined
    };
    let block = result.ast;
    if (block !== undefined) {
      collectNodes(block).forEach(n => {
        if (n.TAG === "DividerNode") {
          found.contents = n._0;
          return;
        }
      });
    }
    let d = found.contents;
    if (d !== undefined) {
      t.expect(d.label).toEqual("text");
      return t.expect(d.style).toEqual("Bold");
    } else {
      return t.expect("no-divider").toBe("found");
    }
  });
  Vitest.test("leading dashes WITHOUT trailing dashes are NOT a divider", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

- item`, undefined, undefined);
    let foundDivider = {
      contents: false
    };
    let block = result.ast;
    if (block !== undefined) {
      collectNodes(block).forEach(n => {
        if (n.TAG === "DividerNode") {
          foundDivider.contents = true;
          return;
        }
      });
    }
    t.expect(foundDivider.contents).toBe(false);
  });
});

Vitest.describe("Regression P2: dashless +#id+ container (Codex round 2)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("+#id+ parses as a Container with id", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+#card+
|     |
+-----+`, undefined, undefined);
    let foundContainer = {
      contents: undefined
    };
    let block = result.ast;
    if (block !== undefined) {
      collectNodes(block).forEach(n => {
        if (n.TAG === "ContainerNode") {
          foundContainer.contents = n._0;
          return;
        }
      });
    }
    let c = foundContainer.contents;
    if (c !== undefined) {
      return t.expect(c.id).toEqual("card");
    } else {
      return t.expect("no-container").toBe("found");
    }
  });
  Vitest.test("+-#id-+ also parses as a Container with id", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+-#card-+
|       |
+-------+`, undefined, undefined);
    let foundContainer = {
      contents: undefined
    };
    let block = result.ast;
    if (block !== undefined) {
      collectNodes(block).forEach(n => {
        if (n.TAG === "ContainerNode") {
          foundContainer.contents = n._0;
          return;
        }
      });
    }
    let c = foundContainer.contents;
    if (c !== undefined) {
      return t.expect(c.id).toEqual("card");
    } else {
      return t.expect("no-container").toBe("found");
    }
  });
});

export {
  collectNodes,
}
/*  Not a pure module */
