// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as Heuristics from "../../utils/Heuristics.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P2: body-wall tolerance for containers (Codex round 14)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("body wall shifted +1 col still produces a Container", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+-----+
|    |
+-----+`, undefined, undefined);
    let block = result.ast;
    let containers = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "ContainerNode") {
        return n._0;
      }
    });
    t.expect(containers.length).toBe(1);
    let hasWallWarn = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return match === "MisalignedContainerWall";
      } else {
        return false;
      }
    });
    t.expect(hasWallWarn).toBe(true);
  });
  Vitest.test("perfectly aligned container emits NO wall-tolerance warning", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+-----+
|     |
+-----+`, undefined, undefined);
    let hasWallWarn = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return match === "MisalignedContainerWall";
      } else {
        return false;
      }
    });
    t.expect(hasWallWarn).toBe(false);
  });
  Vitest.test("warning carries the wallAlignment ruleId", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+-----+
|    |
+-----+`, undefined, undefined);
    let hasRuleId = result.warnings.some(w => {
      let match = w.code;
      let match$1 = w.ruleId;
      if (typeof match !== "object" && match === "MisalignedContainerWall" && match$1 !== undefined) {
        return match$1 === Heuristics.Rule.containerWallAlignment;
      } else {
        return false;
      }
    });
    t.expect(hasRuleId).toBe(true);
  });
  Vitest.test("body row with content + only one wall present emits MisalignedContainerWall (regardless of tolerance)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let opts_strict = V2Parser.defaultOptions.strict;
    let opts_tabSize = V2Parser.defaultOptions.tabSize;
    let opts_maxDepth = V2Parser.defaultOptions.maxDepth;
    let opts_heuristics = {
      containerColumnTolerance: 0,
      containerWidthTolerance: Heuristics.emptyPartial.containerWidthTolerance,
      radioHorizontalGap: Heuristics.emptyPartial.radioHorizontalGap,
      radioVerticalColumnTolerance: Heuristics.emptyPartial.radioVerticalColumnTolerance,
      radioMaxBlankRows: Heuristics.emptyPartial.radioMaxBlankRows,
      centerSymmetryThreshold: Heuristics.emptyPartial.centerSymmetryThreshold,
      rightAlignThreshold: Heuristics.emptyPartial.rightAlignThreshold,
      dividerMinRun: Heuristics.emptyPartial.dividerMinRun,
      nearMissTokenDistance: Heuristics.emptyPartial.nearMissTokenDistance
    };
    let opts_emojiRegistry = V2Parser.defaultOptions.emojiRegistry;
    let opts = {
      strict: opts_strict,
      tabSize: opts_tabSize,
      maxDepth: opts_maxDepth,
      heuristics: opts_heuristics,
      emojiRegistry: opts_emojiRegistry
    };
    let result = V2Parser.parse(`@scene: s

+-----+
|    |
+-----+`, opts, undefined);
    let hasWallWarn = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return match === "MisalignedContainerWall";
      } else {
        return false;
      }
    });
    t.expect(hasWallWarn).toBe(true);
  });
});

export {
  collectNodes,
}
/*  Not a pure module */
