// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P2: container child offsets are outer-source-absolute (Codex round 6)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("button inside a container has start.offset pointing at the actual [", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let src = `@scene: s

+--------------+
|   [ Login ]  |
+--------------+`;
    let result = V2Parser.parse(src, undefined, undefined);
    let block = result.ast;
    let buttons = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "ButtonNode") {
        return n._0;
      }
    });
    let b = buttons[0];
    if (b === undefined) {
      return t.expect("no-button").toBe("found");
    }
    let off = b.location.start.offset;
    t.expect(off > 20).toBe(true);
    let ch = src.charAt(off);
    t.expect(ch).toBe("[");
  });
  Vitest.test("input inside a container preserves outer source offset", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let src = `@scene: s

+----------------+
|  [__email__]   |
+----------------+`;
    let result = V2Parser.parse(src, undefined, undefined);
    let block = result.ast;
    let inputs = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "InputNode") {
        return n._0;
      }
    });
    let i = inputs[0];
    if (i === undefined) {
      return t.expect("no-input").toBe("found");
    }
    let off = i.location.start.offset;
    let ch = src.charAt(off);
    t.expect(ch).toBe("[");
  });
});

Vitest.describe("Regression P2: wide-gap same-row radios are NOT grouped (Codex round 6)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("(*) A (10 spaces) (*) B -> different groups, no MultipleRadiosSelected", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

(*) A          (*) B`, undefined, undefined);
    let multipleSelected = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return false;
      } else {
        return match.TAG === "MultipleRadiosSelected";
      }
    });
    t.expect(multipleSelected).toBe(false);
    let block = result.ast;
    let radios = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "RadioNode") {
        return n._0;
      }
    });
    t.expect(radios.length).toBe(2);
    let match = radios[0];
    let match$1 = radios[1];
    if (match !== undefined && match$1 !== undefined) {
      return t.expect(Primitive_object.notequal(match.group, match$1.group)).toBe(true);
    }
  });
  Vitest.test("close-gap (default 6 or fewer) same-row radios ARE grouped", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

(*) A   (*) B`, undefined, undefined);
    let multipleSelected = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return false;
      } else {
        return match.TAG === "MultipleRadiosSelected";
      }
    });
    t.expect(multipleSelected).toBe(true);
  });
});

export {
  collectNodes,
}
/*  Not a pure module */
