// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as Heuristics from "../../utils/Heuristics.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P2: misaligned bottom border tolerance (Codex round 7)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("bottom border drifted +1 col is accepted with a warning", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+-----+
|     |
 +-----+`, undefined, undefined);
    let block = result.ast;
    let containers = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "ContainerNode") {
        return n._0;
      }
    });
    t.expect(containers.length >= 1).toBe(true);
    let hasWarning = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return match === "MisalignedContainerCorner";
      } else {
        return false;
      }
    });
    t.expect(hasWarning).toBe(true);
  });
  Vitest.test("warning carries the cornerAlignment ruleId", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+-----+
|     |
 +-----+`, undefined, undefined);
    let hasRuleId = result.warnings.some(w => {
      let match = w.code;
      let match$1 = w.ruleId;
      if (typeof match !== "object" && match === "MisalignedContainerCorner" && match$1 !== undefined) {
        return match$1 === Heuristics.Rule.containerCornerAlignment;
      } else {
        return false;
      }
    });
    t.expect(hasRuleId).toBe(true);
  });
  Vitest.test("aligned containers do NOT emit a tolerance warning", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+-----+
|     |
+-----+`, undefined, undefined);
    let hasWarning = result.warnings.some(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return match === "MisalignedContainerCorner";
      } else {
        return false;
      }
    });
    t.expect(hasWarning).toBe(false);
  });
  Vitest.test("nested container's `+` is NOT mistaken for outer's bottom (no false tolerance match)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

+----------+
|+--------+|
||   Hi   ||
|+--------+|
+----------+`, undefined, undefined);
    let hasUnclosed = result.errors.some(e => {
      let match = e.code;
      return match === "UnclosedContainer";
    });
    t.expect(hasUnclosed).toBe(false);
    let block = result.ast;
    let containers = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "ContainerNode") {
        return n._0;
      }
    });
    t.expect(containers.length >= 2).toBe(true);
  });
});

Vitest.describe("Regression P2: tabSize propagates into containers (Codex round 7)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.test("tab inside container respects tabSize=2 vs default", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
  let src = "@scene: s\n\n+--------+\n|\tx     |\n+--------+";
  let opts2_strict = V2Parser.defaultOptions.strict;
  let opts2_maxDepth = V2Parser.defaultOptions.maxDepth;
  let opts2_heuristics = V2Parser.defaultOptions.heuristics;
  let opts2_emojiRegistry = V2Parser.defaultOptions.emojiRegistry;
  let opts2 = {
    strict: opts2_strict,
    tabSize: 2,
    maxDepth: opts2_maxDepth,
    heuristics: opts2_heuristics,
    emojiRegistry: opts2_emojiRegistry
  };
  let opts8_strict = V2Parser.defaultOptions.strict;
  let opts8_maxDepth = V2Parser.defaultOptions.maxDepth;
  let opts8_heuristics = V2Parser.defaultOptions.heuristics;
  let opts8_emojiRegistry = V2Parser.defaultOptions.emojiRegistry;
  let opts8 = {
    strict: opts8_strict,
    tabSize: 8,
    maxDepth: opts8_maxDepth,
    heuristics: opts8_heuristics,
    emojiRegistry: opts8_emojiRegistry
  };
  let r2 = V2Parser.parse(src, opts2, undefined);
  let r8 = V2Parser.parse(src, opts8, undefined);
  let textOf = r => {
    let block = r.ast;
    if (block === undefined) {
      return;
    }
    let nodes = collectNodes(block);
    return nodes.find(n => n.TAG === "TextNode");
  };
  let match = textOf(r2);
  let match$1 = textOf(r8);
  if (match !== undefined && match.TAG === "TextNode" && match$1 !== undefined && match$1.TAG === "TextNode") {
    return t.expect(match._0.location.start.col !== match$1._0.location.start.col).toBe(true);
  }
  t.expect("missing-text-nodes").toBe("present");
}));

export {
  collectNodes,
}
/*  Not a pure module */
