// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P2: recovered block strips right wall too (Codex round 24)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.test("recovered nested block `| Hi |` produces TextNode('Hi'), not 'Hi |'", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
  let result = V2Parser.parse(`@scene: outer

+----------+
| @scene: x |
| Hi       |
+----------+`, undefined, undefined);
  let match = result.blocks[1];
  if (match === undefined) {
    return t.expect("no-inner").toBe("found");
  }
  if (match.TAG !== "SceneBlock") {
    return t.expect("no-inner").toBe("found");
  }
  let nodes = collectNodes({
    TAG: "SceneBlock",
    _0: match._0
  });
  let foundClean = nodes.some(n => {
    if (n.TAG === "TextNode") {
      return n._0.content.trim() === "Hi";
    } else {
      return false;
    }
  });
  let foundDirty = nodes.some(n => {
    if (n.TAG === "TextNode") {
      return n._0.content.includes("|");
    } else {
      return false;
    }
  });
  t.expect(foundClean).toBe(true);
  t.expect(foundDirty).toBe(false);
}));

Vitest.describe("Regression P2: header-attrs are read behind container walls (Codex round 24)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("`| @title: Inner |` after recovered header sets the title", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: outer

+-----------------+
| @scene: inner   |
| @title: Cool    |
| Body            |
+-----------------+`, undefined, undefined);
    let match = result.blocks[1];
    if (match === undefined) {
      return t.expect("no-inner").toBe("found");
    }
    if (match.TAG !== "SceneBlock") {
      return t.expect("no-inner").toBe("found");
    }
    let s = match._0;
    t.expect(s.slug).toBe("inner");
    t.expect(s.title).toEqual("Cool");
  });
  Vitest.test("`| @device: mobile |` behind walls is honored", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: outer

+--------------------+
| @scene: phone      |
| @device: mobile    |
+--------------------+`, undefined, undefined);
    let match = result.blocks[1];
    if (match !== undefined && match.TAG === "SceneBlock") {
      return t.expect(match._0.device).toEqual("Mobile");
    } else {
      return t.expect("no-inner").toBe("found");
    }
  });
});

export {
  collectNodes,
}
/*  Not a pure module */
