// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Parser from "../../V2Parser.mjs";

Vitest.describe("Regression P2: pipe noise gated to nested recovery (Codex round 21)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("`| @scene: x |` alone (no real top-level header) reports MissingBlockDeclaration", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`| @scene: nope |`, undefined, undefined);
    let hasMissing = result.errors.some(e => {
      let match = e.code;
      return match === "MissingBlockDeclaration";
    });
    t.expect(hasMissing).toBe(true);
    t.expect(result.blocks.length).toBe(0);
  });
  Vitest.test("`| @component: c |` before any header does NOT register a component", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`| @component: c |`, undefined, undefined);
    t.expect(result.blocks.length).toBe(0);
  });
  Vitest.test("nested-block recovery still works after this gating", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: outer

+---------------+
| @scene: inner |
+---------------+`, undefined, undefined);
    t.expect(result.blocks.length).toBe(2);
    let match = result.blocks[0];
    let match$1 = result.blocks[1];
    if (match !== undefined && match.TAG === "SceneBlock" && match$1 !== undefined && match$1.TAG === "SceneBlock") {
      t.expect(match._0.slug).toBe("outer");
      return t.expect(match$1._0.slug).toBe("inner");
    }
    t.expect("missing-blocks").toBe("found");
  });
  Vitest.test("after recovery, AT MOST ONE subsequent lookup uses pipe-noise", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: outer

+---------------+
| @scene: inner |
+---------------+`, undefined, undefined);
    t.expect(result.blocks.length).toBe(2);
  });
});

/*  Not a pure module */
