// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";

Vitest.describe("Regression P2: MultipleRadiosSelected uses a real location (Codex round 33)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("warning location points at a row in the conflicting group (not zeroLoc)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

(*) A
(*) B`, undefined, undefined);
    let warn = result.warnings.find(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return false;
      } else {
        return match.TAG === "MultipleRadiosSelected";
      }
    });
    if (warn !== undefined) {
      return t.expect(warn.location.start.row > 0).toBe(true);
    } else {
      return t.expect("no-warning").toBe("present");
    }
  });
  Vitest.test("warning location matches a radio in the same group", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse(`@scene: s

(*) A
(*) B`, undefined, undefined);
    let warn = result.warnings.find(w => {
      let match = w.code;
      if (typeof match !== "object") {
        return false;
      } else {
        return match.TAG === "MultipleRadiosSelected";
      }
    });
    let match = result.ast;
    let radioRows = match !== undefined ? (
        match.TAG === "SceneBlock" ? Core__Array.filterMap(match._0.children, n => {
            if (n.TAG !== "RadioNode") {
              return;
            }
            let r = n._0;
            if (r.selected) {
              return r.location.start.row;
            }
          }) : []
      ) : [];
    if (warn === undefined) {
      return t.expect("no-warning").toBe("present");
    }
    let matchesRow = radioRows.some(row => row === warn.location.start.row);
    t.expect(matchesRow).toBe(true);
  });
});

/*  Not a pure module */
