// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as V2Types from "../../types/V2Types.mjs";
import * as V2Parser from "../../V2Parser.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";

function collectNodes(block) {
  let acc = [];
  let walk = n => {
    acc.push(n);
    let c = V2Types.getChildren(n);
    if (c !== undefined) {
      c.forEach(walk);
      return;
    }
  };
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  walk(root);
  return acc;
}

Vitest.describe("Regression P2: container body for CR-line-ending input (Codex round 31)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("CR-only line endings preserve container children", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse("@scene: s\r\r+----+\r| Hi |\r+----+", undefined, undefined);
    t.expect(result.success).toBe(true);
    let block = result.ast;
    let containers = Core__Array.filterMap(block !== undefined ? collectNodes(block) : [], n => {
      if (n.TAG === "ContainerNode") {
        return n._0;
      }
    });
    t.expect(containers.length).toBe(1);
    let foundHi = {
      contents: false
    };
    containers.forEach(c => {
      c.children.forEach(child => {
        if (child.TAG === "TextNode" && child._0.content.includes("Hi")) {
          foundHi.contents = true;
          return;
        }
      });
    });
    t.expect(foundHi.contents).toBe(true);
  });
  Vitest.test("CRLF line endings also work", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let result = V2Parser.parse("@scene: s\r\n\r\n+----+\r\n| Hi |\r\n+----+", undefined, undefined);
    t.expect(result.success).toBe(true);
    let foundHi = {
      contents: false
    };
    let block = result.ast;
    if (block !== undefined) {
      collectNodes(block).forEach(n => {
        if (n.TAG === "TextNode" && n._0.content.includes("Hi")) {
          foundHi.contents = true;
          return;
        }
      });
    }
    t.expect(foundHi.contents).toBe(true);
  });
});

export {
  collectNodes,
}
/*  Not a pure module */
