// Generated by ReScript, PLEASE EDIT WITH CARE


function processEscapeChar(c) {
  switch (c) {
    case "$" :
      return "$";
    case "\"" :
      return "\"";
    case "\\" :
      return "\\";
    case "n" :
      return "\n";
    case "t" :
      return "\t";
    default:
      return;
  }
}

function unescapeString(s) {
  let n = s.length;
  let out = "";
  let i = 0;
  while (i < n) {
    let ch = s.charAt(i);
    if (ch === "\\" && (i + 1 | 0) < n) {
      let next = s.charAt(i + 1 | 0);
      let decoded = processEscapeChar(next);
      if (decoded !== undefined) {
        out = out + decoded;
        i = i + 2 | 0;
      } else {
        out = out + ch;
        i = i + 1 | 0;
      }
    } else {
      out = out + ch;
      i = i + 1 | 0;
    }
  };
  return out;
}

export {
  processEscapeChar,
  unescapeString,
}
/* No side effect */
