// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.mjs";

let $$default = {
  containerColumnTolerance: 1,
  containerWidthTolerance: 2,
  radioHorizontalGap: 6,
  radioVerticalColumnTolerance: 1,
  radioMaxBlankRows: 0,
  centerSymmetryThreshold: 0.15,
  rightAlignThreshold: 0.10,
  dividerMinRun: 3,
  nearMissTokenDistance: 1
};

let normalizePartial = (function(p) {
    if (p === undefined || p === null) {
      return {
        containerColumnTolerance: undefined,
        containerWidthTolerance: undefined,
        radioHorizontalGap: undefined,
        radioVerticalColumnTolerance: undefined,
        radioMaxBlankRows: undefined,
        centerSymmetryThreshold: undefined,
        rightAlignThreshold: undefined,
        dividerMinRun: undefined,
        nearMissTokenDistance: undefined,
      };
    }
    return p;
  });

function applyPartial(p, base) {
  let p$1 = normalizePartial(p);
  return {
    containerColumnTolerance: Core__Option.getOr(p$1.containerColumnTolerance, base.containerColumnTolerance),
    containerWidthTolerance: Core__Option.getOr(p$1.containerWidthTolerance, base.containerWidthTolerance),
    radioHorizontalGap: Core__Option.getOr(p$1.radioHorizontalGap, base.radioHorizontalGap),
    radioVerticalColumnTolerance: Core__Option.getOr(p$1.radioVerticalColumnTolerance, base.radioVerticalColumnTolerance),
    radioMaxBlankRows: Core__Option.getOr(p$1.radioMaxBlankRows, base.radioMaxBlankRows),
    centerSymmetryThreshold: Core__Option.getOr(p$1.centerSymmetryThreshold, base.centerSymmetryThreshold),
    rightAlignThreshold: Core__Option.getOr(p$1.rightAlignThreshold, base.rightAlignThreshold),
    dividerMinRun: Core__Option.getOr(p$1.dividerMinRun, base.dividerMinRun),
    nearMissTokenDistance: Core__Option.getOr(p$1.nearMissTokenDistance, base.nearMissTokenDistance)
  };
}

function make(overrides, param) {
  if (overrides !== undefined) {
    return applyPartial(overrides, $$default);
  } else {
    return $$default;
  }
}

let Rule = {
  containerCornerAlignment: "container.cornerAlignment",
  containerWallAlignment: "container.wallAlignment",
  containerWidthConsistency: "container.widthConsistency",
  radioGroupingHorizontal: "radioGrouping.horizontal",
  radioGroupingVertical: "radioGrouping.vertical",
  radioGroupingContainer: "radioGrouping.container",
  textCenter: "text.center",
  textRight: "text.right",
  dividerMinRun: "divider.minRun",
  nearMissPatterns: "nearMissPatterns",
  errorRecoveryContainerSync: "errorRecovery.containerSync",
  errorRecoveryInputSync: "errorRecovery.inputSync"
};

let emptyPartial = {
  containerColumnTolerance: undefined,
  containerWidthTolerance: undefined,
  radioHorizontalGap: undefined,
  radioVerticalColumnTolerance: undefined,
  radioMaxBlankRows: undefined,
  centerSymmetryThreshold: undefined,
  rightAlignThreshold: undefined,
  dividerMinRun: undefined,
  nearMissTokenDistance: undefined
};

export {
  $$default as default,
  emptyPartial,
  normalizePartial,
  applyPartial,
  make,
  Rule,
}
/* No side effect */
