// Generated by ReScript, PLEASE EDIT WITH CARE

import * as UnicodeUtils from "./UnicodeUtils.mjs";

function make(row, col, offset) {
  return {
    row: row,
    col: col,
    offset: offset
  };
}

function advance(p, s, tabSizeOpt, param) {
  let tabSize = tabSizeOpt !== undefined ? tabSizeOpt : 4;
  let width = UnicodeUtils.visualWidth(s, p.col, tabSize, undefined);
  return {
    row: p.row,
    col: p.col + width | 0,
    offset: p.offset + s.length | 0
  };
}

function newline(p) {
  return {
    row: p.row + 1 | 0,
    col: 0,
    offset: p.offset + 1 | 0
  };
}

function toDisplay(p) {
  return `(line ` + (p.row + 1 | 0).toString() + `, col ` + (p.col + 1 | 0).toString() + `)`;
}

let zero = {
  row: 0,
  col: 0,
  offset: 0
};

export {
  make,
  zero,
  advance,
  newline,
  toDisplay,
}
/* No side effect */
