// Generated by ReScript, PLEASE EDIT WITH CARE


function slugify(text) {
  let trimmed = text.trim();
  if (trimmed === "") {
    return "empty";
  }
  let lower = trimmed.toLowerCase();
  let withDashes = lower.replace(/[^a-z0-9-￿]+/g, "-");
  let collapsed = withDashes.replace(/-+/g, "-");
  let stripped = collapsed.replace(/^-+|-+$/g, "");
  if (stripped === "") {
    return "empty";
  } else {
    return stripped;
  }
}

export {
  slugify,
}
/* No side effect */
