// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";

function isWide(cp) {
  if (cp >= 4352 && cp <= 4447 || cp >= 11904 && cp <= 12350 || cp >= 12353 && cp <= 13311 || cp >= 13312 && cp <= 19903 || cp >= 19968 && cp <= 40959 || cp >= 40960 && cp <= 42191 || cp >= 44032 && cp <= 55203 || cp >= 63744 && cp <= 64255 || cp >= 65072 && cp <= 65103 || cp >= 65280 && cp <= 65376 || cp >= 65504 && cp <= 65510 || cp >= 127744 && cp <= 129791) {
    return true;
  } else if (cp >= 131072) {
    return cp <= 196607;
  } else {
    return false;
  }
}

function isCombining(cp) {
  if (cp >= 768 && cp <= 879 || cp >= 6832 && cp <= 6911 || cp >= 7616 && cp <= 7679 || cp >= 8400 && cp <= 8447 || cp >= 65056 && cp <= 65071) {
    return true;
  } else {
    return cp === 8205;
  }
}

function graphemeWidth(s) {
  if (s === "") {
    return 0;
  }
  let cp = Core__Option.getOr(s.codePointAt(0), 32);
  if (isCombining(cp)) {
    return 0;
  } else if (isWide(cp)) {
    return 2;
  } else {
    return 1;
  }
}

function foldGraphemes(s, f, init) {
  let n = s.length;
  let acc = init;
  let i = 0;
  while (i < n) {
    let cp = Core__Option.getOr(s.codePointAt(i), 32);
    let cuLen = cp > 65535 ? 2 : 1;
    let clusterStart = i;
    let clusterEnd = clusterStart + cuLen | 0;
    let keepExtending = true;
    let lastWasZwj = cp === 8205;
    while (keepExtending && clusterEnd < n) {
      let nextCp = Core__Option.getOr(s.codePointAt(clusterEnd), -1);
      if (nextCp < 0 || !(isCombining(nextCp) || lastWasZwj)) {
        keepExtending = false;
      } else {
        clusterEnd = clusterEnd + (
          nextCp > 65535 ? 2 : 1
        ) | 0;
        lastWasZwj = nextCp === 8205;
      }
    };
    let width = isCombining(cp) ? 0 : (
        isWide(cp) ? 2 : 1
      );
    acc = f(acc, clusterStart, clusterEnd, width);
    i = clusterEnd;
  };
  return acc;
}

function visualWidth(s, startColOpt, tabSizeOpt, param) {
  let startCol = startColOpt !== undefined ? startColOpt : 0;
  let tabSize = tabSizeOpt !== undefined ? tabSizeOpt : 4;
  let col = startCol;
  let n = s.length;
  let i = 0;
  let prevWasZwj = false;
  while (i < n) {
    let cp = Core__Option.getOr(s.codePointAt(i), 32);
    let cuLen = cp > 65535 ? 2 : 1;
    if (cp === 9) {
      let next = (Primitive_int.div(col, tabSize) + 1 | 0) * tabSize | 0;
      col = next;
      prevWasZwj = false;
    } else if (cp === 8205) {
      prevWasZwj = true;
    } else if (prevWasZwj) {
      prevWasZwj = false;
    } else if (!isCombining(cp)) {
      col = isWide(cp) ? col + 2 | 0 : col + 1 | 0;
    }
    i = i + cuLen | 0;
  };
  return col - startCol | 0;
}

function slice(s, start, end_) {
  return s.slice(start, end_);
}

export {
  isWide,
  isCombining,
  graphemeWidth,
  foldGraphemes,
  visualWidth,
  slice,
}
/* No side effect */
