// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Lexer from "../lexer/Lexer.mjs";
import * as Priority from "../parser/Priority.mjs";
import * as V2Errors from "../types/V2Errors.mjs";
import * as GridIndex from "../lexer/GridIndex.mjs";
import * as Heuristics from "../utils/Heuristics.mjs";
import * as TokenStream from "../lexer/TokenStream.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as ParseContext from "../parser/ParseContext.mjs";
import * as UnicodeUtils from "../utils/UnicodeUtils.mjs";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as LayoutInferrer from "../layout/LayoutInferrer.mjs";
import * as V2ElementParser from "./V2ElementParser.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as V2ParserRegistry from "./V2ParserRegistry.mjs";

function splitLines(source) {
  let normalized = source.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  return normalized.split("\n");
}

function rowStartOffsets(source) {
  let n = source.length;
  let result = [0];
  let i = 0;
  while (i < n) {
    let ch = source.charAt(i);
    if (ch === "\r") {
      let next = i + 1 | 0;
      let isCRLF = next < n && source.charAt(next) === "\n";
      let skip = isCRLF ? 2 : 1;
      result.push(i + skip | 0);
      i = i + skip | 0;
    } else if (ch === "\n") {
      result.push(i + 1 | 0);
      i = i + 1 | 0;
    } else {
      i = i + 1 | 0;
    }
  };
  return result;
}

function detectTopBorder(stream) {
  let snap = TokenStream.save(stream);
  let plus1 = TokenStream.peek(stream);
  let match = plus1.kind;
  if (typeof match !== "object") {
    if (match === "Plus") {
      let lc = plus1.position.col;
      TokenStream.next(stream);
      let nameBuf = "";
      let idCandidate;
      let sawDashes = false;
      let keep = true;
      let endPos = plus1.endPosition;
      let plus2Col = -1;
      while (keep) {
        let tok = TokenStream.peek(stream);
        let match$1 = tok.kind;
        let exit = 0;
        if (typeof match$1 !== "object") {
          switch (match$1) {
            case "Identifier" :
              exit = 1;
              break;
            case "Plus" :
              plus2Col = tok.position.col;
              endPos = tok.endPosition;
              TokenStream.next(stream);
              keep = false;
              break;
            case "Hash" :
              TokenStream.next(stream);
              let idBuf = "";
              let keepId = true;
              while (keepId) {
                let t = TokenStream.peek(stream);
                let match$2 = t.kind;
                if (typeof match$2 !== "object") {
                  if (match$2 === "Identifier") {
                    idBuf = idBuf + t.text;
                    TokenStream.next(stream);
                  } else {
                    keepId = false;
                  }
                } else if (match$2.TAG === "Dashes" && match$2._0 === 1) {
                  let next = TokenStream.peekAt(stream, 1);
                  let match$3 = next.kind;
                  if (typeof match$3 !== "object" && match$3 === "Identifier") {
                    idBuf = idBuf + "-";
                    TokenStream.next(stream);
                  } else {
                    keepId = false;
                  }
                } else {
                  keepId = false;
                }
              };
              if (idBuf !== "") {
                idCandidate = idBuf;
              }
              break;
            case "Newline" :
            case "EOF" :
              keep = false;
              break;
            default:
              keep = false;
              plus2Col = -2;
          }
        } else {
          switch (match$1.TAG) {
            case "Dashes" :
              sawDashes = true;
              TokenStream.next(stream);
              break;
            case "Whitespace" :
              exit = 1;
              break;
            default:
              keep = false;
              plus2Col = -2;
          }
        }
        if (exit === 1) {
          nameBuf = nameBuf + tok.text;
          TokenStream.next(stream);
        }
      };
      let hasShape = sawDashes || Core__Option.isSome(idCandidate);
      if (plus2Col < 0 || !hasShape) {
        TokenStream.restore(stream, snap);
        return;
      }
      let after = TokenStream.peek(stream);
      let match$4 = after.kind;
      let trailingOk;
      if (typeof match$4 !== "object") {
        switch (match$4) {
          case "Newline" :
          case "EOF" :
            trailingOk = true;
            break;
          default:
            trailingOk = false;
        }
      } else if (match$4.TAG === "Whitespace") {
        let match$5 = TokenStream.peekAt(stream, 1).kind;
        if (typeof match$5 !== "object") {
          switch (match$5) {
            case "Newline" :
            case "EOF" :
              trailingOk = true;
              break;
            default:
              trailingOk = false;
          }
        } else {
          trailingOk = false;
        }
      } else {
        trailingOk = false;
      }
      if (trailingOk) {
        TokenStream.restore(stream, snap);
        let name = nameBuf.trim();
        return [
          lc,
          plus2Col,
          name === "" ? undefined : name,
          idCandidate,
          endPos
        ];
      }
      TokenStream.restore(stream, snap);
      return;
    }
    TokenStream.restore(stream, snap);
    return;
  } else {
    TokenStream.restore(stream, snap);
    return;
  }
}

function canParse(stream) {
  return detectTopBorder(stream) !== undefined;
}

function consumeRow(stream) {
  let keep = true;
  while (keep) {
    let tok = TokenStream.peek(stream);
    let match = tok.kind;
    if (typeof match !== "object") {
      switch (match) {
        case "Newline" :
          TokenStream.next(stream);
          keep = false;
          break;
        case "EOF" :
          keep = false;
          break;
        default:
          TokenStream.next(stream);
      }
    } else {
      TokenStream.next(stream);
    }
  };
}

function isBottomBorderRow(gridIndex, tokens, row, lc, rc, tolerance) {
  let chL = GridIndex.charAt(gridIndex, tokens, row, lc);
  let chR = GridIndex.charAt(gridIndex, tokens, row, rc);
  let dashRunPresent = () => {
    let foundDash = false;
    let c = lc + 1 | 0;
    while (!foundDash && c < rc) {
      let ch = GridIndex.charAt(gridIndex, tokens, row, c);
      if (ch === "-" || ch === "=") {
        foundDash = true;
      }
      c = c + 1 | 0;
    };
    return foundDash;
  };
  if (chL === "+" && chR === "+" && dashRunPresent()) {
    return "Exact";
  }
  if (chL === "|" || chR === "|") {
    return "NoMatch";
  }
  if (tolerance <= 0) {
    return "NoMatch";
  }
  let leftHit = chL === "+";
  let rightHit = chR === "+";
  let d = 1;
  while ((!leftHit || !rightHit) && d <= tolerance) {
    if (!leftHit) {
      let lm = GridIndex.charAt(gridIndex, tokens, row, lc - d | 0);
      let lp = GridIndex.charAt(gridIndex, tokens, row, lc + d | 0);
      if (lm === "+" || lp === "+") {
        leftHit = true;
      }
    }
    if (!rightHit) {
      let rm = GridIndex.charAt(gridIndex, tokens, row, rc - d | 0);
      let rp = GridIndex.charAt(gridIndex, tokens, row, rc + d | 0);
      if (rm === "+" || rp === "+") {
        rightHit = true;
      }
    }
    d = d + 1 | 0;
  };
  if (leftHit && rightHit && dashRunPresent()) {
    return "Tolerated";
  } else {
    return "NoMatch";
  }
}

function wallAt(gridIndex, tokens, row, col, tolerance) {
  let ch = GridIndex.charAt(gridIndex, tokens, row, col);
  if (ch === "|") {
    return "Exact";
  }
  if (tolerance <= 0) {
    return "NoMatch";
  }
  let found = false;
  let d = 1;
  while (!found && d <= tolerance) {
    let chM = GridIndex.charAt(gridIndex, tokens, row, col - d | 0);
    let chP = GridIndex.charAt(gridIndex, tokens, row, col + d | 0);
    if (chM === "|" || chP === "|") {
      found = true;
    }
    d = d + 1 | 0;
  };
  if (found) {
    return "Tolerated";
  } else {
    return "NoMatch";
  }
}

function bodyRowWalls(gridIndex, tokens, row, lc, rc, tolerance) {
  return [
    wallAt(gridIndex, tokens, row, lc, tolerance),
    wallAt(gridIndex, tokens, row, rc, tolerance)
  ];
}

function bottomCornerCols(gridIndex, tokens, row, hintLc, hintRc, tolerance) {
  let lcOut = -1;
  let rcOut = -1;
  let probe = col => GridIndex.charAt(gridIndex, tokens, row, col) === "+";
  if (probe(hintLc)) {
    lcOut = hintLc;
  } else {
    let d = 1;
    while (lcOut < 0 && d <= tolerance) {
      if (probe(hintLc - d | 0)) {
        lcOut = hintLc - d | 0;
      } else if (probe(hintLc + d | 0)) {
        lcOut = hintLc + d | 0;
      }
      d = d + 1 | 0;
    };
  }
  if (probe(hintRc)) {
    rcOut = hintRc;
  } else {
    let d$1 = 1;
    while (rcOut < 0 && d$1 <= tolerance) {
      if (probe(hintRc - d$1 | 0)) {
        rcOut = hintRc - d$1 | 0;
      } else if (probe(hintRc + d$1 | 0)) {
        rcOut = hintRc + d$1 | 0;
      }
      d$1 = d$1 + 1 | 0;
    };
  }
  return [
    lcOut,
    rcOut
  ];
}

function findBottomRow(ctx, topRow, lc, rc) {
  let colTolerance = ctx.heuristics.containerColumnTolerance;
  let widthTolerance = ctx.heuristics.containerWidthTolerance;
  let tolerance = colTolerance > widthTolerance ? colTolerance : widthTolerance;
  let r = topRow + 1 | 0;
  let maxRow = GridIndex.lastRow(ctx.gridIndex) + 1 | 0;
  let found = -1;
  let bottomTolerated = false;
  let wallTolerated = false;
  let keep = true;
  while (keep && r <= maxRow) {
    let match = isBottomBorderRow(ctx.gridIndex, ctx.tokens, r, lc, rc, tolerance);
    switch (match) {
      case "NoMatch" :
        let match$1 = bodyRowWalls(ctx.gridIndex, ctx.tokens, r, lc, rc, colTolerance);
        let rWall = match$1[1];
        let lWall = match$1[0];
        let lPresent;
        switch (lWall) {
          case "Exact" :
          case "Tolerated" :
            lPresent = true;
            break;
          case "NoMatch" :
            lPresent = false;
            break;
        }
        let rPresent;
        switch (rWall) {
          case "Exact" :
          case "Tolerated" :
            rPresent = true;
            break;
          case "NoMatch" :
            rPresent = false;
            break;
        }
        if ((lWall === "Tolerated" || rWall === "Tolerated") && lPresent && rPresent) {
          wallTolerated = true;
        }
        let hasAnything = false;
        let c = lc + 1 | 0;
        while (!hasAnything && c < rc) {
          let ch = GridIndex.charAt(ctx.gridIndex, ctx.tokens, r, c);
          if (ch !== " " && ch !== "") {
            hasAnything = true;
          }
          c = c + 1 | 0;
        };
        if (!lPresent && !rPresent) {
          if (hasAnything) {
            keep = false;
          } else {
            r = r + 1 | 0;
          }
        } else if (!lPresent || !rPresent) {
          if (hasAnything) {
            wallTolerated = true;
          }
          r = r + 1 | 0;
        } else {
          r = r + 1 | 0;
        }
        break;
      case "Exact" :
        found = r;
        keep = false;
        break;
      case "Tolerated" :
        found = r;
        bottomTolerated = true;
        keep = false;
        break;
    }
  };
  let widthMismatch = false;
  if (found >= 0) {
    let match$2 = bottomCornerCols(ctx.gridIndex, ctx.tokens, found, lc, rc, tolerance);
    let rcB = match$2[1];
    let lcB = match$2[0];
    if (lcB >= 0 && rcB >= 0) {
      let topWidth = (rc - lc | 0) + 1 | 0;
      let bottomWidth = (rcB - lcB | 0) + 1 | 0;
      if (topWidth !== bottomWidth) {
        widthMismatch = true;
      }
    }
  }
  return [
    found,
    bottomTolerated,
    wallTolerated,
    widthMismatch
  ];
}

function extractInnerSource(ctx, topRow, bottomRow, lc, rc) {
  let lines = splitLines(ctx.source);
  let byteIndexForVisualCol = (line, targetCol) => {
    let n = line.length;
    let i = 0;
    let col = 0;
    let keep = true;
    while (keep && i < n && col < targetCol) {
      let cp = Core__Option.getOr(line.codePointAt(i), 32);
      let cuLen = cp > 65535 ? 2 : 1;
      if (cp === 9) {
        let next = (Primitive_int.div(col, ctx.tabSize) + 1 | 0) * ctx.tabSize | 0;
        col = next;
      } else if (!UnicodeUtils.isCombining(cp)) {
        col = UnicodeUtils.isWide(cp) ? col + 2 | 0 : col + 1 | 0;
      }
      i = i + cuLen | 0;
      if (col >= targetCol) {
        keep = false;
      }
    };
    return i;
  };
  let buf = "";
  let r = topRow + 1 | 0;
  while (r < bottomRow) {
    let line = Core__Option.getOr(lines[r], "");
    let len = line.length;
    let innerStartByte = byteIndexForVisualCol(line, lc + 1 | 0);
    let innerEndByte = byteIndexForVisualCol(line, rc);
    let safeStart = innerStartByte > len ? len : innerStartByte;
    let safeEnd = innerEndByte > len ? len : innerEndByte;
    let slice = safeStart >= safeEnd ? "" : line.slice(safeStart, safeEnd);
    let wallAtCanonical = line.charAt(innerEndByte) === "|";
    let trimmedSlice = !wallAtCanonical && slice.endsWith("|") ? slice.slice(0, slice.length - 1 | 0) : slice;
    buf = buf + trimmedSlice;
    if (r < (bottomRow - 1 | 0)) {
      buf = buf + "\n";
    }
    r = r + 1 | 0;
  };
  return buf;
}

let registryHolder = {
  contents: undefined
};

function setRegistry(r) {
  registryHolder.contents = {
    registry: r
  };
}

function getRegistry() {
  let rr = registryHolder.contents;
  if (rr !== undefined) {
    return rr.registry;
  }
}

function parseInnerContent(ctx, inner, lc, rc, topRow, bottomRow) {
  let reg = getRegistry();
  if (reg === undefined) {
    return [];
  }
  let tokens = Lexer.tokenize(ctx.tabSize, inner);
  let outerLines = splitLines(ctx.source);
  let offsetTable = rowStartOffsets(ctx.source);
  let rowStartOffset = outerRow => Core__Option.getOr(offsetTable[outerRow], ctx.source.length);
  let byteIndexInRow = (outerRow, targetCol) => {
    let line = Core__Option.getOr(outerLines[outerRow], "");
    let n = line.length;
    let i = 0;
    let col = 0;
    let keep = true;
    while (keep && i < n && col < targetCol) {
      let cp = Core__Option.getOr(line.codePointAt(i), 32);
      let cuLen = cp > 65535 ? 2 : 1;
      if (cp === 9) {
        col = (Primitive_int.div(col, ctx.tabSize) + 1 | 0) * ctx.tabSize | 0;
      } else if (!UnicodeUtils.isCombining(cp)) {
        col = UnicodeUtils.isWide(cp) ? col + 2 | 0 : col + 1 | 0;
      }
      i = i + cuLen | 0;
      if (col >= targetCol) {
        keep = false;
      }
    };
    return i;
  };
  let adjusted = tokens.map(tok => {
    let outerRowS = (tok.position.row + topRow | 0) + 1 | 0;
    let outerRowE = (tok.endPosition.row + topRow | 0) + 1 | 0;
    let outerColS = (tok.position.col + lc | 0) + 1 | 0;
    let outerColE = (tok.endPosition.col + lc | 0) + 1 | 0;
    let pos_offset = rowStartOffset(outerRowS) + byteIndexInRow(outerRowS, outerColS) | 0;
    let pos = {
      row: outerRowS,
      col: outerColS,
      offset: pos_offset
    };
    let endPos_offset = rowStartOffset(outerRowE) + byteIndexInRow(outerRowE, outerColE) | 0;
    let endPos = {
      row: outerRowE,
      col: outerColE,
      offset: endPos_offset
    };
    return {
      kind: tok.kind,
      text: tok.text,
      position: pos,
      endPosition: endPos
    };
  });
  let innerGrid = GridIndex.make(adjusted);
  let innerCtx = {
    blockType: ctx.blockType,
    blockSlug: ctx.blockSlug,
    props: ctx.props,
    containerDepth: ctx.containerDepth,
    errors: [],
    warnings: [],
    heuristics: ctx.heuristics,
    tokens: adjusted,
    gridIndex: innerGrid,
    source: ctx.source,
    maxDepth: ctx.maxDepth,
    tabSize: ctx.tabSize,
    containerStack: ctx.containerStack,
    pendingNestedBlockRow: ctx.pendingNestedBlockRow,
    pendingNestedBlockBoundRow: ctx.pendingNestedBlockBoundRow,
    pendingNestedBlockWallCols: ctx.pendingNestedBlockWallCols,
    emojiRegistry: ctx.emojiRegistry,
    parseBoundRow: ctx.parseBoundRow,
    wallCols: ctx.wallCols
  };
  let stream = TokenStream.make(adjusted);
  let result = [];
  let keep = true;
  let isNestedBlockHeader = () => {
    let a = TokenStream.peek(stream);
    let b = TokenStream.peekAt(stream, 1);
    let c = TokenStream.peekAt(stream, 2);
    let match = a.kind;
    let match$1 = b.kind;
    let match$2 = c.kind;
    if (typeof match !== "object" && match === "At" && typeof match$1 !== "object" && match$1 === "Identifier" && typeof match$2 !== "object" && match$2 === "Colon") {
      if (b.text === "scene") {
        return true;
      } else {
        return b.text === "component";
      }
    } else {
      return false;
    }
  };
  while (keep && !TokenStream.isAtEnd(stream)) {
    let tok = TokenStream.peek(stream);
    let match = tok.kind;
    let exit = 0;
    if (typeof match !== "object") {
      switch (match) {
        case "At" :
          if (isNestedBlockHeader()) {
            ParseContext.addError(innerCtx, V2Errors.makeError("NestedBlockDeclaration", {
              start: tok.position,
              end_: tok.endPosition
            }, true, undefined));
            let match$1 = ctx.pendingNestedBlockRow;
            if (match$1 !== undefined) {
              
            } else {
              ctx.pendingNestedBlockRow = tok.position.row;
              ctx.pendingNestedBlockBoundRow = bottomRow;
              ctx.pendingNestedBlockWallCols = [
                lc,
                rc
              ];
            }
            keep = false;
          } else {
            exit = 1;
          }
          break;
        case "Newline" :
          TokenStream.next(stream);
          break;
        case "EOF" :
          keep = false;
          break;
        default:
          exit = 1;
      }
    } else if (match.TAG === "Whitespace") {
      TokenStream.next(stream);
    } else {
      exit = 1;
    }
    if (exit === 1) {
      let node = V2ParserRegistry.tryParse(reg, innerCtx, stream);
      if (node !== undefined) {
        result.push(node);
      } else {
        TokenStream.next(stream);
      }
    }
  };
  innerCtx.errors.forEach(e => ParseContext.addError(ctx, e));
  innerCtx.warnings.forEach(w => ParseContext.addWarning(ctx, w));
  return result;
}

function extractFormat2(ctx, children) {
  let out = [];
  children.forEach(node => {
    if (node.TAG !== "TextNode") {
      return;
    }
    let t = node._0;
    let c = t.content.trim();
    if (!(c.length > 1 && c.charAt(0) === "#")) {
      return;
    }
    let rest = c.slice(1, c.length);
    let hasWhitespace = false;
    let i = 0;
    let restLen = rest.length;
    while (i < restLen && !hasWhitespace) {
      let ch = rest.charAt(i);
      if (ch === " " || ch === "\t" || ch === "\r") {
        hasWhitespace = true;
      }
      i = i + 1 | 0;
    };
    if (hasWhitespace) {
      return ParseContext.addError(ctx, V2Errors.makeError("InvalidIdFormat", t.location, undefined, undefined));
    } else {
      out.push([
        rest,
        t.location
      ]);
      return;
    }
  });
  return out;
}

function parse(ctx, stream) {
  let match = detectTopBorder(stream);
  if (match === undefined) {
    return;
  }
  let format1Id = match[3];
  let rc = match[1];
  let lc = match[0];
  let topTok = TokenStream.peek(stream);
  let topRow = topTok.position.row;
  let match$1 = findBottomRow(ctx, topRow, lc, rc);
  let bottomRow = match$1[0];
  if (bottomRow < 0) {
    let startPos = topTok.position;
    let lines = splitLines(ctx.source);
    let endRowRef = topRow;
    consumeRow(stream);
    let isSyncRow = line => {
      let trimmed = line.trim();
      if (trimmed === "" || trimmed.startsWith("+") || trimmed.startsWith("@scene:")) {
        return true;
      } else {
        return trimmed.startsWith("@component:");
      }
    };
    let keepRec = true;
    while (keepRec) {
      let nextRow = endRowRef + 1 | 0;
      let line = Core__Option.getOr(lines[nextRow], "");
      if (nextRow >= lines.length || isSyncRow(line)) {
        keepRec = false;
      } else {
        consumeRow(stream);
        endRowRef = nextRow;
      }
    };
    let endRowPos = TokenStream.position(stream);
    let loc = {
      start: startPos,
      end_: endRowPos
    };
    ParseContext.addError(ctx, V2Errors.makeError("UnclosedContainer", loc, undefined, undefined));
    let recoveredRows = [];
    let i = topRow;
    while (i <= endRowRef) {
      recoveredRows.push(Core__Option.getOr(lines[i], ""));
      i = i + 1 | 0;
    };
    let errNode_message = V2Errors.getErrorMessage("UnclosedContainer");
    let errNode_recoveredContent = recoveredRows.join("\n");
    let errNode = {
      location: loc,
      message: errNode_message,
      recoveredContent: errNode_recoveredContent
    };
    return {
      TAG: "ErrorNode",
      _0: errNode
    };
  }
  let endLineCount = (bottomRow - topRow | 0) + 1 | 0;
  let i$1 = 0;
  while (i$1 < endLineCount) {
    consumeRow(stream);
    i$1 = i$1 + 1 | 0;
  };
  let bounds_width = (rc - lc | 0) + 1 | 0;
  let bounds_height = (bottomRow - topRow | 0) + 1 | 0;
  let bounds = {
    x: lc,
    y: topRow,
    width: bounds_width,
    height: bounds_height
  };
  if (match$1[1]) {
    ParseContext.addWarning(ctx, V2Errors.makeWarning("MisalignedContainerCorner", {
      start: topTok.position,
      end_: topTok.endPosition
    }, Heuristics.Rule.containerCornerAlignment, undefined));
  }
  if (match$1[2]) {
    ParseContext.addWarning(ctx, V2Errors.makeWarning("MisalignedContainerWall", {
      start: topTok.position,
      end_: topTok.endPosition
    }, Heuristics.Rule.containerWallAlignment, undefined));
  }
  if (match$1[3]) {
    ParseContext.addWarning(ctx, V2Errors.makeWarning("InconsistentContainerWidth", {
      start: topTok.position,
      end_: topTok.endPosition
    }, Heuristics.Rule.containerWidthConsistency, undefined));
  }
  let canDescend = ParseContext.enterContainer(ctx, bounds);
  let children;
  if (canDescend) {
    let inner = extractInnerSource(ctx, topRow, bottomRow, lc, rc);
    let ch = parseInnerContent(ctx, inner, lc, rc, topRow, bottomRow);
    ParseContext.exitContainer(ctx);
    children = ch;
  } else {
    ParseContext.addError(ctx, V2Errors.makeError("MaxDepthExceeded", {
      start: topTok.position,
      end_: topTok.position
    }, true, undefined));
    children = [];
  }
  let errorsBefore = ctx.errors.length;
  let format2 = extractFormat2(ctx, children);
  let recoveredFromIds = ctx.errors.length > errorsBefore;
  let match$2 = format2.length;
  let match$3;
  if (format1Id !== undefined) {
    match$3 = [
      format1Id,
      children
    ];
  } else if (match$2 !== 0) {
    if (match$2 !== 1) {
      let match$4 = format2[0];
      ParseContext.addError(ctx, V2Errors.makeError("MultipleIdDeclarations", {
        start: topTok.position,
        end_: topTok.position
      }, undefined, undefined));
      recoveredFromIds = true;
      match$3 = [
        match$4[0],
        children
      ];
    } else {
      let match$5 = format2[0];
      let id2 = match$5[0];
      let filtered = children.filter(n => {
        if (n.TAG !== "TextNode") {
          return true;
        }
        let c = n._0.content.trim();
        return c !== `#` + id2;
      });
      match$3 = [
        id2,
        filtered
      ];
    }
  } else {
    match$3 = [
      undefined,
      children
    ];
  }
  let finalChildren = match$3[1];
  let layout = LayoutInferrer.inferLayout(finalChildren, Primitive_option.some(bounds), undefined);
  let lines$1 = splitLines(ctx.source);
  let offsetTable = rowStartOffsets(ctx.source);
  let off = Core__Option.getOr(offsetTable[bottomRow], ctx.source.length);
  let bottomLine = Core__Option.getOr(lines$1[bottomRow], "");
  let n = bottomLine.length;
  let bi = 0;
  let col = 0;
  let target = rc + 1 | 0;
  let keep = true;
  while (keep && bi < n && col < target) {
    let cp = Core__Option.getOr(bottomLine.codePointAt(bi), 32);
    let cuLen = cp > 65535 ? 2 : 1;
    if (cp === 9) {
      col = (Primitive_int.div(col, ctx.tabSize) + 1 | 0) * ctx.tabSize | 0;
    } else if (!UnicodeUtils.isCombining(cp)) {
      col = UnicodeUtils.isWide(cp) ? col + 2 | 0 : col + 1 | 0;
    }
    bi = bi + cuLen | 0;
    if (col >= target) {
      keep = false;
    }
  };
  let endOffset = off + bi | 0;
  let node_location = {
    start: topTok.position,
    end_: {
      row: bottomRow,
      col: rc + 1 | 0,
      offset: endOffset
    }
  };
  let node_id = match$3[0];
  let node_name = match[2];
  let node_containsErrorRecovery = !canDescend || recoveredFromIds;
  let node = {
    location: node_location,
    id: node_id,
    name: node_name,
    children: finalChildren,
    layout: layout,
    bounds: bounds,
    containsErrorRecovery: node_containsErrorRecovery
  };
  return {
    TAG: "ContainerNode",
    _0: node
  };
}

function make() {
  return V2ElementParser.make("Container", Priority.container, canParse, parse);
}

let priority = Priority.container;

export {
  priority,
  splitLines,
  rowStartOffsets,
  detectTopBorder,
  canParse,
  consumeRow,
  isBottomBorderRow,
  wallAt,
  bodyRowWalls,
  bottomCornerCols,
  findBottomRow,
  extractInnerSource,
  registryHolder,
  setRegistry,
  getRegistry,
  parseInnerContent,
  extractFormat2,
  parse,
  make,
}
/* No side effect */
