// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Priority from "../parser/Priority.mjs";
import * as V2Errors from "../types/V2Errors.mjs";
import * as TokenStream from "../lexer/TokenStream.mjs";
import * as ParseContext from "../parser/ParseContext.mjs";
import * as V2ElementParser from "./V2ElementParser.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function isLineOnly(stream, kind) {
  let snap = TokenStream.save(stream);
  let result = false;
  let tok = TokenStream.peek(stream);
  if (Primitive_object.equal(tok.kind, kind)) {
    TokenStream.next(stream);
    let next = TokenStream.peek(stream);
    let match = next.kind;
    if (typeof match !== "object") {
      switch (match) {
        case "Newline" :
        case "EOF" :
          result = true;
          break;
      }
    }
  }
  TokenStream.restore(stream, snap);
  return result;
}

function canParse(stream) {
  let tok = TokenStream.peek(stream);
  let match = tok.kind;
  if (typeof match !== "object") {
    return false;
  }
  switch (match.TAG) {
    case "Dashes" :
    case "Equals" :
      return match._0 >= 1;
    default:
      return false;
  }
}

function collectRow(stream) {
  let s = "";
  let endPos = TokenStream.peek(stream).position;
  let keep = true;
  while (keep) {
    let tok = TokenStream.peek(stream);
    let match = tok.kind;
    let exit = 0;
    if (typeof match !== "object") {
      switch (match) {
        case "Newline" :
        case "EOF" :
          keep = false;
          break;
        default:
          exit = 1;
      }
    } else {
      exit = 1;
    }
    if (exit === 1) {
      s = s + tok.text;
      endPos = tok.endPosition;
      TokenStream.next(stream);
    }
  };
  return [
    s,
    endPos
  ];
}

function parse(ctx, stream) {
  let tok = TokenStream.peek(stream);
  let match = tok.kind;
  let bold;
  bold = typeof match !== "object" ? false : match.TAG === "Equals";
  let style = bold ? "Bold" : "Normal";
  let startPos = tok.position;
  let match$1 = collectRow(stream);
  let trimmed = match$1[0].trim();
  let location_end_ = match$1[1];
  let location = {
    start: startPos,
    end_: location_end_
  };
  let stripRun = (s, ch) => {
    let n = s.length;
    let i = 0;
    while (i < n && s.charAt(i) === ch) {
      i = i + 1 | 0;
    };
    let j = n;
    while (j > i && s.charAt(j - 1 | 0) === ch) {
      j = j - 1 | 0;
    };
    return s.slice(i, j);
  };
  let stripped = stripRun(trimmed, bold ? "=" : "-");
  let middle = stripped.trim();
  let hasLeading = trimmed.length > 0 && trimmed.charAt(0) === (
    bold ? "=" : "-"
  );
  let hasTrailing = trimmed.length > 0 && trimmed.charAt(trimmed.length - 1 | 0) === (
    bold ? "=" : "-"
  );
  if (middle !== "" && (!hasLeading || !hasTrailing)) {
    return;
  }
  if (middle === "") {
    if (trimmed.length < ctx.heuristics.dividerMinRun) {
      return;
    }
    let node = {
      location: location,
      style: style,
      id: undefined,
      label: undefined
    };
    return {
      TAG: "DividerNode",
      _0: node
    };
  }
  let isIdOnly = middle.length > 1 && middle.charAt(0) === "#" && !middle.includes(" ");
  let hasHashInside = middle.includes("#");
  if (isIdOnly) {
    let id = middle.slice(1, middle.length);
    let node_id = id;
    let node$1 = {
      location: location,
      style: style,
      id: node_id,
      label: undefined
    };
    return {
      TAG: "DividerNode",
      _0: node$1
    };
  }
  if (hasHashInside) {
    ParseContext.addWarning(ctx, V2Errors.makeWarning("MixedDividerLabelId", location, undefined, undefined));
    let node$2 = {
      location: location,
      content: trimmed,
      align: "Left"
    };
    return {
      TAG: "TextNode",
      _0: node$2
    };
  }
  let node_label = middle;
  let node$3 = {
    location: location,
    style: style,
    id: undefined,
    label: node_label
  };
  return {
    TAG: "DividerNode",
    _0: node$3
  };
}

function make() {
  return V2ElementParser.make("Divider", Priority.dividerLabeledBold, canParse, parse);
}

let priority = Priority.dividerLabeledBold;

export {
  priority,
  isLineOnly,
  canParse,
  collectRow,
  parse,
  make,
}
/* No side effect */
