// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Priority from "../parser/Priority.mjs";
import * as V2Errors from "../types/V2Errors.mjs";
import * as TokenStream from "../lexer/TokenStream.mjs";
import * as ParseContext from "../parser/ParseContext.mjs";
import * as EmojiRegistry from "../registry/EmojiRegistry.mjs";
import * as V2ElementParser from "./V2ElementParser.mjs";

function canParse(stream) {
  let c1 = TokenStream.peek(stream);
  let name = TokenStream.peekAt(stream, 1);
  let c2 = TokenStream.peekAt(stream, 2);
  let match = c1.kind;
  let match$1 = name.kind;
  let match$2 = c2.kind;
  if (typeof match !== "object" && match === "Colon" && typeof match$1 !== "object" && match$1 === "Identifier" && typeof match$2 !== "object" && match$2 === "Colon") {
    return c1.position.row === c2.position.row;
  } else {
    return false;
  }
}

function parse(ctx, stream) {
  let c1 = TokenStream.peek(stream);
  let name = TokenStream.peekAt(stream, 1);
  let c2 = TokenStream.peekAt(stream, 2);
  let match = c1.kind;
  let match$1 = name.kind;
  let match$2 = c2.kind;
  if (typeof match === "object") {
    return;
  }
  if (match !== "Colon") {
    return;
  }
  if (typeof match$1 === "object") {
    return;
  }
  if (match$1 !== "Identifier") {
    return;
  }
  if (typeof match$2 === "object") {
    return;
  }
  if (match$2 !== "Colon") {
    return;
  }
  TokenStream.next(stream);
  TokenStream.next(stream);
  TokenStream.next(stream);
  let location_start = c1.position;
  let location_end_ = c2.endPosition;
  let location = {
    start: location_start,
    end_: location_end_
  };
  let resolved = EmojiRegistry.lookupWithOverride(ctx.emojiRegistry, name.text);
  let emojiStr = resolved !== undefined ? resolved : (ParseContext.addWarning(ctx, V2Errors.makeWarning({
      TAG: "UnknownEmoji",
      _0: name.text
    }, location, undefined, undefined)), `:` + name.text + `:`);
  let node_shortcode = name.text;
  let node = {
    location: location,
    shortcode: node_shortcode,
    emoji: emojiStr
  };
  return {
    TAG: "EmojiNode",
    _0: node
  };
}

function make() {
  return V2ElementParser.make("Emoji", Priority.emoji, canParse, parse);
}

let priority = Priority.emoji;

export {
  priority,
  canParse,
  parse,
  make,
}
/* EmojiRegistry Not a pure module */
