// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Priority from "../parser/Priority.mjs";
import * as V2Errors from "../types/V2Errors.mjs";
import * as TokenStream from "../lexer/TokenStream.mjs";
import * as ParseContext from "../parser/ParseContext.mjs";
import * as V2ElementParser from "./V2ElementParser.mjs";

function canParse(stream) {
  let d = TokenStream.peek(stream);
  let lb = TokenStream.peekAt(stream, 1);
  let match = d.kind;
  let match$1 = lb.kind;
  if (typeof match !== "object" && match === "Dollar" && typeof match$1 !== "object") {
    return match$1 === "LBrace";
  } else {
    return false;
  }
}

function parse(ctx, stream) {
  let d = TokenStream.peek(stream);
  let match = d.kind;
  if (typeof match === "object") {
    return;
  }
  if (match !== "Dollar") {
    return;
  }
  let startPos = d.position;
  TokenStream.next(stream);
  TokenStream.next(stream);
  let inner = "";
  let endPos = startPos;
  let closed = false;
  let keep = true;
  while (keep) {
    let tok = TokenStream.peek(stream);
    let match$1 = tok.kind;
    let exit = 0;
    if (typeof match$1 !== "object") {
      switch (match$1) {
        case "RBrace" :
          endPos = tok.endPosition;
          TokenStream.next(stream);
          closed = true;
          keep = false;
          break;
        case "Newline" :
        case "EOF" :
          keep = false;
          break;
        default:
          exit = 1;
      }
    } else {
      exit = 1;
    }
    if (exit === 1) {
      inner = inner + tok.text;
      TokenStream.next(stream);
    }
  };
  if (!closed) {
    return;
  }
  let raw = inner.trim();
  let colonIdx = raw.indexOf(":");
  let match$2 = colonIdx >= 0 ? [
      raw.slice(0, colonIdx).trim(),
      true,
      raw.slice(colonIdx + 1 | 0, raw.length).trim()
    ] : (
      raw.endsWith("?") ? [
          raw.slice(0, raw.length - 1 | 0),
          false,
          undefined
        ] : [
          raw,
          true,
          undefined
        ]
    );
  let defaultValue = match$2[2];
  let required = match$2[1];
  let name = match$2[0];
  let location = {
    start: startPos,
    end_: endPos
  };
  if (ParseContext.isInComponent(ctx)) {
    let node = {
      location: location,
      name: name,
      required: required,
      defaultValue: defaultValue
    };
    return {
      TAG: "PropPlaceholderNode",
      _0: node
    };
  }
  ParseContext.addWarning(ctx, V2Errors.makeWarning("PropOutsideComponent", location, undefined, undefined));
  let textNode_content = "${" + raw + "}";
  let textNode = {
    location: location,
    content: textNode_content,
    align: "Left"
  };
  return {
    TAG: "TextNode",
    _0: textNode
  };
}

function make() {
  return V2ElementParser.make("PropPlaceholder", Priority.propPlaceholder, canParse, parse);
}

let priority = Priority.propPlaceholder;

export {
  priority,
  canParse,
  parse,
  make,
}
/* No side effect */
