// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Priority from "../parser/Priority.mjs";
import * as V2Errors from "../types/V2Errors.mjs";
import * as TokenStream from "../lexer/TokenStream.mjs";
import * as ParseContext from "../parser/ParseContext.mjs";
import * as V2ElementParser from "./V2ElementParser.mjs";

function canParse(stream) {
  let lp = TokenStream.peek(stream);
  let mid = TokenStream.peekAt(stream, 1);
  let rp = TokenStream.peekAt(stream, 2);
  let match = lp.kind;
  let match$1 = mid.kind;
  let match$2 = rp.kind;
  if (typeof match !== "object" && match === "LParen") {
    if (typeof match$1 !== "object") {
      if (match$1 === "Asterisk" && typeof match$2 !== "object") {
        return match$2 === "RParen";
      } else {
        return false;
      }
    } else if (match$1.TAG === "Whitespace" && typeof match$2 !== "object" && match$2 === "RParen") {
      return match$1._0 === 1;
    } else {
      return false;
    }
  } else {
    return false;
  }
}

function parse(ctx, stream) {
  let lp = TokenStream.peek(stream);
  let mid = TokenStream.peekAt(stream, 1);
  let rp = TokenStream.peekAt(stream, 2);
  let match = mid.kind;
  let selected;
  selected = typeof match !== "object" ? match === "Asterisk" : false;
  let match$1 = lp.kind;
  let match$2 = rp.kind;
  if (typeof match$1 === "object") {
    return;
  }
  if (match$1 !== "LParen") {
    return;
  }
  if (typeof match$2 === "object") {
    return;
  }
  if (match$2 !== "RParen") {
    return;
  }
  let startPos = lp.position;
  TokenStream.next(stream);
  TokenStream.next(stream);
  TokenStream.next(stream);
  TokenStream.skipInlineWhitespace(stream);
  let labelRef = "";
  let endPosRef = rp.endPosition;
  let keep = true;
  let isNextRadioMarker = () => {
    let a = TokenStream.peek(stream);
    let b = TokenStream.peekAt(stream, 1);
    let c = TokenStream.peekAt(stream, 2);
    let match = a.kind;
    let match$1 = b.kind;
    let match$2 = c.kind;
    if (typeof match !== "object" && match === "LParen") {
      if (typeof match$1 !== "object") {
        if (match$1 === "Asterisk" && typeof match$2 !== "object") {
          return match$2 === "RParen";
        } else {
          return false;
        }
      } else if (match$1.TAG === "Whitespace" && typeof match$2 !== "object" && match$2 === "RParen") {
        return match$1._0 === 1;
      } else {
        return false;
      }
    } else {
      return false;
    }
  };
  while (keep) {
    let tok = TokenStream.peek(stream);
    let match$3 = tok.kind;
    let exit = 0;
    if (typeof match$3 !== "object") {
      switch (match$3) {
        case "LParen" :
          if (isNextRadioMarker()) {
            keep = false;
          } else {
            exit = 1;
          }
          break;
        case "Pipe" :
        case "Newline" :
        case "EOF" :
          keep = false;
          break;
        default:
          exit = 1;
      }
    } else if (match$3.TAG === "Whitespace") {
      labelRef = labelRef + tok.text;
      TokenStream.next(stream);
    } else {
      exit = 1;
    }
    if (exit === 1) {
      labelRef = labelRef + tok.text;
      endPosRef = tok.endPosition;
      TokenStream.next(stream);
    }
  };
  let label = labelRef.trim();
  if (label === "") {
    ParseContext.addWarning(ctx, V2Errors.makeWarning("MissingRadioLabel", {
      start: startPos,
      end_: endPosRef
    }, undefined, undefined));
  }
  let node_location = {
    start: startPos,
    end_: endPosRef
  };
  let node = {
    location: node_location,
    selected: selected,
    label: label,
    group: undefined
  };
  return {
    TAG: "RadioNode",
    _0: node
  };
}

function make() {
  return V2ElementParser.make("Radio", Priority.radio, canParse, parse);
}

let priority = Priority.radio;

export {
  priority,
  canParse,
  parse,
  make,
}
/* No side effect */
