// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Slugify from "../utils/Slugify.mjs";
import * as Priority from "../parser/Priority.mjs";
import * as TokenStream from "../lexer/TokenStream.mjs";
import * as V2ElementParser from "./V2ElementParser.mjs";

function canParse(stream) {
  let lb = TokenStream.peek(stream);
  let id = TokenStream.peekAt(stream, 1);
  let colon = TokenStream.peekAt(stream, 2);
  let match = lb.kind;
  let match$1 = id.kind;
  let match$2 = colon.kind;
  if (typeof match !== "object" && match === "LBracket" && typeof match$1 !== "object" && match$1 === "Identifier" && typeof match$2 !== "object" && match$2 === "Colon" && (id.text === "v" || id.text === "V")) {
    return TokenStream.findOnCurrentRow(stream, t => {
      let match = t.kind;
      if (typeof match !== "object") {
        return match === "RBracket";
      } else {
        return false;
      }
    }) !== undefined;
  } else {
    return false;
  }
}

function parse(_ctx, stream) {
  let lb = TokenStream.peek(stream);
  let match = lb.kind;
  if (typeof match === "object") {
    return;
  }
  if (match !== "LBracket") {
    return;
  }
  let startPos = lb.position;
  TokenStream.next(stream);
  TokenStream.next(stream);
  TokenStream.next(stream);
  let inner = "";
  let endPosRef = startPos;
  let keep = true;
  while (keep) {
    let tok = TokenStream.peek(stream);
    let match$1 = tok.kind;
    let exit = 0;
    if (typeof match$1 !== "object") {
      switch (match$1) {
        case "RBracket" :
          endPosRef = tok.endPosition;
          TokenStream.next(stream);
          keep = false;
          break;
        case "Newline" :
        case "EOF" :
          keep = false;
          break;
        default:
          exit = 1;
      }
    } else {
      exit = 1;
    }
    if (exit === 1) {
      inner = inner + tok.text;
      TokenStream.next(stream);
    }
  };
  let placeholder = inner.trim();
  let id = Slugify.slugify(placeholder === "" ? "select" : placeholder);
  let node_location = {
    start: startPos,
    end_: endPosRef
  };
  let node = {
    location: node_location,
    id: id,
    placeholder: placeholder
  };
  return {
    TAG: "SelectNode",
    _0: node
  };
}

function make() {
  return V2ElementParser.make("Select", Priority.select, canParse, parse);
}

let priority = Priority.select;

export {
  priority,
  canParse,
  parse,
  make,
}
/* No side effect */
