// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Priority from "../parser/Priority.mjs";
import * as V2Errors from "../types/V2Errors.mjs";
import * as TokenStream from "../lexer/TokenStream.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as ParseContext from "../parser/ParseContext.mjs";
import * as EmojiRegistry from "../registry/EmojiRegistry.mjs";
import * as V2ElementParser from "./V2ElementParser.mjs";

function canParse(stream) {
  let match = TokenStream.peek(stream).kind;
  if (typeof match !== "object") {
    return match === "Quote";
  } else {
    return false;
  }
}

function parseInner(ctx, stream) {
  let content = {
    contents: ""
  };
  let buf = {
    contents: ""
  };
  let parts = [];
  let multiline = false;
  let closed = false;
  let endPos = TokenStream.peek(stream).position;
  let keep = true;
  let append = s => {
    content.contents = content.contents + s;
    buf.contents = buf.contents + s;
  };
  let pushLiteral = () => {
    if (buf.contents !== "") {
      parts.push({
        TAG: "Literal",
        _0: buf.contents
      });
      buf.contents = "";
      return;
    }
  };
  while (keep) {
    let tok = TokenStream.peek(stream);
    let match = tok.kind;
    let exit = 0;
    if (typeof match !== "object") {
      switch (match) {
        case "Colon" :
          let nameTok = TokenStream.peekAt(stream, 1);
          let closeTok = TokenStream.peekAt(stream, 2);
          let match$1 = nameTok.kind;
          let match$2 = closeTok.kind;
          let exit$1 = 0;
          if (typeof match$1 !== "object" && match$1 === "Identifier" && typeof match$2 !== "object" && match$2 === "Colon") {
            let resolved = EmojiRegistry.lookupWithOverride(ctx.emojiRegistry, nameTok.text);
            let emojiNode_location = {
              start: tok.position,
              end_: closeTok.endPosition
            };
            let emojiNode_shortcode = nameTok.text;
            let emojiNode_emoji = Core__Option.getOr(resolved, `:` + nameTok.text + `:`);
            let emojiNode = {
              location: emojiNode_location,
              shortcode: emojiNode_shortcode,
              emoji: emojiNode_emoji
            };
            pushLiteral();
            if (resolved !== undefined) {
              content.contents = content.contents + resolved;
            } else {
              ParseContext.addWarning(ctx, V2Errors.makeWarning({
                TAG: "UnknownEmoji",
                _0: nameTok.text
              }, emojiNode_location, undefined, undefined));
              content.contents = content.contents + (`:` + nameTok.text + `:`);
            }
            parts.push({
              TAG: "EmojiRef",
              _0: emojiNode
            });
            endPos = closeTok.endPosition;
            TokenStream.next(stream);
            TokenStream.next(stream);
            TokenStream.next(stream);
          } else {
            exit$1 = 2;
          }
          if (exit$1 === 2) {
            append(":");
            endPos = tok.endPosition;
            TokenStream.next(stream);
          }
          break;
        case "Dollar" :
          let next = TokenStream.peekAt(stream, 1);
          let match$3 = next.kind;
          let exit$2 = 0;
          if (typeof match$3 !== "object" && match$3 === "LBrace") {
            let snap = TokenStream.save(stream);
            TokenStream.next(stream);
            TokenStream.next(stream);
            let inner = "";
            let foundClose = false;
            let propEnd = tok.position;
            let k = true;
            while (k) {
              let t = TokenStream.peek(stream);
              let match$4 = t.kind;
              let exit$3 = 0;
              if (typeof match$4 !== "object") {
                switch (match$4) {
                  case "RBrace" :
                    propEnd = t.endPosition;
                    TokenStream.next(stream);
                    foundClose = true;
                    k = false;
                    break;
                  case "Quote" :
                  case "Newline" :
                  case "EOF" :
                    k = false;
                    break;
                  default:
                    exit$3 = 3;
                }
              } else {
                exit$3 = 3;
              }
              if (exit$3 === 3) {
                inner = inner + t.text;
                TokenStream.next(stream);
              }
            };
            if (foundClose) {
              endPos = propEnd;
              let raw = inner.trim();
              let colonIdx = raw.indexOf(":");
              let match$5 = colonIdx >= 0 ? [
                  raw.slice(0, colonIdx).trim(),
                  true,
                  raw.slice(colonIdx + 1 | 0, raw.length).trim()
                ] : (
                  raw.endsWith("?") ? [
                      raw.slice(0, raw.length - 1 | 0),
                      false,
                      undefined
                    ] : [
                      raw,
                      true,
                      undefined
                    ]
                );
              let propNode_location = {
                start: tok.position,
                end_: propEnd
              };
              let propNode_name = match$5[0];
              let propNode_required = match$5[1];
              let propNode_defaultValue = match$5[2];
              let propNode = {
                location: propNode_location,
                name: propNode_name,
                required: propNode_required,
                defaultValue: propNode_defaultValue
              };
              if (ParseContext.isInComponent(ctx)) {
                pushLiteral();
                content.contents = content.contents + "${" + raw + "}";
                parts.push({
                  TAG: "PropRef",
                  _0: propNode
                });
              } else {
                ParseContext.addWarning(ctx, V2Errors.makeWarning("PropOutsideComponent", propNode_location, undefined, undefined));
                append("${" + raw + "}");
              }
            } else {
              TokenStream.restore(stream, snap);
              append("$");
              endPos = tok.endPosition;
              TokenStream.next(stream);
            }
          } else {
            exit$2 = 2;
          }
          if (exit$2 === 2) {
            append("$");
            endPos = tok.endPosition;
            TokenStream.next(stream);
          }
          break;
        case "Quote" :
          endPos = tok.endPosition;
          TokenStream.next(stream);
          pushLiteral();
          closed = true;
          keep = false;
          break;
        case "Newline" :
          append("\n");
          endPos = tok.endPosition;
          multiline = true;
          TokenStream.next(stream);
          break;
        case "EOF" :
          keep = false;
          break;
        default:
          exit = 1;
      }
    } else {
      exit = 1;
    }
    if (exit === 1) {
      let text = tok.text;
      endPos = tok.endPosition;
      if (text === "\\") {
        let nextTok = TokenStream.peekAt(stream, 1);
        let nc = nextTok.text;
        let decoded;
        switch (nc) {
          case "$" :
            decoded = "$";
            break;
          case "\"" :
            decoded = "\"";
            break;
          case "\\" :
            decoded = "\\";
            break;
          default:
            decoded = undefined;
        }
        if (decoded !== undefined) {
          append(decoded);
          TokenStream.next(stream);
          endPos = nextTok.endPosition;
          TokenStream.next(stream);
        } else {
          append(text);
          TokenStream.next(stream);
        }
      } else {
        append(text);
        TokenStream.next(stream);
      }
    }
  };
  pushLiteral();
  return [
    content.contents,
    parts,
    endPos,
    multiline,
    closed
  ];
}

function parse(ctx, stream) {
  let q = TokenStream.peek(stream);
  let match = q.kind;
  if (typeof match === "object") {
    return;
  }
  if (match !== "Quote") {
    return;
  }
  let startPos = q.position;
  TokenStream.next(stream);
  let match$1 = parseInner(ctx, stream);
  let endPos = match$1[2];
  let content = match$1[0];
  if (match$1[4]) {
    let node_location = {
      start: startPos,
      end_: endPos
    };
    let node_interpolations = match$1[1];
    let node_multiline = match$1[3];
    let node = {
      location: node_location,
      content: content,
      interpolations: node_interpolations,
      multiline: node_multiline
    };
    return {
      TAG: "StringNode",
      _0: node
    };
  }
  let loc = {
    start: startPos,
    end_: endPos
  };
  ParseContext.addError(ctx, V2Errors.makeError("UnclosedString", loc, undefined, undefined));
  let errNode_message = V2Errors.getErrorMessage("UnclosedString");
  let errNode_recoveredContent = "\"" + content;
  let errNode = {
    location: loc,
    message: errNode_message,
    recoveredContent: errNode_recoveredContent
  };
  return {
    TAG: "ErrorNode",
    _0: errNode
  };
}

function make() {
  return V2ElementParser.make("String", Priority.string, canParse, parse);
}

let priority = Priority.string;

export {
  priority,
  canParse,
  parseInner,
  parse,
  make,
}
/* EmojiRegistry Not a pure module */
