// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Slugify from "../utils/Slugify.mjs";
import * as Priority from "../parser/Priority.mjs";
import * as TokenStream from "../lexer/TokenStream.mjs";
import * as V2ElementParser from "./V2ElementParser.mjs";

function canParse(stream) {
  let tok = TokenStream.peek(stream);
  let match = tok.kind;
  if (typeof match !== "object" && match === "LBracket") {
    return TokenStream.findOnCurrentRow(stream, t => {
      let match = t.kind;
      if (typeof match !== "object") {
        return match === "RBracket";
      } else {
        return false;
      }
    }) !== undefined;
  } else {
    return false;
  }
}

function parse(_ctx, stream) {
  let lb = TokenStream.peek(stream);
  let match = lb.kind;
  if (typeof match === "object") {
    return;
  }
  if (match !== "LBracket") {
    return;
  }
  let startPos = lb.position;
  TokenStream.next(stream);
  let textRef = "";
  let endPosRef = lb.endPosition;
  let keep = true;
  while (keep) {
    let tok = TokenStream.peek(stream);
    let match$1 = tok.kind;
    let exit = 0;
    if (typeof match$1 !== "object") {
      switch (match$1) {
        case "RBracket" :
          endPosRef = tok.endPosition;
          TokenStream.next(stream);
          keep = false;
          break;
        case "Newline" :
        case "EOF" :
          keep = false;
          break;
        default:
          exit = 1;
      }
    } else {
      exit = 1;
    }
    if (exit === 1) {
      textRef = textRef + tok.text;
      TokenStream.next(stream);
    }
  };
  let text = textRef.trim();
  let id = Slugify.slugify(text === "" ? "button" : text);
  let node_location = {
    start: startPos,
    end_: endPosRef
  };
  let node = {
    location: node_location,
    id: id,
    text: text
  };
  return {
    TAG: "ButtonNode",
    _0: node
  };
}

function make() {
  return V2ElementParser.make("Button", Priority.button, canParse, parse);
}

let priority = Priority.button;

export {
  priority,
  canParse,
  parse,
  make,
}
/* No side effect */
