// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Priority from "../parser/Priority.mjs";
import * as V2Errors from "../types/V2Errors.mjs";
import * as TokenStream from "../lexer/TokenStream.mjs";
import * as ParseContext from "../parser/ParseContext.mjs";
import * as V2ElementParser from "./V2ElementParser.mjs";

function isCheckMark(tok) {
  let w = tok.kind;
  if (typeof w !== "object") {
    if (w === "Identifier" && (tok.text === "x" || tok.text === "X" || tok.text === "v" || tok.text === "V")) {
      return true;
    } else {
      return;
    }
  } else if (w.TAG === "Whitespace" && w._0 === 1) {
    return false;
  } else {
    return;
  }
}

function canParse(stream) {
  let lb = TokenStream.peek(stream);
  let mid = TokenStream.peekAt(stream, 1);
  let rb = TokenStream.peekAt(stream, 2);
  let match = lb.kind;
  let match$1 = isCheckMark(mid);
  let match$2 = rb.kind;
  if (typeof match !== "object" && match === "LBracket" && match$1 !== undefined && typeof match$2 !== "object") {
    return match$2 === "RBracket";
  } else {
    return false;
  }
}

function parse(ctx, stream) {
  let lb = TokenStream.peek(stream);
  let mid = TokenStream.peekAt(stream, 1);
  let rb = TokenStream.peekAt(stream, 2);
  let match = lb.kind;
  let match$1 = isCheckMark(mid);
  let match$2 = rb.kind;
  if (typeof match === "object") {
    return;
  }
  if (match !== "LBracket") {
    return;
  }
  if (match$1 === undefined) {
    return;
  }
  if (typeof match$2 === "object") {
    return;
  }
  if (match$2 !== "RBracket") {
    return;
  }
  let startPos = lb.position;
  TokenStream.next(stream);
  TokenStream.next(stream);
  TokenStream.next(stream);
  TokenStream.skipInlineWhitespace(stream);
  let labelRef = "";
  let endPosRef = rb.endPosition;
  let keep = true;
  let isNextCheckboxMarker = () => {
    let a = TokenStream.peek(stream);
    let b = TokenStream.peekAt(stream, 1);
    let c = TokenStream.peekAt(stream, 2);
    let match = a.kind;
    let match$1 = isCheckMark(b);
    let match$2 = c.kind;
    if (typeof match !== "object" && match === "LBracket" && match$1 !== undefined && typeof match$2 !== "object") {
      return match$2 === "RBracket";
    } else {
      return false;
    }
  };
  while (keep) {
    let tok = TokenStream.peek(stream);
    let match$3 = tok.kind;
    let exit = 0;
    if (typeof match$3 !== "object") {
      switch (match$3) {
        case "LBracket" :
          if (isNextCheckboxMarker()) {
            keep = false;
          } else {
            exit = 1;
          }
          break;
        case "Pipe" :
        case "Newline" :
        case "EOF" :
          keep = false;
          break;
        default:
          exit = 1;
      }
    } else {
      exit = 1;
    }
    if (exit === 1) {
      labelRef = labelRef + tok.text;
      endPosRef = tok.endPosition;
      TokenStream.next(stream);
    }
  };
  let label = labelRef.trim();
  if (label === "") {
    ParseContext.addWarning(ctx, V2Errors.makeWarning("MissingCheckboxLabel", {
      start: startPos,
      end_: endPosRef
    }, undefined, undefined));
  }
  let node_location = {
    start: startPos,
    end_: endPosRef
  };
  let node = {
    location: node_location,
    checked: match$1,
    label: label
  };
  return {
    TAG: "CheckboxNode",
    _0: node
  };
}

function make() {
  return V2ElementParser.make("Checkbox", Priority.checkbox, canParse, parse);
}

let priority = Priority.checkbox;

export {
  priority,
  isCheckMark,
  canParse,
  parse,
  make,
}
/* No side effect */
