// Generated by ReScript, PLEASE EDIT WITH CARE


function make(elementType, priority, canParse, parse) {
  return {
    elementType: elementType,
    priority: priority,
    canParse: canParse,
    parse: parse
  };
}

export {
  make,
}
/* No side effect */
