// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Priority from "../parser/Priority.mjs";
import * as V2Errors from "../types/V2Errors.mjs";
import * as TokenStream from "../lexer/TokenStream.mjs";
import * as ParseContext from "../parser/ParseContext.mjs";
import * as V2ElementParser from "./V2ElementParser.mjs";

function canParse(stream) {
  let lb = TokenStream.peek(stream);
  let underscore = TokenStream.peekAt(stream, 1);
  let match = lb.kind;
  let match$1 = underscore.kind;
  if (typeof match !== "object" && match === "LBracket" && typeof match$1 === "object" && match$1.TAG === "Underscores") {
    return match$1._0 >= 2;
  } else {
    return false;
  }
}

function parse(ctx, stream) {
  let lb = TokenStream.peek(stream);
  let match = lb.kind;
  if (typeof match === "object") {
    return;
  }
  if (match !== "LBracket") {
    return;
  }
  let startPos = lb.position;
  TokenStream.next(stream);
  let opening = TokenStream.peek(stream);
  let n = opening.kind;
  let emptyShortCircuit;
  if (typeof n !== "object" || !(n.TAG === "Underscores" && n._0 >= 4)) {
    emptyShortCircuit = false;
  } else {
    let next = TokenStream.peekAt(stream, 1);
    let match$1 = next.kind;
    emptyShortCircuit = typeof match$1 !== "object" ? match$1 === "RBracket" : false;
  }
  let inner = "";
  let endPosRef = startPos;
  let keep = true;
  let closed = false;
  if (emptyShortCircuit) {
    let rb = TokenStream.peekAt(stream, 1);
    endPosRef = rb.endPosition;
    TokenStream.next(stream);
    TokenStream.next(stream);
    closed = true;
    keep = false;
  } else {
    let match$2 = opening.kind;
    if (typeof match$2 === "object" && match$2.TAG === "Underscores") {
      TokenStream.next(stream);
    }
  }
  while (keep) {
    let tok = TokenStream.peek(stream);
    let n$1 = tok.kind;
    let exit = 0;
    if (typeof n$1 !== "object") {
      switch (n$1) {
        case "Newline" :
        case "EOF" :
          keep = false;
          break;
        default:
          exit = 1;
      }
    } else if (n$1.TAG === "Underscores" && n$1._0 >= 2) {
      let next$1 = TokenStream.peekAt(stream, 1);
      let match$3 = next$1.kind;
      let exit$1 = 0;
      if (typeof match$3 !== "object" && match$3 === "RBracket") {
        endPosRef = next$1.endPosition;
        TokenStream.next(stream);
        TokenStream.next(stream);
        closed = true;
        keep = false;
      } else {
        exit$1 = 2;
      }
      if (exit$1 === 2) {
        inner = inner + tok.text;
        endPosRef = tok.endPosition;
        TokenStream.next(stream);
      }
    } else {
      exit = 1;
    }
    if (exit === 1) {
      inner = inner + tok.text;
      endPosRef = tok.endPosition;
      TokenStream.next(stream);
    }
  };
  if (closed) {
    let placeholder = inner.trim();
    let node_location = {
      start: startPos,
      end_: endPosRef
    };
    let node = {
      location: node_location,
      placeholder: placeholder
    };
    return {
      TAG: "InputNode",
      _0: node
    };
  }
  let loc = {
    start: startPos,
    end_: endPosRef
  };
  ParseContext.addError(ctx, V2Errors.makeError("UnclosedInput", loc, undefined, undefined));
  let recovered = "[__" + inner;
  let errNode_message = V2Errors.getErrorMessage("UnclosedInput");
  let errNode_recoveredContent = recovered;
  let errNode = {
    location: loc,
    message: errNode_message,
    recoveredContent: errNode_recoveredContent
  };
  return {
    TAG: "ErrorNode",
    _0: errNode
  };
}

function make() {
  return V2ElementParser.make("Input", Priority.input, canParse, parse);
}

let priority = Priority.input;

export {
  priority,
  canParse,
  parse,
  make,
}
/* No side effect */
