// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TokenStream from "../lexer/TokenStream.mjs";

function make() {
  return {
    parsers: []
  };
}

function register(reg, p) {
  let combined = reg.parsers.slice();
  combined.push(p);
  combined.sort((a, b) => b.priority - a.priority | 0);
  reg.parsers = combined;
}

function unregister(reg, et) {
  reg.parsers = reg.parsers.filter(p => p.elementType !== et);
}

function parsers(reg) {
  return reg.parsers;
}

function tryParse(reg, ctx, stream) {
  let found;
  let i = 0;
  let n = reg.parsers.length;
  while (found === undefined && i < n) {
    let p = reg.parsers[i];
    let snapshot = TokenStream.save(stream);
    if (p.canParse(stream)) {
      TokenStream.restore(stream, snapshot);
      let node = p.parse(ctx, stream);
      if (node !== undefined) {
        found = node;
      } else {
        TokenStream.restore(stream, snapshot);
      }
    } else {
      TokenStream.restore(stream, snapshot);
    }
    i = i + 1 | 0;
  };
  return found;
}

export {
  make,
  register,
  unregister,
  parsers,
  tryParse,
}
/* No side effect */
