// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Priority from "../parser/Priority.mjs";
import * as TokenStream from "../lexer/TokenStream.mjs";
import * as ParseContext from "../parser/ParseContext.mjs";
import * as V2ElementParser from "./V2ElementParser.mjs";

function canParse(_stream) {
  return true;
}

function determineAlignment(ctx, startCol, endCol) {
  let b = ParseContext.currentContainerBounds(ctx);
  if (b === undefined) {
    return "Left";
  }
  let innerLeft = b.x + 1 | 0;
  let innerRight = (b.x + b.width | 0) - 2 | 0;
  let w = (innerRight - innerLeft | 0) + 1 | 0;
  if (w <= 0.0) {
    return "Left";
  }
  let leftPad = startCol - innerLeft | 0;
  let rightPad = innerRight - (endCol - 1 | 0) | 0;
  let lp = leftPad < 0 ? 0 : leftPad;
  let rp = rightPad < 0 ? 0 : rightPad;
  if (lp < 2 && rp < 2) {
    return "Left";
  }
  let rpRatio = rp / w;
  let symRatio = Math.abs(lp - rp | 0) / w;
  if (rpRatio <= ctx.heuristics.rightAlignThreshold && lp > (rp << 1)) {
    return "Right";
  } else if (symRatio <= ctx.heuristics.centerSymmetryThreshold) {
    return "Center";
  } else {
    return "Left";
  }
}

function parse(ctx, stream) {
  let startTok = TokenStream.peek(stream);
  let match = startTok.kind;
  let exit = 0;
  if (typeof match !== "object") {
    switch (match) {
      case "Newline" :
      case "EOF" :
        return;
      default:
        exit = 1;
    }
  } else {
    exit = 1;
  }
  if (exit === 1) {
    let startPos = startTok.position;
    let endPosRef = startTok.endPosition;
    let textRef = "";
    let keep = true;
    let consumedAny = false;
    let isInlineElementStart = () => {
      let a = TokenStream.peek(stream);
      let b = TokenStream.peekAt(stream, 1);
      let c = TokenStream.peekAt(stream, 2);
      let match = a.kind;
      if (typeof match === "object") {
        return false;
      }
      switch (match) {
        case "LParen" :
          let match$1 = b.kind;
          let match$2 = c.kind;
          if (typeof match$1 !== "object") {
            if (match$1 === "Asterisk" && typeof match$2 !== "object") {
              return match$2 === "RParen";
            } else {
              return false;
            }
          } else if (match$1.TAG === "Whitespace" && typeof match$2 !== "object" && match$2 === "RParen") {
            return match$1._0 === 1;
          } else {
            return false;
          }
        case "Colon" :
          let match$3 = b.kind;
          let match$4 = c.kind;
          if (typeof match$3 !== "object" && match$3 === "Identifier" && typeof match$4 !== "object" && match$4 === "Colon") {
            return a.position.row === c.position.row;
          } else {
            return false;
          }
        case "Dollar" :
          let match$5 = b.kind;
          if (typeof match$5 !== "object") {
            return match$5 === "LBrace";
          } else {
            return false;
          }
        case "LBracket" :
        case "LAngle" :
        case "Quote" :
          return true;
        default:
          return false;
      }
    };
    let isWallPipe = tok => {
      let match = tok.kind;
      let match$1 = ctx.wallCols;
      if (typeof match === "object") {
        return false;
      }
      if (match !== "Pipe") {
        return false;
      }
      if (match$1 === undefined) {
        return false;
      }
      let tol = ctx.heuristics.containerColumnTolerance;
      let c = tok.position.col;
      let near = target => {
        if (c >= (target - tol | 0)) {
          return c <= (target + tol | 0);
        } else {
          return false;
        }
      };
      if (near(match$1[0])) {
        return true;
      } else {
        return near(match$1[1]);
      }
    };
    while (keep) {
      let tok = TokenStream.peek(stream);
      let match$1 = tok.kind;
      let exit$1 = 0;
      if (typeof match$1 !== "object") {
        switch (match$1) {
          case "Pipe" :
            if (isWallPipe(tok)) {
              keep = false;
            } else {
              exit$1 = 2;
            }
            break;
          case "Newline" :
          case "EOF" :
            keep = false;
            break;
          default:
            exit$1 = 2;
        }
      } else {
        exit$1 = 2;
      }
      if (exit$1 === 2) {
        if (consumedAny && isInlineElementStart()) {
          keep = false;
        } else {
          textRef = textRef + tok.text;
          endPosRef = tok.endPosition;
          TokenStream.next(stream);
          consumedAny = true;
        }
      }
    };
    let content = textRef.trim();
    if (content === "") {
      return;
    }
    let raw = textRef;
    let leadingSpaces = 0;
    let n = raw.length;
    let i = 0;
    let keep2 = true;
    while (keep2 && i < n) {
      let c = raw.charAt(i);
      if (c === " " || c === "\t") {
        leadingSpaces = leadingSpaces + 1 | 0;
        i = i + 1 | 0;
      } else {
        keep2 = false;
      }
    };
    let actualStartCol = startPos.col + leadingSpaces | 0;
    let trailing = 0;
    let j = n - 1 | 0;
    let keep3 = true;
    while (keep3 && j >= 0) {
      let c$1 = raw.charAt(j);
      if (c$1 === " " || c$1 === "\t") {
        trailing = trailing + 1 | 0;
        j = j - 1 | 0;
      } else {
        keep3 = false;
      }
    };
    let actualEndCol = endPosRef.col - trailing | 0;
    let align = determineAlignment(ctx, actualStartCol, actualEndCol);
    let node_location = {
      start: startPos,
      end_: endPosRef
    };
    let node = {
      location: node_location,
      content: content,
      align: align
    };
    return {
      TAG: "TextNode",
      _0: node
    };
  }
}

function make() {
  return V2ElementParser.make("Text", Priority.text, canParse, parse);
}

let priority = Priority.text;

export {
  priority,
  canParse,
  determineAlignment,
  parse,
  make,
}
/* No side effect */
