// Generated by ReScript, PLEASE EDIT WITH CARE


function make(kind, text, position, endPosition) {
  return {
    kind: kind,
    text: text,
    position: position,
    endPosition: endPosition
  };
}

function isEof(tok) {
  let match = tok.kind;
  if (typeof match !== "object") {
    return match === "EOF";
  } else {
    return false;
  }
}

function isNewline(tok) {
  let match = tok.kind;
  if (typeof match !== "object") {
    return match === "Newline";
  } else {
    return false;
  }
}

function isWhitespace(tok) {
  let match = tok.kind;
  if (typeof match !== "object") {
    return false;
  } else {
    return match.TAG === "Whitespace";
  }
}

function kindToString(kind) {
  if (typeof kind !== "object") {
    switch (kind) {
      case "Identifier" :
        return "Identifier";
      case "Plus" :
        return "Plus";
      case "Pipe" :
        return "Pipe";
      case "LBracket" :
        return "LBracket";
      case "RBracket" :
        return "RBracket";
      case "LParen" :
        return "LParen";
      case "RParen" :
        return "RParen";
      case "LAngle" :
        return "LAngle";
      case "RAngle" :
        return "RAngle";
      case "Colon" :
        return "Colon";
      case "Hash" :
        return "Hash";
      case "Dollar" :
        return "Dollar";
      case "LBrace" :
        return "LBrace";
      case "RBrace" :
        return "RBrace";
      case "Asterisk" :
        return "Asterisk";
      case "Quote" :
        return "Quote";
      case "At" :
        return "At";
      case "Comma" :
        return "Comma";
      case "QuestionMark" :
        return "QuestionMark";
      case "Newline" :
        return "Newline";
      case "EOF" :
        return "EOF";
    }
  } else {
    switch (kind.TAG) {
      case "Dashes" :
        return `Dashes(` + kind._0.toString() + `)`;
      case "Equals" :
        return `Equals(` + kind._0.toString() + `)`;
      case "Underscores" :
        return `Underscores(` + kind._0.toString() + `)`;
      case "Whitespace" :
        return `Whitespace(` + kind._0.toString() + `)`;
      case "Other" :
        return `Other(` + kind._0 + `)`;
    }
  }
}

export {
  make,
  isEof,
  isNewline,
  isWhitespace,
  kindToString,
}
/* No side effect */
