// Generated by ReScript, PLEASE EDIT WITH CARE


function getErrorMessage(code) {
  switch (code) {
    case "InvalidIdFormat" :
      return "Error: Invalid ID format - ID line must contain only #id";
    case "MultipleIdDeclarations" :
      return "Error: Multiple ID declarations in container";
    case "UnclosedInput" :
      return "Error: Unclosed Input boundary - missing '__]'";
    case "UnclosedString" :
      return "Error: Unclosed string literal - missing '\"'";
    case "UnclosedContainer" :
      return "Error: Unclosed container - missing bottom border";
    case "MissingBlockDeclaration" :
      return "Error: Missing block declaration - add @scene: or @component:";
    case "NestedBlockDeclaration" :
      return "Error: @scene/@component cannot be nested inside another block";
    case "MaxDepthExceeded" :
      return "Error: Container nesting exceeded maxDepth";
  }
}

function getWarningMessage(code) {
  if (typeof code !== "object") {
    switch (code) {
      case "PropOutsideComponent" :
        return "Warning: PropPlaceholder outside @component - will render as literal";
      case "MixedDividerLabelId" :
        return "Warning: Mixed label and ID in divider - treating as text";
      case "MissingCheckboxLabel" :
        return "Warning: Checkbox without label";
      case "MissingRadioLabel" :
        return "Warning: Radio without label";
      case "MisalignedContainerCorner" :
        return "Warning: Container corners are not aligned";
      case "MisalignedContainerWall" :
        return "Warning: Container wall column drifted from the corner";
      case "InconsistentContainerWidth" :
        return "Warning: Top and bottom borders have different widths";
      case "RadioGroupAmbiguous" :
        return "Warning: Could not unambiguously group these radios";
      case "LooksLikeButton" :
        return "Warning: Bracket form looks like a Button but does not match";
      case "LooksLikeInput" :
        return "Warning: Bracket form looks like an Input but does not match";
      case "LooksLikeCheckbox" :
        return "Warning: Bracket form looks like a Checkbox but does not match";
      case "LooksLikeRadio" :
        return "Warning: Paren form looks like a Radio but does not match";
    }
  } else {
    switch (code.TAG) {
      case "UnknownEmoji" :
        return `Warning: Unknown emoji shortcode ':` + code._0 + `:' - rendering as text`;
      case "DuplicatePropName" :
        return `Warning: Duplicate prop '` + code._0 + `' - last declaration wins`;
      case "DuplicateContainerId" :
        return `Warning: Duplicate container id '` + code._0 + `'`;
      case "UnknownPropReference" :
        return `Warning: \${` + code._0 + `} does not appear in @props`;
      case "MultipleRadiosSelected" :
        return `Warning: Multiple selected radios in group '` + code._0 + `'`;
    }
  }
}

function makeError(code, location, recoverableOpt, param) {
  let recoverable = recoverableOpt !== undefined ? recoverableOpt : true;
  return {
    code: code,
    message: getErrorMessage(code),
    location: location,
    recoverable: recoverable
  };
}

function makeWarning(code, location, ruleId, param) {
  return {
    code: code,
    message: getWarningMessage(code),
    location: location,
    ruleId: ruleId
  };
}

export {
  getErrorMessage,
  getWarningMessage,
  makeError,
  makeWarning,
}
/* No side effect */
