// Generated by ReScript, PLEASE EDIT WITH CARE


let zeroPos = {
  row: 0,
  col: 0,
  offset: 0
};

let zeroLoc = {
  start: zeroPos,
  end_: zeroPos
};

function getLocation(node) {
  return node._0.location;
}

function getNodeType(node) {
  switch (node.TAG) {
    case "SceneNode" :
      return "Scene";
    case "ComponentNode" :
      return "Component";
    case "ContainerNode" :
      return "Container";
    case "TextNode" :
      return "Text";
    case "ButtonNode" :
      return "Button";
    case "LinkNode" :
      return "Link";
    case "InputNode" :
      return "Input";
    case "SelectNode" :
      return "Select";
    case "CheckboxNode" :
      return "Checkbox";
    case "RadioNode" :
      return "Radio";
    case "DividerNode" :
      return "Divider";
    case "StringNode" :
      return "String";
    case "EmojiNode" :
      return "Emoji";
    case "PropPlaceholderNode" :
      return "PropPlaceholder";
    case "ErrorNode" :
      return "Error";
  }
}

function isBlockNode(node) {
  switch (node.TAG) {
    case "SceneNode" :
    case "ComponentNode" :
      return true;
    default:
      return false;
  }
}

function getChildren(node) {
  switch (node.TAG) {
    case "SceneNode" :
      return node._0.children;
    case "ComponentNode" :
    case "ContainerNode" :
      return node._0.children;
    default:
      return;
  }
}

let emptyLayout_groups = [];

let emptyLayout = {
  direction: "Column",
  groups: emptyLayout_groups,
  distribution: undefined
};

export {
  zeroPos,
  zeroLoc,
  getLocation,
  getNodeType,
  isBlockNode,
  getChildren,
  emptyLayout,
}
/* No side effect */
