// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Slugify from "../utils/Slugify.mjs";
import * as Heuristics from "../utils/Heuristics.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";
import * as TokenStream from "../lexer/TokenStream.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as V2ParserRegistry from "../elements/V2ParserRegistry.mjs";

let defaultOptions = {
  strict: false,
  tabSize: 4,
  maxDepth: 10,
  heuristics: Heuristics.emptyPartial,
  emojiRegistry: undefined
};

function readLineContent(stream) {
  let buf = "";
  let keep = true;
  while (keep) {
    let tok = TokenStream.peek(stream);
    let match = tok.kind;
    let exit = 0;
    if (typeof match !== "object") {
      switch (match) {
        case "Newline" :
        case "EOF" :
          keep = false;
          break;
        default:
          exit = 1;
      }
    } else {
      exit = 1;
    }
    if (exit === 1) {
      buf = buf + tok.text;
      TokenStream.next(stream);
    }
  };
  return buf.trim();
}

function parseProps(raw) {
  if (raw.trim() === "") {
    return [
      [],
      []
    ];
  }
  let entries = raw.split(",");
  let parsed = Core__Array.filterMap(entries, e => {
    let entry = e.trim();
    if (entry === "") {
      return;
    }
    let eqIdx = entry.indexOf("=");
    let match = eqIdx < 0 ? [
        entry,
        undefined
      ] : [
        entry.slice(0, eqIdx).trim(),
        entry.slice(eqIdx + 1 | 0, entry.length).trim()
      ];
    let lhs = match[0];
    let match$1 = lhs.endsWith("?") ? [
        lhs.slice(0, lhs.length - 1 | 0),
        true
      ] : [
        lhs,
        false
      ];
    let stripQuotes = s => {
      if (s.length >= 2 && s.startsWith("\"") && s.endsWith("\"")) {
        return s.slice(1, s.length - 1 | 0);
      } else {
        return s;
      }
    };
    return {
      name: stripQuotes(match$1[0].trim()),
      optional: match$1[1],
      defaultValue: match[1]
    };
  });
  let seenIdx = {};
  let dups = [];
  let dedup = [];
  parsed.forEach((p, param) => {
    let prevIdx = seenIdx[p.name];
    if (prevIdx !== undefined) {
      dups.push(p.name);
      dedup[prevIdx] = p;
    } else {
      seenIdx[p.name] = dedup.length;
      dedup.push(p);
    }
  });
  return [
    dedup,
    dups
  ];
}

function parseDeviceType(s) {
  let match = s.trim().toLowerCase();
  switch (match) {
    case "desktop" :
      return "Desktop";
    case "mobile" :
      return "Mobile";
    case "tablet" :
      return "Tablet";
    default:
      return;
  }
}

function detectBlockHeader(stream) {
  let snap = TokenStream.save(stream);
  let at = TokenStream.peek(stream);
  let match = at.kind;
  if (typeof match !== "object" && match === "At") {
    TokenStream.next(stream);
    let id = TokenStream.peek(stream);
    let match$1 = id.kind;
    if (typeof match$1 !== "object" && match$1 === "Identifier" && (id.text === "scene" || id.text === "component")) {
      TokenStream.next(stream);
      let colon = TokenStream.peek(stream);
      let match$2 = colon.kind;
      if (typeof match$2 !== "object") {
        if (match$2 === "Colon") {
          TokenStream.next(stream);
          TokenStream.skipInlineWhitespace(stream);
          let slug = readLineContent(stream);
          let nl = TokenStream.peek(stream);
          let match$3 = nl.kind;
          if (typeof match$3 !== "object" && match$3 === "Newline") {
            TokenStream.next(stream);
          }
          let kind = id.text === "scene" ? "Scene" : "Component";
          return [
            kind,
            Slugify.slugify(slug),
            at.position
          ];
        }
        TokenStream.restore(stream, snap);
        return;
      } else {
        TokenStream.restore(stream, snap);
        return;
      }
    } else {
      TokenStream.restore(stream, snap);
      return;
    }
  } else {
    TokenStream.restore(stream, snap);
    return;
  }
}

function parseHeaderAttrs(stream, wallColsOpt, param) {
  let wallCols = wallColsOpt !== undefined ? Primitive_option.valFromOption(wallColsOpt) : undefined;
  let title;
  let device;
  let transition;
  let props = [];
  let propDups = [];
  let isWallPipe = tok => {
    let match = tok.kind;
    if (typeof match !== "object" && match === "Pipe" && wallCols !== undefined) {
      if (tok.position.col === wallCols[0]) {
        return true;
      } else {
        return tok.position.col === wallCols[1];
      }
    } else {
      return false;
    }
  };
  let keep = true;
  while (keep) {
    let snap = TokenStream.save(stream);
    let at = TokenStream.peek(stream);
    let match = at.kind;
    if (typeof match !== "object") {
      switch (match) {
        case "Pipe" :
          if (isWallPipe(at)) {
            TokenStream.next(stream);
          } else {
            keep = false;
          }
          break;
        case "At" :
          TokenStream.next(stream);
          let id = TokenStream.peek(stream);
          let match$1 = id.kind;
          if (typeof match$1 !== "object" && match$1 === "Identifier" && id.text !== "scene" && id.text !== "component") {
            let key = id.text;
            TokenStream.next(stream);
            let colon = TokenStream.peek(stream);
            let match$2 = colon.kind;
            if (typeof match$2 !== "object" && match$2 === "Colon") {
              TokenStream.next(stream);
              TokenStream.skipInlineWhitespace(stream);
              let value = readLineContent(stream);
              let value$1;
              if (wallCols !== undefined) {
                let trimmed = value.trim();
                value$1 = trimmed.endsWith("|") ? trimmed.slice(0, trimmed.length - 1 | 0).trim() : trimmed;
              } else {
                value$1 = value;
              }
              let nl = TokenStream.peek(stream);
              let match$3 = nl.kind;
              if (typeof match$3 !== "object" && match$3 === "Newline") {
                TokenStream.next(stream);
              }
              switch (key) {
                case "device" :
                  device = parseDeviceType(value$1);
                  break;
                case "props" :
                  let match$4 = parseProps(value$1);
                  props = match$4[0];
                  propDups = match$4[1];
                  break;
                case "title" :
                  title = value$1;
                  break;
                case "transition" :
                  transition = value$1;
                  break;
              }
            } else {
              TokenStream.restore(stream, snap);
              keep = false;
            }
          } else {
            TokenStream.restore(stream, snap);
            keep = false;
          }
          break;
        case "Newline" :
          TokenStream.next(stream);
          break;
        default:
          keep = false;
      }
    } else if (match.TAG === "Whitespace") {
      TokenStream.next(stream);
    } else {
      keep = false;
    }
  };
  return [
    title,
    device,
    transition,
    props,
    propDups
  ];
}

function parseContent(ctx, registry, stream) {
  let children = [];
  let keep = true;
  let isPastBound = () => {
    let b = ctx.parseBoundRow;
    if (b !== undefined) {
      return TokenStream.peek(stream).position.row >= b;
    } else {
      return false;
    }
  };
  let isWallPipe = tok => {
    let match = tok.kind;
    let match$1 = ctx.wallCols;
    if (typeof match === "object") {
      return false;
    }
    if (match !== "Pipe") {
      return false;
    }
    if (match$1 === undefined) {
      return false;
    }
    let tol = ctx.heuristics.containerColumnTolerance;
    let c = tok.position.col;
    let near = t => {
      if (c >= (t - tol | 0)) {
        return c <= (t + tol | 0);
      } else {
        return false;
      }
    };
    if (near(match$1[0])) {
      return true;
    } else {
      return near(match$1[1]);
    }
  };
  while (keep && !TokenStream.isAtEnd(stream) && !isPastBound()) {
    let snap = TokenStream.save(stream);
    let match = detectBlockHeader(stream);
    if (match !== undefined) {
      TokenStream.restore(stream, snap);
      keep = false;
    } else {
      TokenStream.restore(stream, snap);
      let tok = TokenStream.peek(stream);
      let match$1 = tok.kind;
      let exit = 0;
      if (typeof match$1 !== "object") {
        switch (match$1) {
          case "Pipe" :
            if (isWallPipe(tok)) {
              TokenStream.next(stream);
            } else {
              exit = 1;
            }
            break;
          case "Newline" :
            TokenStream.next(stream);
            break;
          case "EOF" :
            keep = false;
            break;
          default:
            exit = 1;
        }
      } else if (match$1.TAG === "Whitespace") {
        TokenStream.next(stream);
      } else {
        exit = 1;
      }
      if (exit === 1) {
        let node = V2ParserRegistry.tryParse(registry, ctx, stream);
        if (node !== undefined) {
          children.push(node);
        } else {
          TokenStream.next(stream);
        }
      }
    }
  };
  return children;
}

export {
  defaultOptions,
  readLineContent,
  parseProps,
  parseDeviceType,
  detectBlockHeader,
  parseHeaderAttrs,
  parseContent,
}
/* No side effect */
