// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(blockType, blockSlug, propsOpt, heuristics, tokens, gridIndex, source, maxDepthOpt, tabSizeOpt, parseBoundRowOpt, wallColsOpt, emojiRegistryOpt, param) {
  let props = propsOpt !== undefined ? propsOpt : [];
  let maxDepth = maxDepthOpt !== undefined ? maxDepthOpt : 10;
  let tabSize = tabSizeOpt !== undefined ? tabSizeOpt : 4;
  let parseBoundRow = parseBoundRowOpt !== undefined ? Primitive_option.valFromOption(parseBoundRowOpt) : undefined;
  let wallCols = wallColsOpt !== undefined ? Primitive_option.valFromOption(wallColsOpt) : undefined;
  let emojiRegistry = emojiRegistryOpt !== undefined ? Primitive_option.valFromOption(emojiRegistryOpt) : undefined;
  return {
    blockType: blockType,
    blockSlug: blockSlug,
    props: props,
    containerDepth: 0,
    errors: [],
    warnings: [],
    heuristics: heuristics,
    tokens: tokens,
    gridIndex: gridIndex,
    source: source,
    maxDepth: maxDepth,
    tabSize: tabSize,
    containerStack: /* [] */0,
    pendingNestedBlockRow: undefined,
    pendingNestedBlockBoundRow: undefined,
    pendingNestedBlockWallCols: undefined,
    emojiRegistry: emojiRegistry,
    parseBoundRow: parseBoundRow,
    wallCols: wallCols
  };
}

function addError(ctx, err) {
  ctx.errors.push(err);
}

function addWarning(ctx, w) {
  ctx.warnings.push(w);
}

function isInComponent(ctx) {
  let match = ctx.blockType;
  return match !== "Scene";
}

function enterContainer(ctx, bounds) {
  if ((ctx.containerDepth + 1 | 0) > ctx.maxDepth) {
    return false;
  } else {
    ctx.containerDepth = ctx.containerDepth + 1 | 0;
    ctx.containerStack = {
      hd: bounds,
      tl: ctx.containerStack
    };
    return true;
  }
}

function exitContainer(ctx) {
  if (ctx.containerDepth <= 0) {
    return;
  }
  ctx.containerDepth = ctx.containerDepth - 1 | 0;
  let match = ctx.containerStack;
  if (match !== 0) {
    ctx.containerStack = match.tl;
    return;
  }
}

function currentContainerBounds(ctx) {
  let match = ctx.containerStack;
  if (match !== 0) {
    return match.hd;
  }
}

export {
  make,
  addError,
  addWarning,
  isInComponent,
  enterContainer,
  exitContainer,
  currentContainerBounds,
}
/* No side effect */
