// Generated by ReScript, PLEASE EDIT WITH CARE


let string = 115;

let containerId = 110;

let propPlaceholder = 105;

let emoji = 100;

let select = 95;

let input = 90;

let radio = 85;

let checkbox = 80;

let button = 70;

let link = 60;

let dividerLabeledBold = 50;

let dividerLabeled = 48;

let dividerId = 45;

let divider = 40;

let container = 10;

let text = 1;

export {
  string,
  containerId,
  propPlaceholder,
  emoji,
  select,
  input,
  radio,
  checkbox,
  button,
  link,
  dividerLabeledBold,
  dividerLabeled,
  dividerId,
  divider,
  container,
  text,
}
/* No side effect */
