// Visual Verifier — index.ts
//
// Combines three independent signals into a single verification score:
//   - Cycle edit distance (always available, no extra deps)
//   - Pixel SSIM         (requires htmlToBitmap)
//   - Region IoU          (requires htmlToBitmap)
//
// All metrics are normalized to [0, 1] (higher = better). The final score
// is a weighted average over whichever metrics could be computed.
//
// See ml-parser/self-improvement.md §2-§4 for the role of this component
// in the ML self-improvement loop.

import type {
  Bitmap,
  HtmlToBitmap,
  MetricResult,
  VerifyInput,
  VerifyOptions,
  VerifyResult,
  VerifyWeights,
} from "./types.js";

import { asciiToBitmap } from "./render/asciiToBitmap.js";
import { cycleEditDistance } from "./metrics/cycleEditDistance.js";
import { pixelSSIM } from "./metrics/pixelSSIM.js";
import { regionIoU } from "./metrics/regionIoU.js";

const DEFAULT_WEIGHTS: VerifyWeights = { cycle: 0.5, ssim: 0.3, iou: 0.2 };

// Lazy V2 Renderer binding (analogous to printer in cycleEditDistance).
// V2Parser.parse() returns a SceneBlock/ComponentBlock, so we call
// renderBlockToString. Renderer.defaultOptions() supplies sensible defaults.
type RendererModule = {
  defaultOptions: () => unknown;
  renderBlockToString: (block: unknown, options: unknown) => string;
};
let cachedRenderer: RendererModule | null = null;

async function getRenderer(): Promise<RendererModule> {
  if (cachedRenderer) return cachedRenderer;
  // @ts-ignore — generated by ReScript
  const mod = (await import("../renderer/v2/V2Renderer.mjs")) as RendererModule;
  cachedRenderer = mod;
  return mod;
}

/**
 * Verify how faithfully an ML-produced V2 AST represents its ASCII input.
 *
 * Always runs cycle edit distance.
 * If `input.htmlToBitmap` is supplied, also runs pixel SSIM and region IoU
 * after rendering the AST to HTML via the V2 Renderer.
 */
export async function verify(
  input: VerifyInput,
  options: VerifyOptions = {}
): Promise<VerifyResult> {
  const weights: VerifyWeights = {
    cycle: options.weights?.cycle ?? DEFAULT_WEIGHTS.cycle,
    ssim: options.weights?.ssim ?? DEFAULT_WEIGHTS.ssim,
    iou: options.weights?.iou ?? DEFAULT_WEIGHTS.iou,
  };

  const warnings: string[] = [];

  // 1. Cycle edit distance — always available.
  const cycle = await cycleEditDistance(input.ascii, input.ast);

  // 2 & 3. Pixel SSIM + Region IoU — require htmlToBitmap.
  let pixelSSIMResult: MetricResult | undefined;
  let regionIoUResult: MetricResult | undefined;

  if (input.htmlToBitmap) {
    try {
      const renderer = await getRenderer();
      const rendererOpts = renderer.defaultOptions();
      const html = renderer.renderBlockToString(input.ast, rendererOpts);
      const htmlBitmap = await input.htmlToBitmap(html);
      const asciiBitmap = asciiToBitmap(input.ascii);

      pixelSSIMResult = pixelSSIM(asciiBitmap, htmlBitmap, options.ssimWindow);
      regionIoUResult = regionIoU(
        asciiBitmap,
        htmlBitmap,
        options.iouGrid,
        options.iouThreshold
      );
    } catch (err) {
      const msg =
        err instanceof Error ? err.message : String(err);
      warnings.push(`htmlToBitmap pipeline failed: ${msg}`);
    }
  } else {
    warnings.push(
      "htmlToBitmap not supplied; pixel SSIM and region IoU skipped"
    );
  }

  // Compute weighted score over whichever metrics ran.
  const components: Array<[number, number]> = [
    [cycle.score, weights.cycle],
  ];
  if (pixelSSIMResult) components.push([pixelSSIMResult.score, weights.ssim]);
  if (regionIoUResult) components.push([regionIoUResult.score, weights.iou]);

  const totalWeight = components.reduce((s, [, w]) => s + w, 0);
  const weightedSum = components.reduce((s, [v, w]) => s + v * w, 0);
  const score = totalWeight === 0 ? 0 : weightedSum / totalWeight;

  return {
    score,
    metrics: {
      cycleEditDistance: cycle,
      pixelSSIM: pixelSSIMResult,
      regionIoU: regionIoUResult,
    },
    warnings,
  };
}

// Re-exports so consumers can use individual metrics, build custom pipelines,
// or write their own HtmlToBitmap adapter.
export { asciiToBitmap } from "./render/asciiToBitmap.js";
export { cycleEditDistance } from "./metrics/cycleEditDistance.js";
export { pixelSSIM } from "./metrics/pixelSSIM.js";
export { regionIoU } from "./metrics/regionIoU.js";
export { levenshtein, normalizedEditDistance } from "./compare/levenshtein.js";
export { ssim, ssimToScore, padToCommonSize } from "./compare/ssim.js";

export type {
  Bitmap,
  HtmlToBitmap,
  MetricResult,
  VerifyInput,
  VerifyOptions,
  VerifyResult,
  VerifyWeights,
} from "./types.js";
