// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Lexer from "./lexer/Lexer.mjs";
import * as V2Types from "./types/V2Types.mjs";
import * as V2Errors from "./types/V2Errors.mjs";
import * as GridIndex from "./lexer/GridIndex.mjs";
import * as Validator from "./validator/Validator.mjs";
import * as Heuristics from "./utils/Heuristics.mjs";
import * as BlockParser from "./parser/BlockParser.mjs";
import * as EmojiParser from "./elements/EmojiParser.mjs";
import * as RadioParser from "./elements/RadioParser.mjs";
import * as TokenStream from "./lexer/TokenStream.mjs";
import * as ParseContext from "./parser/ParseContext.mjs";
import * as RadioGrouper from "./layout/RadioGrouper.mjs";
import * as SelectParser from "./elements/SelectParser.mjs";
import * as StringParser from "./elements/StringParser.mjs";
import * as V2LinkParser from "./elements/V2LinkParser.mjs";
import * as V2TextParser from "./elements/V2TextParser.mjs";
import * as DividerParser from "./elements/DividerParser.mjs";
import * as V2InputParser from "./elements/V2InputParser.mjs";
import * as LayoutInferrer from "./layout/LayoutInferrer.mjs";
import * as V2ButtonParser from "./elements/V2ButtonParser.mjs";
import * as ContainerParser from "./elements/ContainerParser.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as V2CheckboxParser from "./elements/V2CheckboxParser.mjs";
import * as V2ParserRegistry from "./elements/V2ParserRegistry.mjs";
import * as PropPlaceholderParser from "./elements/PropPlaceholderParser.mjs";

function makeRegistry() {
  let reg = V2ParserRegistry.make();
  V2ParserRegistry.register(reg, StringParser.make());
  V2ParserRegistry.register(reg, PropPlaceholderParser.make());
  V2ParserRegistry.register(reg, EmojiParser.make());
  V2ParserRegistry.register(reg, SelectParser.make());
  V2ParserRegistry.register(reg, V2InputParser.make());
  V2ParserRegistry.register(reg, RadioParser.make());
  V2ParserRegistry.register(reg, V2CheckboxParser.make());
  V2ParserRegistry.register(reg, V2ButtonParser.make());
  V2ParserRegistry.register(reg, V2LinkParser.make());
  V2ParserRegistry.register(reg, DividerParser.make());
  V2ParserRegistry.register(reg, ContainerParser.make());
  V2ParserRegistry.register(reg, V2TextParser.make());
  return reg;
}

function advanceToNextHeader(stream, pipeNoiseOpt, param) {
  let pipeNoise = pipeNoiseOpt !== undefined ? pipeNoiseOpt : false;
  let header;
  let keep = true;
  while (keep && !TokenStream.isAtEnd(stream)) {
    let tok = TokenStream.peek(stream);
    let match = tok.kind;
    let exit = 0;
    if (typeof match !== "object") {
      switch (match) {
        case "Pipe" :
          if (pipeNoise) {
            TokenStream.next(stream);
          } else {
            exit = 1;
          }
          break;
        case "Newline" :
          TokenStream.next(stream);
          break;
        case "EOF" :
          keep = false;
          break;
        default:
          exit = 1;
      }
    } else if (match.TAG === "Whitespace") {
      TokenStream.next(stream);
    } else {
      exit = 1;
    }
    if (exit === 1) {
      let h = BlockParser.detectBlockHeader(stream);
      if (h !== undefined) {
        header = h;
        keep = false;
      } else {
        TokenStream.skipToEndOfRow(stream);
      }
    }
  };
  return header;
}

function parseOneBlock(source, tokens, gridIndex, stream, registry, options, kind, slug, startPos, parseBoundRowOpt, wallColsOpt) {
  let parseBoundRow = parseBoundRowOpt !== undefined ? Primitive_option.valFromOption(parseBoundRowOpt) : undefined;
  let wallCols = wallColsOpt !== undefined ? Primitive_option.valFromOption(wallColsOpt) : undefined;
  let match = BlockParser.parseHeaderAttrs(stream, Primitive_option.some(wallCols), undefined);
  let props = match[3];
  let blockType;
  blockType = kind === "Scene" ? "Scene" : "Component";
  let ctx = ParseContext.make(blockType, slug, props, Heuristics.applyPartial(options.heuristics, Heuristics.default), tokens, gridIndex, source, options.maxDepth, options.tabSize, Primitive_option.some(parseBoundRow), Primitive_option.some(wallCols), Primitive_option.some(options.emojiRegistry), undefined);
  match[4].forEach(name => ParseContext.addWarning(ctx, V2Errors.makeWarning({
    TAG: "DuplicatePropName",
    _0: name
  }, {
    start: startPos,
    end_: startPos
  }, undefined, undefined)));
  let rawChildren = BlockParser.parseContent(ctx, registry, stream);
  let children = RadioGrouper.assignGroupsRecursive(rawChildren, slug, Heuristics.applyPartial(options.heuristics, Heuristics.default));
  let layout = LayoutInferrer.inferLayout(children, undefined, undefined);
  let loc_end_ = TokenStream.position(stream);
  let loc = {
    start: startPos,
    end_: loc_end_
  };
  let block;
  block = blockType === "Scene" ? ({
      TAG: "SceneBlock",
      _0: {
        location: loc,
        slug: slug,
        title: match[0],
        device: match[1],
        transition: match[2],
        children: children,
        layout: layout
      }
    }) : ({
      TAG: "ComponentBlock",
      _0: {
        location: loc,
        slug: slug,
        props: props,
        children: children,
        layout: layout
      }
    });
  let match$1 = Validator.validate(block);
  let r = ctx.pendingNestedBlockRow;
  let pending = r !== undefined ? [
      r,
      ctx.pendingNestedBlockBoundRow,
      ctx.pendingNestedBlockWallCols
    ] : undefined;
  return [
    block,
    ctx.errors.concat(match$1[0]),
    ctx.warnings.concat(match$1[1]),
    pending
  ];
}

let normalizeOptions = (function(opts, dflt) {
    if (opts === undefined || opts === null) return dflt;
    return {
      strict: opts.strict !== undefined ? opts.strict : dflt.strict,
      tabSize: opts.tabSize !== undefined ? opts.tabSize : dflt.tabSize,
      maxDepth: opts.maxDepth !== undefined ? opts.maxDepth : dflt.maxDepth,
      heuristics: opts.heuristics !== undefined && opts.heuristics !== null
        ? opts.heuristics
        : dflt.heuristics,
      emojiRegistry: opts.emojiRegistry !== undefined && opts.emojiRegistry !== null
        ? opts.emojiRegistry
        : dflt.emojiRegistry,
    };
  });

function parse(source, optionsOpt, param) {
  let options = optionsOpt !== undefined ? optionsOpt : BlockParser.defaultOptions;
  let options$1 = normalizeOptions(options, BlockParser.defaultOptions);
  let tokens = Lexer.tokenize(options$1.tabSize, source);
  let gridIndex = GridIndex.make(tokens);
  let stream = TokenStream.make(tokens);
  let registry = makeRegistry();
  ContainerParser.setRegistry(registry);
  let blocks = [];
  let allErrors = [];
  let allWarnings = [];
  let keep = true;
  let nextLookupPipeNoise = false;
  let nextParseBoundRow;
  let nextWallCols;
  let nextIsPropagated = false;
  while (keep) {
    let pipeNoise = nextLookupPipeNoise;
    let parseBoundRow = nextParseBoundRow;
    let wallCols = nextWallCols;
    let isPropagated = nextIsPropagated;
    nextLookupPipeNoise = false;
    nextParseBoundRow = undefined;
    nextWallCols = undefined;
    nextIsPropagated = false;
    let match = advanceToNextHeader(stream, pipeNoise, undefined);
    if (match !== undefined) {
      let startPos = match[2];
      if (isPropagated) {
        allErrors.push(V2Errors.makeError("NestedBlockDeclaration", {
          start: startPos,
          end_: startPos
        }, true, undefined));
      }
      let match$1 = parseOneBlock(source, tokens, gridIndex, stream, registry, options$1, match[0], match[1], startPos, Primitive_option.some(parseBoundRow), Primitive_option.some(wallCols));
      let pendingRow = match$1[3];
      let errs = match$1[1];
      blocks.push(match$1[0]);
      let strict = options$1.strict;
      errs.forEach(e => {
        let e2 = strict ? ({
            code: e.code,
            message: e.message,
            location: e.location,
            recoverable: false
          }) : e;
        allErrors.push(e2);
      });
      match$1[2].forEach(w => {
        allWarnings.push(w);
      });
      if (strict && errs.length > 0) {
        keep = false;
      }
      if (pendingRow !== undefined) {
        TokenStream.rewindToRow(stream, pendingRow[0]);
        nextLookupPipeNoise = true;
        nextParseBoundRow = pendingRow[1];
        nextWallCols = pendingRow[2];
      } else if (parseBoundRow !== undefined && TokenStream.peek(stream).position.row < parseBoundRow) {
        nextParseBoundRow = parseBoundRow;
        nextWallCols = wallCols;
        nextLookupPipeNoise = true;
        nextIsPropagated = true;
      }
    } else {
      keep = false;
    }
  };
  if (blocks.length === 0) {
    return {
      ast: undefined,
      blocks: [],
      errors: [V2Errors.makeError("MissingBlockDeclaration", V2Types.zeroLoc, false, undefined)],
      warnings: [],
      success: false
    };
  }
  let success = allErrors.length === 0;
  return {
    ast: blocks[0],
    blocks: blocks,
    errors: allErrors,
    warnings: allWarnings,
    success: success
  };
}

function parseWireframe(source) {
  return parse(source, undefined, undefined);
}

let defaultOptions = BlockParser.defaultOptions;

let version = "2.3.0";

let implementation = "rescript-v2";

export {
  defaultOptions,
  makeRegistry,
  advanceToNextHeader,
  parseOneBlock,
  normalizeOptions,
  parse,
  parseWireframe,
  version,
  implementation,
}
/* EmojiParser Not a pure module */
