// PublicApi.test.ts
// End-to-end TypeScript smoke test of the V2 renderer's public surface.
// Mirrors what an external consumer would import.
//
// Verifies:
// - renderToString called from JS
// - renderToStringWithDiagnostics returns [html, warnings]
// - parser/v2 → V2 renderer composition works on real ASCII source
// - default options exposes the expected fields
//
// DOM-mode (renderToDOM) requires a DOM environment; we skip the live
// mount test here and rely on the ReScript-side unit tests when jsdom
// is available.

import { describe, test, expect } from "vitest";
// @ts-ignore — generated by ReScript
import * as V2Renderer from "../V2Renderer.mjs";
// @ts-ignore
import * as V2Parser from "../../../parser/v2/V2Parser.mjs";

const source = `@scene: login
@title: Login
@device: mobile

+----------------+
|  'Welcome'     |
|  [__email__]   |
|  [ Sign In ]   |
+----------------+`;

describe("V2 Renderer public API (TS smoke)", () => {
  test("defaultOptions returns the expected shape", () => {
    const opts = V2Renderer.defaultOptions();
    expect(opts.classPrefix).toBe("wf-");
    expect(opts.idPrefix).toBe("wf-");
    expect(opts.syntheticIdSalt).toBe("v2");
    expect(opts.includeSourceLocations).toBe(true);
  });

  test("renderBlockToString turns a parsed scene into an HTML string", () => {
    const parsed = V2Parser.parse(source);
    expect(parsed.success).toBe(true);
    expect(parsed.ast).toBeDefined();
    const opts = V2Renderer.defaultOptions();
    const html = V2Renderer.renderBlockToString(parsed.ast, opts);
    expect(typeof html).toBe("string");
    expect(html.startsWith("<section")).toBe(true);
    expect(html).toContain("wf-scene");
    expect(html).toContain("wf-device-mobile");
    // We rendered a sign-in button with id 'sign-in'.
    expect(html).toContain("wf-button");
  });

  test("renderBlockToStringWithDiagnostics returns a tuple", () => {
    const parsed = V2Parser.parse(source);
    const opts = V2Renderer.defaultOptions();
    const tuple = V2Renderer.renderBlockToStringWithDiagnostics(
      parsed.ast,
      opts
    );
    // ReScript tuples surface as arrays in JS.
    expect(Array.isArray(tuple)).toBe(true);
    expect(tuple.length).toBe(2);
    expect(typeof tuple[0]).toBe("string");
    expect(Array.isArray(tuple[1])).toBe(true);
  });

  test("byte-identical output for the same input", () => {
    const parsed = V2Parser.parse(source);
    const opts = V2Renderer.defaultOptions();
    const a = V2Renderer.renderBlockToString(parsed.ast, opts);
    const b = V2Renderer.renderBlockToString(parsed.ast, opts);
    expect(a).toBe(b);
  });

  test("version metadata is exposed", () => {
    expect(typeof V2Renderer.version).toBe("string");
    expect(typeof V2Renderer.implementation).toBe("string");
  });
});
