// cycleEditDistance.ts
// Cycle-consistency metric: ASCII A vs A' where A' = V2Printer.print(ast).
//
// This is the primary signal that an ML model preserved the input's
// structure when mapping ASCII → V2 AST. The V2 ASCII Printer is
// deterministic (per its spec), so any drift between A and A' indicates
// real semantic difference, not printer randomness.
//
// See ml-parser/self-improvement.md §3.1 (Loop A).

import type { MetricResult } from "../types.js";
import { levenshtein } from "../compare/levenshtein.js";

// Lazy bind — V2Printer is a ReScript-generated .mjs and would force a
// build dep on every test file that imports this module. We dynamically
// import on first use and cache the binding.
//
// The printer exposes `print` (for individual AST nodes) and `printBlock`
// (for SceneBlock / ComponentBlock variants). V2Parser.parse() returns a
// Block, so we default to `printBlock`. Callers can override via options.
type PrinterModule = {
  defaultOptions: () => unknown;
  print: (ast: unknown, opts: unknown) => string;
  printBlock: (block: unknown, opts: unknown) => string;
};
let cachedPrinter: PrinterModule | null = null;

async function getPrinter(): Promise<PrinterModule> {
  if (cachedPrinter) return cachedPrinter;
  // @ts-ignore — generated by ReScript
  const mod = (await import("../../printer/v2/V2Printer.mjs")) as PrinterModule;
  cachedPrinter = mod;
  return mod;
}

/**
 * Allow tests / custom configurations to inject a printer (e.g. mock or
 * alternate options). When provided, takes precedence over the lazy import.
 */
export interface CycleOptions {
  /** Custom printer function. Receives the AST as-is and must return a string. */
  printer?: (ast: unknown) => string;
}

/**
 * Compute the cycle edit distance metric.
 *
 * Score = 1 − (editDistance / max(len(A), len(A'))).
 * A score of 1.0 means A and A' are identical; lower means structural drift.
 */
export async function cycleEditDistance(
  ascii: string,
  ast: unknown,
  options: CycleOptions = {}
): Promise<MetricResult> {
  let printed: string;
  if (options.printer) {
    printed = options.printer(ast);
  } else {
    const printer = await getPrinter();
    const opts = printer.defaultOptions();
    printed = printer.printBlock(ast, opts);
  }

  const distance = levenshtein(ascii, printed);
  const maxLen = Math.max(ascii.length, printed.length);
  const normalized = maxLen === 0 ? 0 : distance / maxLen;
  const score = Math.max(0, 1 - normalized);

  return { score, raw: distance };
}
