// Generated by ReScript, PLEASE EDIT WITH CARE

import * as V2Types from "../types/V2Types.mjs";
import * as V2Errors from "../types/V2Errors.mjs";
import * as Core__Dict from "@rescript/core/src/Core__Dict.mjs";
import * as Heuristics from "../utils/Heuristics.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";

function walkAst(root, f) {
  let go = node => {
    f(node);
    let children = V2Types.getChildren(node);
    if (children !== undefined) {
      children.forEach(go);
      return;
    }
  };
  go(root);
}

function validate(block) {
  let errs = [];
  let warns = [];
  let root;
  root = block.TAG === "SceneBlock" ? ({
      TAG: "SceneNode",
      _0: block._0
    }) : ({
      TAG: "ComponentNode",
      _0: block._0
    });
  let declaredProps = {};
  if (block.TAG !== "SceneBlock") {
    block._0.props.forEach(p => {
      declaredProps[p.name] = true;
    });
  }
  let seenIds = {};
  let radioGroups = {};
  let radioGroupLoc = {};
  let checkPropRef = p => {
    let isComponent;
    isComponent = block.TAG !== "SceneBlock";
    if (isComponent && declaredProps[p.name] === undefined) {
      warns.push(V2Errors.makeWarning({
        TAG: "UnknownPropReference",
        _0: p.name
      }, p.location, undefined, undefined));
      return;
    }
  };
  let checkDupId = (id, loc) => {
    let count = Core__Option.getOr(seenIds[id], 0);
    if (count > 0) {
      warns.push(V2Errors.makeWarning({
        TAG: "DuplicateContainerId",
        _0: id
      }, loc, undefined, undefined));
    }
    seenIds[id] = count + 1 | 0;
  };
  walkAst(root, node => {
    switch (node.TAG) {
      case "ContainerNode" :
        let c = node._0;
        let id = c.id;
        if (id !== undefined) {
          return checkDupId(id, c.location);
        } else {
          return;
        }
      case "TextNode" :
        let tn = node._0;
        let c$1 = tn.content;
        let ruleId = Heuristics.Rule.nearMissPatterns;
        let emit = code => {
          warns.push(V2Errors.makeWarning(code, tn.location, ruleId, undefined));
        };
        if (!(c$1.startsWith("[") && !c$1.includes("]"))) {
          if (c$1.startsWith("(") && !c$1.includes(")")) {
            return emit("LooksLikeRadio");
          } else {
            return;
          }
        }
        if (c$1.startsWith("[__")) {
          return emit("LooksLikeInput");
        }
        if (c$1.length < 2) {
          return emit("LooksLikeButton");
        }
        let ch1 = c$1.charAt(1);
        if (ch1 === "x" || ch1 === "X" || ch1 === "v" || ch1 === "V" || ch1 === " ") {
          return emit("LooksLikeCheckbox");
        } else {
          return emit("LooksLikeButton");
        }
      case "ButtonNode" :
      case "LinkNode" :
      case "SelectNode" :
        break;
      case "RadioNode" :
        let r = node._0;
        let g = r.group;
        if (g === undefined) {
          return;
        }
        let n = Core__Option.getOr(radioGroups[g], 0);
        radioGroups[g] = n + (
          r.selected ? 1 : 0
        ) | 0;
        if (r.selected && radioGroupLoc[g] === undefined) {
          radioGroupLoc[g] = r.location;
          return;
        } else {
          return;
        }
      case "StringNode" :
        node._0.interpolations.forEach(seg => {
          switch (seg.TAG) {
            case "PropRef" :
              return checkPropRef(seg._0);
            case "Literal" :
            case "EmojiRef" :
              return;
          }
        });
        return;
      case "PropPlaceholderNode" :
        return checkPropRef(node._0);
      default:
        return;
    }
    let b = node._0;
    checkDupId(b.id, b.location);
  });
  Core__Dict.forEachWithKey(radioGroups, (count, g) => {
    if (count < 2) {
      return;
    }
    let loc = Core__Option.getOr(radioGroupLoc[g], V2Types.zeroLoc);
    warns.push(V2Errors.makeWarning({
      TAG: "MultipleRadiosSelected",
      _0: g
    }, loc, undefined, undefined));
  });
  return [
    errs,
    warns
  ];
}

export {
  walkAst,
  validate,
}
/* No side effect */
