// Generated by ReScript, PLEASE EDIT WITH CARE


function buildDefaults() {
  let d = {};
  d["check"] = "✔";
  d["cross"] = "✘";
  d["warning"] = "⚠";
  d["info"] = "ℹ";
  d["heart"] = "❤";
  d["star"] = "\u{2B50}";
  d["search"] = "\u{1F50D}";
  d["settings"] = "⚙";
  d["user"] = "\u{1F464}";
  d["home"] = "\u{1F3E0}";
  d["mail"] = "✉";
  d["bell"] = "\u{1F514}";
  d["lock"] = "\u{1F512}";
  d["bow"] = "\u{1F647}";
  return d;
}

let mutableRegistry = {
  contents: buildDefaults()
};

function lookup(shortcode) {
  return mutableRegistry.contents[shortcode];
}

function register(shortcode, emoji) {
  mutableRegistry.contents[shortcode] = emoji;
}

function reset() {
  mutableRegistry.contents = buildDefaults();
}

let isNullOverride = (function(o) { return o === null; });

function lookupWithOverride(overrides, shortcode) {
  if (overrides === undefined) {
    return mutableRegistry.contents[shortcode];
  }
  if (isNullOverride(overrides)) {
    return mutableRegistry.contents[shortcode];
  }
  let found = overrides[shortcode];
  if (found !== undefined) {
    return found;
  } else {
    return mutableRegistry.contents[shortcode];
  }
}

export {
  buildDefaults,
  mutableRegistry,
  lookup,
  register,
  reset,
  isNullOverride,
  lookupWithOverride,
}
/* mutableRegistry Not a pure module */
